### ISSUE TITLE
Truncation and text wrapping for data table cells

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#1003]
## Summary
There needs to a way to truncate long content within a data table cell so that a single row doesn't take up too much vertical space. Conversely, there also needs to be a text wrap option so row heights can automatically be set based on content. 

## 💰 User value
This allows more data to displayed in a table at a time, and helps to automatically define the height of rows. 

## 📚 User Stories
If relevant, describe the high-level functionality as user stories.

*As an* ICDS user: 
*I need* to be able to set a data table cell to wrap text
*So that* the entire cell content can be visible. 

*As an* ICDS user
*I need* to be able to set a data table cell to truncate
*So that* the row height can be kept small for large content. 

## 📝 Acceptance Criteria 
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

**Text wrap**
*Given* that a cell exists in a table
*When* it is set to 'text-wrap'
*Then* it should automatically resize to fit all lines of text,
*And* the column width should not be altered.  

*Given* that a column exists in a table
*When* it is set to 'text-wrap'
*Then* all cells in that column should resize to fit all lines of text, 
*And* the column width should not be altered. 

*Given* that a cell has been set to text-wrap
*When* it resizes, and it becomes the tallest cell in a row,
*Then* the row that it resides in should resize to contain the cell,
*And* other cells should add whitespace to fill, 
*And* the other cells should adhere to their alignment properties. 

*Given* that a cell has been set to text-wrap
*When* it resizes, but there are other taller cells in the row,
*Then* the row that it resides in should maintain its size, 
*And* the text wrap cell should add whitespace to fill, 
*And* it should adhere to its alignment properties. 

*Given* that a table cell is currently set to wrap
*When* something else then occurs to adjust the row height, 
*Then* the wrapping property should be removed 
*and* the cell should follow normal truncation pattern. 

**Truncation**

*Given* that a cell has a set height and width,
*When* its contents is larger than can be displayed in the cell, 
*Then* it wrap onto multiple lines if space is available, 
*And* the remaining text should be truncated with an ellipsis. 

*Given* that a cell is truncated
*When* its size changes, either by column width changing, or row height changing
*Then* the text should resize to fill the available space. 

*Given* that a truncated text cell exists
*When* hovering over its contents,
*Then* a tooltip should display containing the full cell contents, but be limited to 6 lines of text before it also truncates. 
(for really long content, we will need a method to be able to display the full text, either in future by providing ability to change column width and row height, or by setting text wrap)
(should the lines of text visible in a tooltip be customisable?)
(How wide should the tooltip be? Do tooltips have a max-width?)

**NOTE**: Line-clamping and max-width adjustments for ic-tooltip will be completed as part of a seperate issue

**Optional see more/less button**
*Given* that a text cell exists, and the text is truncated
*When* setting its properties
*Then*an option exists to set the typography element's see more/less functionality,
*And* if set then a see more button should appear on a new line under the truncated text, 
*And* the row height should expand to fit the content if necessary. 

*Given* that a text cell is truncated, and the typography component see more function is set, 
*When* the see more button is clicked
*Then* the full text should be displayed, 
*And* the row height should be adjusted to fit, 
*And* the 'see more' button should switch to a 'see less' button, still situated on a new line below the untruncated text.  

*Given* that a truncated text cell is expanded
*When* clicking the 'see less' button, 
*Then* the cell should revert to the collapsed state
*and* the previous row-height should be set
*and* the 'see less' button should revert to 'see more'.

## ✏ Designs
If there's a Figma design file (or other mock-up), include it here.

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by jd239** [comment]
> Given that a table cell is currently set to wrap
When something else then occurs to adjust the row height,
Then the wrapping property should be removed
and the cell should follow normal truncation pattern.

Should this be the case when more space is added to the row?
