### ISSUE TITLE
Horizontal card layout option

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#1025]
## Summary
Cards are often used to list a number of simple data items. The current vertical card layout does not suit these situations well as it takes up a lot of vertical space. A horizontal layout would enable more use cases to be achieved and denser layouts. 

## 💰 User value
Provides more flexibility into the card component so it can be used in more situations. Allows denser layouts to be achieved which is important for complex applications that need to show lots of data in a single screen without scrolling. 

## 📚 User Stories
If relevant, describe the high-level functionality as user stories.

*As an* ICDS user: 
*I need* a horizontal layout card
*So that* I can show my data in a more desne layout. 

## 📝 Acceptance Criteria 
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

*Given*
*When* 
*Then*

## ✏ Designs
If there's a Figma design file (or other mock-up), include it here.

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by MI6-255** [comment]
Add guidance for this on the site

**Comment by MI6-255** [comment]
Will be a canary component
