### ISSUE TITLE
[ic-side-navigation] react router app title shows when it's not expanded

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1033]
## Summary of the bug
In the react router example in storybook it shows that the app title shows slightly before the side navigation has been expanded, when it should just show the icon.

This has been spotted to be an issue when using nav link in the app title instead of the standard `<a>`.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Go to react storybook
2. Click on: Side navigation
3. Click on: react router
4. See the error

## 🧐 Expected behaviour
Only the icon should show if it's not expanded.

## 📸 Screenshots or code
<img width="380" alt="Screenshot 2023-08-24 at 11 29 18" src="https://github.com/mi6/ic-ui-kit/assets/111882034/ef1f07d3-f627-484b-9807-68dbb83a118a">

**Comment by ad9242** [comment]
fixed in 2.5.0 release
