### ISSUE TITLE
[ic-search-bar/ic-select/ic-tooltip/ic-popover-menu]: Issue with components which contain a popover not appearing correctly in content areas which have `overflow:hidden`.

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#1059]
## Summary of the bug 
A few ICDS components use PopperJS to provide popover functionality to our components such as:
- Search Bar
- Select
- Tooltip

If these components are used within an area where `overflow:hidden` is applied, the popover is cut off and not 'layered' on top.

**PLEASE NOTE:** This ticket also cover additional icDialog bugs:
- https://github.com/mi6/ic-ui-kit/issues/1053
- https://github.com/mi6/ic-ui-kit/issues/1057
- https://github.com/mi6/ic-ui-kit/issues/1041

(These issues have been closed with all updates placed in this ticket)

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Clone repo and build storybook 
2. Add `ic-select` with options to a dialog. 
3. Add overflow hidden to `.content-area` in ic-dialog CSS.
4. Comment out `:host([data-overflow=` styles
5. Click the select component to view options
6. See the error 

## 📸 Screenshots or code 
![Capture](https://github.com/mi6/ic-ui-kit/assets/116016939/6f0527ef-3191-437a-8e2c-60d7bd88d2c9)

## 🖥 📱 Device 
- Type: N/A
- Device: N/A
- OS version: N/A
- Browser version: N/A

## 🧐 Expected behaviour 
Menu should appear without being constrained by the content area. 

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given that I am an app user* 
*When I click or hover on a component which uses a popover*  
*Then I should be able to see all the menu items, tooltips or popover menu items without any obstruction* 

## Additional info 
This fix will need to be applied to all other components which use the PopperJS package or popover style.

**Comment by ASM995** [comment]
This ticket is blocking Accordion comp from being released.

**Comment by jd239** [comment]
Linked to #1057

**Comment by jd239** [comment]
https://github.com/mi6/ic-ui-kit/issues/1053 fix added to ticket
