### ISSUE TITLE
Rename max-length prop on text fields to something more understandable

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#1064]
## Summary 
The existing prop max-length is used to display a character count. The terminology used here is a bit confusing, as max-length may cause misunderstanding of its function when compared with maxLength, as it doesn't actually limit the number of characters that can be entered into the field.

## 💬 Description 

**Existing max-length prop**
This property currently is used to show the character count. The terminology here is incorrect, as it it doesn't actually affect the maximum allowable input characters, but instead sets the value of the character count. The user can still enter more characters than the character count into the field.

Change naming to more accurately describe what this prop does. This is a breaking change as users may already be using this prop name in their code. 

## 💰 Use value 
Makes it easier to understand the different properties available on text field. 

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.  

*Given* 
*When*  
*Then* 

## ✏ Designs 
If there's a Figma design file (or other mock-up), include it here. 

## 🧾 Guidance 
If there's written guidance or documentation, include a link to it here.  

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by DBD324** [comment]
Relates to #604

**Comment by MI6-255** [comment]
Scrap max-length and have a prop to show max characters. Design to clarify if this is okay

**Comment by GCHQ-Developer-094** [comment]
According to site docs we have both properties max-characters and max-length, with the outcome of previous ticket 604 simply stating to just make the description clearer for max-length in the documentation. 

I'd suggest scrap max-length, use max-characters and just add another boolean property something along the lines of hideCharCount.
