### ISSUE TITLE
SlottedSVG Icons shifted in IcButton

### ISSUE THREAD

**Issue by MI6-613** [mi6/ic-ui-kit#1065]
In 2.3.0 all slottedSvgs with MdiIcons the icons are no longer correctly positioned and are shifted so only the top left corner is shown.

**Comment by MI6-255** [comment]
As part of this issue, could we add MDI Icons to our Visual Tests to prevent issues like this

**Comment by MI6-255** [comment]
This is a React component which we don't use Loki with yet
