### ISSUE TITLE
Lock version of web-components in the react package.json

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1089]
## Summary 
currently react package.json contains the following for dependencies:
```
"dependencies": {
    "@ukic/fonts": "^2.2.0",
    "@ukic/web-components": "^2.2.0"
 },
```

However, this could lead to potential problems if a developer locks the component version in their app. 

For example, if a react app developer locked the versions in their app package.json as follows:
```
"@ukic/fonts": "2.2.0",
"@ukic/react": "2.2.0",
```

then when running `npm install`

the latest web-components package (currently 2.4.0 as of writing) is pulled in, which could lead to incompatibilities.

## 💬 Description 
A full description of what the improvement should be and how it should work. 

## 💰 Use value 
this would prevent users getting incompatibility between the react & web components packages.

## 📝 Acceptance Criteria  

Given an app developer locks the version of the react package in their app
When they install the react components
Then the version of the web-components package installed, it should exactly match

## Additional info 
Need to work out how to have the version number updated for release, but lock the dependency version. A workaround would be to add guidance along the lines of 

"if you lock the react components to a particular version, you should also install (& lock) the corresponding web components package"

**Comment by MI6-255** [comment]
Look into the release and if this will mean the version wouldn't be updated?
