### ISSUE TITLE
[@ukic/react]: Build and test React infrastructure

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#1098]
## Summary 
At the moment, most of the testing and builds are targeted for the core web-components build. This is also required for React in order to improve it's stability. 

## 💬 Description 
The outcome of this ticket should be:
- QA build for React Storybook
- Generate Loki tests in particular tests using unique React components such as `SlottedSVG`
- Potentially Component and Unit tests. This should be covered in the web-components tests but the nature of React may make this a requirement. Potentially use Cypress?
- Add documentation to CONTRIBUTING.md regarding React testing

## 💰 Use value 
This is to reduce the pain points with using the React wrapped components. Improve testing capabilities.

## ✏ Designs 
N/A

##  🧾 Guidance 
N/A

## Additional info 
N/A

**Comment by MI6-255** [comment]
Testing anything specific to React e.g. wrapped SVG

**Comment by MI6-255** [comment]
Is this a duplicate now
