### ISSUE TITLE
Fix legacy peer dependency workaround

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#11]
## Summary of the bug
Fix legacy peer dependency workaround. Exploration work required first.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Delete all package-locks
2. Try to npm install without --legacy-peer-dep flag
3. It will fail

## 🧐 Expected behaviour
Npm install to work without the --legacy-peer-dep flag

**Comment by GCHQ-Developer-741** [comment]
Currently ic-design-system has a conflicting peer dependency relating to Gatsby. We use Gatsby 4.2.0, which is suitable as a peer dependency for most of the plugins we use, apart from 1 (https://github.com/jonearley/gatsby-plugin-stencil). There is a [pull request](https://github.com/jonearley/gatsby-plugin-stencil/pull/10) in review to update the peer dependency to Gatsby version 4. However until this is merged, would need to either leave the flag in place, or downgrade the guidance site to Gatsby 2, like bringing in many other issues and requiring significant development capacity.
