### ISSUE TITLE
Performance testing components

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1119]
## Summary 
Explore how we can performance test ICDS components

## 💬 Description 
This spike should explore how we can performance test our components, which will be relevant for all components, but especially the larger components such as data table. 

The outcome should be a set of issues of how we progress with performance testing in terms of technology and what we'll test. It would be worth trying out the options.

## 💰 Use value 
To ensure what ICDS release will not cause any bottlenecks in teams ability to release or use apps efficiently.

## Additional information
- Previous issues with memory leaks may be relevant here as it will feed into this ticket
- The slight flicker of components may factor into this

**Comment by j212122** [comment]
Following from the above comment, I was unable to recreate this scenario. Attempted to configure Cypress e2e tests with the aim of testing a component in storybook (as per iconic example- 100+ of a single component on a page) using Cypress lighthouse plugin. I was unable to run lighthouse tests using Edge, and could not get Cypress to recognise Chrome was installed.

Thoughts:
It is possible to generate a lighthouse HTML report which may give specific details relating to performance so we can pinpoint where there may be issues.

https://github.com/mi6/ic-ui-kit/tree/test/perfomance-testing
^ branch has the required config for anyone wanting to attempt the above.

**Comment by MI6-286** [comment]
I have been able to get the Lighthouse plugin to work using the E2E Cypress configuration and Chrome to test the Storybook example that is mentioned in the previous comment. However, the performance scores are very low, so this would require further investigation. 

The required config is on this branch: 
[ ](https://github.com/mi6/ic-ui-kit/tree/1119-performance-testing)

**Comment by MI6-255** [comment]
Is this completed?
