### ISSUE TITLE
side navigation hidden behind sticky page header

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1142]
## Summary of the bug 
On smaller device sizes, the expanded side navigation gets hidden behind a sticky page header. 

## 🪜 How to reproduce 
1. Go to page: https://mi6.github.io/ic-ui-kit/branches/develop/?path=/story/patterns-component-z-index--component-z-index
2. Change viewport size to tablet or smaller
3. Expand the side nav
4. See side nav content hidden behind page header

## 📸 Screenshots or code 
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/80e557f3-3eba-4057-a1a1-a0c379eb40eb)

## 🧐 Expected behaviour 
expanded side navigation should overlay all content on smaller devices

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* a side navigation and sticky page header are on a page on  small device
*When*  the side nav panel is expanded
*Then* it should overlay the sticky page header

## Additional info 
may just be a case of increasing the z-index variable for side nav. if so, guidance site page may need updating to new value too

**Comment by Shubh8899** [comment]
I would like to work on this.
