### ISSUE TITLE
Review focus state for disabled options in menus

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1155]
## Summary 
There is currently an inconsistency in the focus state for disabled items on menus. We should review ic-searchbar, ic-select & ic-popover-menu to ensure a consistent approach.

## 💬 Description 
ic-popover-menu allows disabled item to be focussed & applies styling to them
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/ea61928b-9be4-4c6c-9c9d-06f5a59336e8)

ic-searchbar & ic-select do not allow the items to be focussed & they are skipped when navigating through the options with the keyboard

## 💰 Use value 
Ensure consistency across all menu components.

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by MI6-255** [comment]
Marked as duplicate
