### ISSUE TITLE
Use more specific class names when adding to host element

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1156]
## Summary 
In some components, class names are added to the host element. This can lead to problems as some of the class names are quite generic eg "icon", "dark", "light", "link". If consumers have styles in their global css such as

```
.icon{
  width: 50px;
height: 50px;
}
```

Then that styling is applied to our components.

## 💬 Description 
The class names applied on the host elements for our components should be more specific eg "ic-icon", "ic-dark", "ic-light", "ic-link" etc

a list of components affected (this should be validated)

- ic-checkbox-group
- ic-classification-banner
- ic-data-entity
- ic-date-picker
- ic-link
- ic-navigation-button
- ic-popover-menu
- ic-radio-group
- ic-radio-option
- ic-text-field
- ic-tooltip
May need to update this list

## 💰 Use value 
Would make consumers lives easier as our components would not change their styling if they have clashing class names

## 📝 Acceptance Criteria  

*Given* 
*When*  
*Then* 

Suggestion is to keep classes on the host, but just make them more unique. if there are cases where the developer thinks it makes more sense to move onto an inner element, then that could be done

**Comment by MI6-255** [comment]
May have breaking changes
