### ISSUE TITLE
File upload option for IcButton

### ISSUE THREAD

**Issue by MI6-613** [mi6/ic-ui-kit#1175]
It is not uncommon for a button to be used to upload a file. By clicking on the button the file explorer is launched and file selected. Text is then placed to the side of the button with the filename. This is done in html by setting the attribute "input=file". If you could allow this for IcButton that would be great.

**Comment by MI6-255** [comment]
Early thoughts here is that we'd also need to expose some sort of changed event to be aware of what the file selected is potentially. If we're doing this work, it'd be worth considering how much extra work a basic file upload component would be

**Comment by ASM995** [comment]
closing as duplicate

**Comment by DBD324** [comment]
Duplicated by #1050
