### ISSUE TITLE
All tab panels visible if app does not import normalize.css

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1179]
## Summary of the bug 
if using ic-tab components, then all tab panel are visible unless the app also imports normalize.css

## 🪜 How to reproduce 
go to: https://stackblitz.com/edit/stackblitz-starters-ugobse?file=src%2FApp.tsx
see all tabs visible

## 📸 Screenshots or code 
```
<IcTabContext contextId="myTabs">
    <IcTabGroup label="Example tab group">
      <IcTab>One</IcTab>
      <IcTab>Two</IcTab>
      <IcTab>Three</IcTab>
    </IcTabGroup>
    <IcTabPanel>Tab One</IcTabPanel>
    <IcTabPanel>Tab Two</IcTabPanel>
    <IcTabPanel>Tab Three</IcTabPanel>
  </IcTabContext>
```

![image](https://github.com/mi6/ic-ui-kit/assets/116102637/c20d2620-4a88-4f5a-9e41-3dff149be80a)

## 🧐 Expected behaviour 
Only the selected tab should be visible

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* there are tabs on a page
*When*  a tab is selected
*Then* only the content for that tab should be visible

## Additional info 
think there are 2 options for this:
1) we could add an import of normalize.css into the ic-tab-panel component, which would then just apply the [hidden] styling
or
2) do we look at adding a class onto the element & apply the css ourselves. more work but would help us move away from normalize.css
this is also similar to https://github.com/mi6/ic-ui-kit/issues/1156

**Comment by jd239** [comment]
To keep implementation consistent across all components, add the normalize.css file to component.
