### ISSUE TITLE
Research into if/how bindings are used in Angular

### ISSUE THREAD

**Issue by GCHQ-Developer-398** [mi6/ic-ui-kit#1186]
## Summary 
Look into how and where bindings can be used in angular.

## 💬 Description 
Now that the starter app is there, look into those interactive components a bit more to figure out some of the more complex stuff. Look into bindings, in angular: https://www.w3schools.com/angular/angular_databinding.asp. It might help with why some of the other components aren't fully working.

**Comment by GCHQ-Developer-530** [comment]
Covered by #1185
