### ISSUE TITLE
Add Cypress unit tests for initial components

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1187]
## Summary
As part of #1166, need to add unit tests for the initial 3 components selected for investigation. This work should be carried out on the duplicated repo created under #1184

Components to test:

- [ ] IcButton
- [ ] IcTopNavigation
- [ ] IcSelect

this should include investigating how to track code coverage

**Comment by MI6-255** [comment]
https://docs.cypress.io/api/cypress-api/custom-commands

**Comment by MI6-255** [comment]
Mital is on Button on this

**Comment by MI6-255** [comment]
Closing as we won't be migrating unit tests
