### ISSUE TITLE
Split component code into separate files

### ISSUE THREAD

**Issue by GCHQ-Developer-398** [mi6/ic-ui-kit#1189]
## Summary 
Split component code into separate files - to test component functionality in Angular

## 💬 Description 
Split some of the components out from the file into separate files so that JavaScript can be applied to specific components (like the dialog and popover menu that are not working). They may not be working because script tags aren't really a thing in angular. The JavaScript should instead go in the .ts file.

**Comment by GCHQ-Developer-530** [comment]
Covered by #1185
