### ISSUE TITLE
Add Cypress to main repo  remove old testing

### ISSUE THREAD

**Issue by j212122** [mi6/ic-ui-kit#1196]
## Summary

Install Cypress in main repo and remove old testing from the installs/pipeline/code (e.g. old e2e, accessibility, loki etc)

## 💬 Description 

Initial set up is straightforward and instructions can be found here:

https://docs.cypress.io/guides/getting-started/installing-cypress
-note the additional steps required for Linux users noted further down the article 
- does not appear to work when using SSH

**Comment by MI6-255** [comment]
Has all the experimenting with x3 components been reviewed already? If not, do we need to break down the migration so it can be reviewed properly

**Comment by MI6-255** [comment]
PR per component
