### ISSUE TITLE
Dark mode: look into different appearances for components

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1214]
## Summary 
Currently some components have default, light and dark appearances, and a couple are missing either light or dark. We should investigate and design the missing appearances where necessary.

If you haven't done a component before, reach out to @GCHQ-Developer-530 , @ad9242 , @gd2910 or @GCHQ-Developer-741 who can walk you through the process to help you get started.

## 💬 Description 
Components that need looking into are:
- [x] - Accordion - @GCHQ-Developer-847
- [x] - Alert - @GCHQ-Developer-530
- [x] - Back to top -  @ad9242 
- [x] - Badge - @GCHQ-Developer-530
- [x] - Breadcrumb - @GCHQ-Developer-530
- [x] - Button - @gd2910 
- [x] - Card - @GCHQ-Developer-741 
- [x] - Card - Horizontal - @GCHQ-Developer-741 
- [x] - Checkbox - @GCHQ-Developer-530
- [x] - Chip @gd2910 @ad9242
- [x] - Classification banner - @GCHQ-Developer-530
- [x] - Data entity - @GCHQ-Developer-530
- [x] - Data table - @GCHQ-Developer-741 
- [x] - Date input - @ad9242
- [x] - Date picker - @ad9242
- [x] - Dialog - @GCHQ-Developer-530
- [x] #2527 @gd2910  - theme tokens added to old ic-divider, ready to be cherry-picked into new [ic-divider](https://github.com/mi6/ic-ui-kit/issues/1331) 
- [x] - Empty state - @GCHQ-Developer-530
- [x] - Footer - @GCHQ-Developer-530
- [x] - Hero - @GCHQ-Developer-530
- [x] - Horizontal scroll (This is reliant on button, and impacts the work in page header, tabs and top nav, for now do a work around for appearance on horizontal scroll) @gd2910 done as part of button work
- [x] - Link - @GCHQ-Developer-530
- [x] - Loading indicator - @GCHQ-Developer-741
- [x] - Multi-select - @GCHQ-Developer-741 
- [x] - Navigation Bar - ready for dev (seems to be part of top nav so will tick off when that's done
- [x] - Page header - @GCHQ-Developer-112
- [x] - Pagination - @GCHQ-Developer-530
- [x] - Popover menu - @gd2910 
- [x] - Radio button - @GCHQ-Developer-530
- [x] - Search bar - @GCHQ-Developer-530
- [x] - Section container
- [x] - Select - @GCHQ-Developer-741 
- [x] - Side navigation - @gd2910 Unskip vis reg tests when fixed
- [x] - Skeleton - @GCHQ-Developer-741 
- [x] - Status tag - @GCHQ-Developer-530 
- [x] - Stepper - @GCHQ-Developer-530
- [x] - Switch - @GCHQ-Developer-530
- [x] - Tabs - @GCHQ-Developer-530 - Unskip vis reg tests when fixed
- [x]  - Table of Content - @GCHQ-Developer-847
- [x] - Text field - @GCHQ-Developer-741 
- [x] - Toast - @GCHQ-Developer-847
- [x] - Toggle button - @GCHQ-Developer-530
- [x] - Tooltip - @ad9242 
- [x] - Top navigation - @GCHQ-Developer-530
- [x] - Treeview - @GCHQ-Developer-530
- [x] - Typography @ad9242 
- [x] - Atoms - @GCHQ-Developer-530

This ticket involves working on these parts:

- [x] 1. First, implement the "data-mode"/theme component so dark mode can be set once in a central place - done
- [x] 2. Implement the pattern of the "Theme" prop and changing to dark mode at a component level (following the list of components above) and add appropriate tests
- [x] 3. Implementing the "Theme" prop and ability for it to recognise dark mode at the global level on each component and the testing that goes with it (mentioned in internal notes) - theme prop is now implemented on ic-theme component 

Make sure to reference internal dark modes on implementation

## 💰 User value 
Users will have the same appearances they can apply to all components rather than some having missing options.

**Comment by MI6-255** [comment]
See internal notes, ask me for them if needed

**Comment by MI6-255** [comment]
Can initially number 1 in it's full, but also make a start with a pattern for point 2

**Comment by GCHQ-Developer-112** [comment]
This ticket is reliant on https://github.com/mi6/ic-ui-kit/issues/2289. Before picking up a component, please check that it's been marked as ready to dev.

**Comment by ad9242** [comment]
once [#2379 ](https://github.com/mi6/ic-ui-kit/pull/2379) is merged work can begin on other components
