### ISSUE TITLE
[ic-radio-option] Create small and large sizes

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1220]
## Summary 
Similar to #643 where we created size variants of checkboxes, we should create different size variants of radio options.

## 💬 Description 
There should be a small, default and large sizes for radio options.

Currently, radio group only has small and default size so we may want to look into a large size for radio group so that they're inline with each other. If #1213 has been completed then there should already be a large radio group so we won't have to worry about it.

## 💰 User value 
Having a set of components all with same size options allows easier layout and switching between page densities by changing all component sizes at once.

## 📚 User Stories 
As a user
I need a way to change the size of radio options
so that they can align with other components of the same size.

## 📝 Acceptance Criteria  
Given that a developer is implmenting a radio option
When setting its properties
Then they should be able to select from the following size options:
- Default
- Small
- Large

**Comment by Ismith507** [comment]
Hello, is this issue still open?

**Comment by GCHQ-Developer-094** [comment]
Included as part of #1213
