### ISSUE TITLE
Indeterminate checkbox functionality

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#1222]
## Summary 
We have the ability to set checkboxes to an indeterminate state, but doing so does not affect any child checkboxes. The checkbox group component should be updated to allow nesting of checkboxes and the correct operation of indeterminate checkboxes. 

## 💬 Description 
Indeterminate checkboxes are displayed when not all children are selected. This control also provides a quick method to then select or deselect all children. 

## 💰 Use value 
Provides a quick method to select/deselect many options at once in a complex checkbox list. 

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.  

*Given* that a checkbox group is being set up, 
*When* specifying its options
*Then* the ability to nest checkboxes below a parent should be available. 

*Given* that a parent checkbox exists, and is currently unselected
*When* it is clicked (or triggered via keyboard or other assistive tech)
*Then* it should become selected, 
*And* all child checkboxes should be selected automatically.   

*Given* that a parent checkbox exists, and is currently selected
*When* it is clicked (or triggered via keyboard or other assistive tech)
*Then* it should become unselected, 
*And* all child checkboxes should be unselected automatically.  

*Given* that a parent checkbox exists with a number of children checkboxes
*When* a child checkbox is selected or deselected, 
*And* this results in **some, but not all,** child checkboxes being selected
*Then* the parent checkbox should automatically update to show its indeterminate state. 

*Given* that a parent checkbox exists with a number of children checkboxes
*When* a child checkbox is selected or deselected, 
*And* this results in **all** child checkboxes being selected
*Then* the parent checkbox should automatically update to show its selected state. 

*Given* that a parent checkbox exists with a number of children checkboxes
*When* a child checkbox is selected or deselected, 
*And* this results in **no** child checkboxes being selected
*Then* the parent checkbox should automatically update to show its unselected state. 

## ✏ Designs 
If there's a Figma design file (or other mock-up), include it here. 

## 🧾 Guidance 
If there's written guidance or documentation, include a link to it here.  

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by ad9242** [comment]
Closing this issue. After discussions with @jd239, @GCHQ-Developer-530, @GCHQ-Developer-094, decided that this functionality should not be part of the checkbox component itself.
Other checkboxes (including native) do not provide this functionality and it feels inappropriate that an individual checkbox should need to be concerned about it's parent\children
If required, investigation can be done to provide a code sample of how to achieve this behaviour, or a wrapper component could be considered which would do this.
