### ISSUE TITLE
Loading Indicator cannot be seen on initial page load

### ISSUE THREAD

**Issue by MI6-613** [mi6/ic-ui-kit#1231]
When a loading indicator is loaded onto a page with no conditional rendering it cannot be seen

**Comment by GCHQ-Developer-299** [comment]
Hi @MI6-613  could you provide more context or a code snippet please? This will enable us to test the issue more easily :) 

Normally the `New issue` process generates a ticket template that provides headings for screenshots/steps to replicate/etc. - was that not your experience?
