### ISSUE TITLE
[ic-dialog] dismiss icon button does not show in safari

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1242]
## Summary of the bug 
View any of the dialog stories in storybook on safari, the dismiss icon is there as you can see the tooltip and focus, but it doesn't actually visually show anything.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to dialog stories on safari
2. Open a dialog
3. See no dismiss icon button

## 📸 Screenshots or code 
<img width="439" alt="Screenshot 2023-11-06 at 13 14 39" src="https://github.com/mi6/ic-ui-kit/assets/111882034/ac8404ed-7872-4ed3-adc3-707978a4a9d0">

## 🖥 📱 Device 
- Type: Desktop
- Device: MacBook
- Browser version: Safari 17.1

## 🧐 Expected behaviour 
Should be able to see the dismiss button.

**Comment by ASM995** [comment]
Linked to #1263
