### ISSUE TITLE
[ic-dialog]: Dismiss button on dialog does not appear correctly

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-ui-kit#1263]
## Summary of the bug 
The dismiss button in the top right does not appear. However, when hovering in the area, the hover state for the button appears

## 🪜 How to reproduce 

1. Navigate to the ["Code" tab of the "Dialog" component page](https://design.sis.gov.uk/components/dialog/code) on the guidance site
2. Select a dialog
3. Hover in top right

## 🖥 📱 Device 
- Device: MacBook
- Browser version: Safari 16

## 🧐 Expected behaviour 
Dismiss icon button should be displayed.

## Additional info 
May be an issue with the SVG rather than the button itself

Raised by: @jd239

**Comment by ASM995** [comment]
Closed as duplicate of #1242
