### ISSUE TITLE
H2 & H3 errors on ICDS website

### ISSUE THREAD

**Issue by GCHQ-Developer-485** [mi6/ic-ui-kit#1293]
## Summary of the bug 
When inspecting the titles on the ICDS component pages what is graphically displayed does not match with the code

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to page: ['...' ](https://design.sis.gov.uk/components/badge)
2. Open the inspect function
3. Hover over the title that says 'Introduction' or 'Component variants'
4. Notice how the code states that it is a H3 title, whereas visibly it is a H2 title.

## 🖥 📱 Device 
- Type: Desktop
- Device: MacBook
- OS version: macOS Sonoma
- Browser version: Safari 17.1

## 🧐 Expected behaviour 
The titles styles used for the  'Introduction' and 'Component variants' should match what the code says. I.e. if it shows a H2 title (as it currently does) then the code should state H2 not H3.

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* 
*When*  
*Then* 

## Additional info 
Tell us anything else useful to help us fix or understand the problem.

**Comment by jd239** [comment]
This work has been completed as https://github.com/mi6/ic-design-system/pull/688
