### ISSUE TITLE
[ic-top-navigation] navigation items with target blank icons move when focused on small devices

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1298]
## Summary of the bug 
When target is "_blank" for navigation items and the external link icon is shown in the side menu on top nav small devices, the icon moves when the navigation item is focused on.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to top navigation - with navigation story
2. Make screen size small enough that the side menu shows
3. Move focus throughout the menu
4. See every time you focus the item with external link, the icon moves.

## 📸 Screenshots or code 
https://github.com/mi6/ic-ui-kit/assets/111882034/9304f5d2-866c-4d5a-ad94-703323cb3be0

## 🖥 📱 Device 
- Type: Mobile simulation in dev tools
- Device: MacBook
- Browser version: Chrome

## 🧐 Expected behaviour 
The icon should stay in the same place no matter if it is focused or not.

**Comment by GCHQ-Developer-299** [comment]
Tested this out on develop branch's storybook today.
This is no longer an issue, possibly thanks to this recent change (https://github.com/mi6/ic-ui-kit/pull/1306) that removed right padding on focus.

https://github.com/mi6/ic-ui-kit/assets/111292477/c6f5992c-b54d-46c1-a85b-d3d8187dc61f
