### ISSUE TITLE
IcPopover When placed in component smaller than itself it stretches component

### ISSUE THREAD

**Issue by MI6-613** [mi6/ic-ui-kit#1312]
When IcPopover is placed in a component of fixed height smaller than the size of the popover the component will scroll to show the popover rather than the popover appear above the component as with MUI popover.

**Comment by MI6-255** [comment]
@MI6-613 could you provide a code example please and if you had any more information

**Comment by ASM995** [comment]
Closing this issue, please reach out if you have more information.
