### ISSUE TITLE
Add Cypress component testing to each component

### ISSUE THREAD

**Issue by j212122** [mi6/ic-ui-kit#1313]
## Summary

Add Cypress component testing to each component

Create a separate pull request for each component

- [ ] Accordion
- [ ] Back to top
- [ ] Badge
- [ ] Breadcrumb
- [ ] Card
- [ ] Checkbox
- [ ] Chip
- [ ] Classification banner
- [ ] Data entity
- [ ] Data table
- [ ] Date picker
- [ ] Dialog
- [ ] Empty state
- [ ] Footer
- [ ] Hero
- [ ] Link
- [ ] Loading Indicator
- [ ] Page header
- [ ] Pagination
- [ ] Popover menu
- [ ] Radio button
- [ ] Search Bar
- [ ] Section container
- [ ] Side Navigation
- [ ] Skeleton
- [ ] Status tag
- [ ] Stepper
- [ ] Switch
- [ ] Tabs
- [ ] Text field
- [ ] Toast
- [ ] Tooltip
- [ ] Top navigation
- [ ] Typography

**Comment by jd239** [comment]
Issue closed as this task is covered by individual tickets such as https://github.com/mi6/ic-ui-kit/issues/1393
