### ISSUE TITLE
Add Cypress accessibility testing to each component

### ISSUE THREAD

**Issue by j212122** [mi6/ic-ui-kit#1314]
Add Cypress accessibility testing to each component

Create a separate pull request for each component

- [ ]  Accordion
- [ ]  Back to top
- [ ]  Badge
- [ ]  Breadcrumb
- [ ]  Card
- [ ]  Checkbox
- [ ]  Chip
- [ ]  Classification banner
- [ ]  Data entity
- [ ]  Data table
- [ ]  Date picker
- [ ]  Dialog
- [ ]  Empty state
- [ ]  Footer
- [ ]  Hero
- [ ]  Link
- [ ]  Loading Indicator
- [ ]  Page header
- [ ]  Pagination
- [ ]  Popover menu
- [ ]  Radio button
- [ ]  Search Bar
- [ ]  Section container
- [ ]  Side Navigation
- [ ]  Skeleton
- [ ]  Status tag
- [ ]  Stepper
- [ ]  Switch
- [ ]  Tabs
- [ ]  Text field
- [ ]  Toast
- [ ]  Tooltip
- [ ]  Top navigation
- [ ]  Typography

**Comment by jd239** [comment]
Ticket has been converted to individual components.
