### ISSUE TITLE
[ic-classification-banner]: Add `top` prop to Classification Banner

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#1317]
## Summary 
Some development teams have been using the Classification banner at the top of the viewport as well as the bottom. This ticket is to introduce a `top` prop to ic-classification-banner. 

## 💬 Description 
There is a requirement to add a `top` prop to the Classification banner so it appears in a fixed position. Additional updates will be required to:
- ic-top-navigation
- ic-side-navigation

The two navigation components have fixed positioning which conflict with a top classification banner. In particular, the `ic-side-navigation` needs styling updates for both mobile and desktop.

The additional work will require `ic-side/ic-top-navigation` taking into account the classification and position itself correct. Similar work has been completed with the `ic-footer` and `ic-back-to-top`

## 💰 User value 
This will allow developers to set the ic-classification-banner at the top, bottom and inline if required. This provide greater flexibility with it's positioning.

## 📚 User Stories 
If relevant, describe the high-level functionality as user stories. 

*As an* ICDS user:  
*I need* the classification banner at the top
*So that* it is clear the classification of the product

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* 
*When*  
*Then* 

## ✏ Designs 
If there's a Figma design file (or other mock-up), include it here. 

##  🧾 Guidance 
A guidance update is also required. 

![Capture](https://github.com/mi6/ic-ui-kit/assets/116016939/be7a5c26-3e84-4cb8-a5da-3e6e63b9dfe8)

The paragraph providing guidance for printing and exporting may not be technically possible so this needs to be reviewed.

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by MI6-682** [comment]
I'm giving this a go if that's ok, will open a PR soon
