### ISSUE TITLE
Split up the PR checklist into headings

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1328]
## Summary 
Split up the PR checklist/DoD into headings

## 💬 Description 
In order to make the PR checklsit more consumable, split it up into headings, such as any checks for feature changes or even new components. Consider what headings we break them into and how we deal with checks we may do across all changes, to make it more consumable.

## 💰 Use value 
Make the PR checklist more consumable, so it can be easily be consumed

**Comment by ASM995** [comment]
Need to consider different checklists for different repos.
