### ISSUE TITLE
Review Git strategy and improve release process

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1330]
## Summary 
Review Git strategy to assess if it's still the best/easiest way for our release notes, and improve the release process depending on the outcome

## 💬 Description 
Consider if our Git strategy is still the best/easiest way to have clear commits and release notes. With a follow up task to automate more of the release process to replace the "rebasing" step of main into develop, then PRers needing to be rebased from there, this might not be needed depending on the outcome.

Could we consider an easier way, moving away from rebasing and potentially merging, are there issues with that?

## 💰 User value 
Make the release and contributing easier.

**Comment by GCHQ-Developer-465** [comment]
This will relate to the contribution model work as this is an area where contributors failed.

**Comment by MI6-255** [comment]
If we don't do this, consider if we need to improve the release process where the branches need rebasing, to improve that experience
