### ISSUE TITLE
Move "Date input" into canary release

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1364]
## Summary 
Move "Date input" into canary release

## 💬 Description 
The component to be moved out of it's holding branch and into the canary released package. This includes any communications that need to be issued.

## 💰 Use value 
Provide users with the opportunity to test our components, before their beta release.

**Comment by jd239** [comment]
To complete the move to canary, Cypress is required for testing within the canary-react package: https://github.com/mi6/ic-ui-kit/issues/1435
