### ISSUE TITLE
Indeterminate checkbox behavior does not match native checkbox

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#137]
The behaviour of the ic-checkbox indeterminate variant does not match a native html checkbox.

The native checkbox has 3 states: indeterminate, checked: true, checked: false
Once a user clicks on a indeterminate checkbox, it is not possible for them to set that individual checkbox back into the indeterminate state - it just toggles between checked & unchecked.
see: https://www.w3schools.com/jsref/prop_checkbox_indeterminate.asp

With the ic-checkbox component, when using the indeterminate variant, the state toggles between indeterminate and unchecked.
**Should this behave like a native checkbox?**
If we choose not to match a native checkbox we will need to revisit the display in WHCM

The guidance also says "Display the indeterminate selection state when the selection of child elements is mixed. Use the indeterminate checkbox to quickly select or de-select all child elements with one click."
**This functionality is not currently built into the component - should it be?**

**Comment by DBD324** [comment]
Links to ticket #1222 that should fix this problem also.

**Comment by ASM995** [comment]
closed as duplicate ticket.
