### ISSUE TITLE
'spacing' not applied to IcTypography variants of "label"

### ISSUE THREAD

**Issue by MI6-27** [mi6/ic-ui-kit#14]
## Summary of the bug
Noticed while refactoring the website to remove Material-UI; using `spacing` on `IcTypography` doesn't add a bottom margin as expected.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Use `IcTypography` and `spacing` prop
2. Inspecting CSS, or visual observing, no bottom margin is added.

## 🧐 Expected behaviour
Expected a bottom margin to be applied to the element.

### 'label' variant
![image](https://user-images.githubusercontent.com/90763452/199969071-ec403444-8d18-4217-9a33-47a42facc52d.png)

### 'body' variant
![image](https://user-images.githubusercontent.com/90763452/199969163-1e988a63-daae-4275-927c-6fa8d2d54a3f.png)

## 🖥 Desktop
 - OS: macOS
 - Browser: chrome

**Comment by ASM995** [comment]
Need to identify whether this is a problem @DBD324
