### ISSUE TITLE
Stepper: Mobile/Compact

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#140]
## Summary
A more compact version of the current stepper.

## 💰 User value
Users would be able to implement steppers for mobile devices.

#### **Automatic switching**
**Given** that a stepper exists on a page
**When** the container is small or resized so that the stepper steps don't display properly
**Then** the stepper should update to show as a compact stepper. 
(question: should we try to auto change to compact stepper, or give user the option of which version to use?)

#### **Manual override**
**Given** that a stepper exists on a page, 
**When** the number of steps is too great to show on a page, 
**Then** the developer should be able to switch the stepper manually to display the compact version. 

### **Radial indicator**
**Given** that a user is on a step, 
**When** viewing the radial indicator, 
**Then** they should see the indicator filled to the percentage completion of the current step. 
(For example, in a four step process, when on step 1 they see it 25% filled, step 2 it is 50% filled, step 3 it is 75% filled, step 4 it is 100% filled)

**Given** that a step is inactive/disabled, 
**When** viewing the radial indicator, 
**Then** they should see the indicator in its disabled state. 

**Given** that a step is complete, 
**When** viewing the radial indicator,
**Then** it should show the default step state with the step number displayed and the % progress highlighted as normal in the radial indicator. 

### **Step statuses**
**Given** that a step exists in a stepper that is optional
**When** viewing the step
**Then** it should display the 'optional' label. 

**Given** that a step exists in a stepper that is required
**When** viewing the step
**Then** it should display the 'required' label. 

**Given** that a step exists in a stepper that is complete
**When** viewing the step
**Then** it should display the 'complete' label. 

**Given** that a step exists in a stepper that is inactive/disabled
**When** viewing the step
**Then** it should display the 'not required' label. 

**Given** that a step exists in a stepper that doesn't require a status, 
**When** viewing the step, 
**Then** it can display no status label. 

### **Text wrapping**
**Given** that a step exists in a stepper, 
**When** viewing the step, 
**Then** it should display the step title with content wrapped onto multiple lines if required,
**And** it should show the step numbering (e.g 1 of 4) and status label (e.g optional) on the same line, 
**And** it should show the next step label below with content wrapped onto multiple lines if required.

### **Complete steps**
**Given** that a user arrives at a step in a stepper which is complete, (for example via next/previous navigation)
**When** the step is displayed, 
**Then** it should show the complete state. 

**Given** that a user is on a complete step, 
**When** changes are made that render the step incomplete,
**Then** the stepper should change back to its incomplete state (either required, optional, not required, or no status)
(this may be the responsibility of the user to implement as ICDS is unlikely to know what constitutes a complete or incomplete step)

### **Inactive/Disabled Steps**
**Given** that a user is on a step within a stepper, either on full stepper or compact stepper,
**When** they navigate to the next step,
**And** that step is an inactive/disabled step,
**Then** they should be displayed the inactive step contents even though it is inactive. 

## ✏ Designs
If there's a Figma design file (or other mock-up), include it here.

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by DBD324** [comment]
Additional AC for the prop behaviour:

**Given** that a step of any ‘stepType’, or ‘stepStatus’ exists, 
**When** a ‘stepSubtitle’ is provided, 
**Then** the ‘stepSubtitle’ should display in the status message on the default and compact stepper. 

**Given** that a step is created with ‘stepType=complete’,
**When** no ‘stepSubtitle’ is provided, 
**Then** the step should display the default “Complete” text in the status message in the compact stepper. 

**Given** that a step is created with step type ‘disabled’,
**When** no ‘stepSubtitle’ is provided, 
**Then** the step should display the default “Not required” text in the status message in the compact stepper. 

**Given** that a step is created with stepStatus ‘required’,
**When** a step with ‘stepType=active || current’ is provided, 
**Then** the step should display the “Required” text in the status message in the compact stepper. 

**Given** that a step is created with stepStatus ‘optional’,
**When** a step with ‘stepType=active || current’ is provided, 
**Then** the step should display the “Optional” text in the status message in the compact stepper. 

**Given** that a step is created with stepStatus ‘required’ or ‘optional’, 
**When** the step also has ‘stepType=completed || disabled’,
**Then** the step should display the “Complete” or “Disabled” text in the status message in the compact stepper according to the ‘stepType’. 

Prop definitions:
**StepType** - Use this to define what state the step should display. 

**StepStatus** - Use this prop to display a status message on the step if it is required or optional. 

**StepSubtitle** - Use this prop to override the default step status messaging displayed when selecting a step type or step status.
