### ISSUE TITLE
Links with an Icon flicker during hydration

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1408]
## Summary of the bug 
Links with an Icon flicker during hydration

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to the design system homepage
2. Watch "Get started" first render with a space at the end, then remove it, e.g. (Get started_ ->) to (Get started ->)

## 🧐 Expected behaviour 
No flicker on Get started.

## Additional info 
Unclear if this is guidance site related or component related, although it's likely not possible to duplicate in Storybook as currently that does not offer the Static Rendering that Gatsby does.

**Comment by GCHQ-Developer-847** [comment]
See [my comment on another FOUC-related ticket](https://github.com/mi6/ic-ui-kit/issues/1415#issuecomment-1997155336)
