### ISSUE TITLE
Top navigation Icon flickers to repositions itself during hydration

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#1409]
## Summary of the bug 
Top navigation Icon flickers to repositions itself during hydration

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to the ICDS homepage
2. Refresh
3. Watch the ICDS logo in top navigation initially position itself at the top, then reposition to the middle.

## Additional info 
Unclear if this is component based or website related, or possibly even guidance for use of Icons.

**Comment by GCHQ-Developer-847** [comment]
See [my comment on another FOUC-related ticket](https://github.com/mi6/ic-ui-kit/issues/1415#issuecomment-1997155336)
