### ISSUE TITLE
[ic-popover-menu]: Popover menu button not closing open popover menu

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#1413]
## Summary of the bug 
Once the popover menu is opened, clicking on the button which initiated the open state, does not close the popover menu.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to page: https://design.sis.gov.uk/components/popover-menu 
2. Click on the first example within the guidance tab
3. Click it again
4. The popover menu remains open 

## 📸 Screenshots or code 
![image](https://github.com/mi6/ic-ui-kit/assets/116016939/b5b02de9-868a-49ba-8e40-9c38742c32e6)

## 🖥 📱 Device 
- Type: Desktop 
- Device: Macbook
- OS version: N/A
- Browser version: Chrome 120 

## 🧐 Expected behaviour 
The button should toggle the display state of the popover menu.
1. Click button to display popover menu
2. Click button to hide popover menu

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given a user wants to close a context menu* 
*When the button which opened the popover menu is pressed again (while the popover menu is on display)*  
*Then the popover menu should disappear* 

## Additional info 
Tell us anything else useful to help us fix or understand the problem.

**Comment by ad9242** [comment]
There is already a check for `isNotPopoverMenuEl` when there is a click in the document to determine whether the popover should be closed. Hopefully can just extend this to check if the click occurred on the anchor el

**Comment by GCHQ-Developer-530** [comment]
This ticket is just updating the storybook examples so that the button opening popover menu doesn't just set it to open, but sets it to the opposite of its current open state. This should mean it will close when clicked.
