### ISSUE TITLE
[ic-card] Accessibility issue for expandable cards

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1457]
## Summary of the bug 
When running accessibility tests in Cypress for expandable cards, there's an error to do with the aria-controls value we've set.

It can also be replicated running accessibility checks against our site. 

## 📸 Screenshots or code 
<img width="1120" alt="Screenshot 2024-01-31 at 16 06 19" src="https://github.com/mi6/ic-ui-kit/assets/111882034/ac04757f-2a05-4d70-aa7c-0ce14932e6a3">

## 🧐 Expected behaviour 
It should pass accessibility checks so that we can add in Cypress tests for a11y.

**Comment by ASM995** [comment]
Consider accessibility guidance update if required.
