### ISSUE TITLE
[ic-chip] disabled chips don't pass colour contrast tests in cypress

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1505]
## Summary of the bug 
When running cypress tests on chip, the disabled variant does not pass the `cy.checkA11yWithWait()` check because of colour contrast. It can also be replicated running a check against the disabled chip story in storybook.

<img width="992" alt="Colour contrast bug in chips" src="https://github.com/mi6/ic-ui-kit/assets/111882034/1ea25b08-2f19-4f4f-929a-bfa0535b1e42">

## 🧐 Expected behaviour 
It should pass colour contrast tests.

## Additional info 
The suggested colour for the text to be changed to when it's disabled doesn't look great. This ticket might have to go through design to decide what the best path is to ensure we have colour contrast and it still visually looks disabled.

**Comment by MI6-94** [comment]
Check with @GCHQ-Developer-299 whether disabled chips are required to pass this and if not how can we remove this check within Cypress.

**Comment by GCHQ-Developer-299** [comment]
[Disabled interface items are not required to meet constrast values](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum#:~:text=User%20Interface%20Components%20that%20are%20not%20available%20for%20user%20interaction%20(e.g.%2C%20a%20disabled%20control%20in%20HTML)%20are%20not%20required%20to%20meet%20contrast%20requirements.)

The disabled chips do make their inputs (the little cross buttons) as disabled and Voiceover recognises it. So this is a false positive. I'd recommend the fix here being adding `rules: { 'color-contrast': { enabled: false }` into the checkA11yWithWait() function call's 'options' object.
