### ISSUE TITLE
Check all code and ensure alignment to documented naming conventions

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#1509]
## Summary 
Need to review all components, props, slots etc and re-word to align to naming conventions. 

## 💬 Description 
Some of our components use different naming conventions. For example, some events do include the prefix '--ic'. 
Need to go through all code and align to conventions. 

## 💰 Use value 
This will enhance the quality of our code and making it more understandable for users to use.

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.  

*Given* 
*When*  
*Then* 

## ✏ Designs 
If there's a Figma design file (or other mock-up), include it here. 

## 🧾 Guidance 
If there's written guidance or documentation, include a link to it here.  

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by MI6-255** [comment]
Already done
