### ISSUE TITLE
IcSelect React Testing

### ISSUE THREAD

**Issue by enwdefnyddiwr** [mi6/ic-ui-kit#151]
## Summary of the bug
I am unable to fire events on any IcSelect components using Jest / react testing library. It appears the event is simulated because the value changes, but my own provided event handler is not executed. The effect is that having replaced the components I was using with the IC components, my tests are now failing.

## 🪜 How to reproduce
Consider this component:

```
const options = [
  { label: "Option 1", value: "OPTION1" },
  { label: "Option 2", value: "OPTION2" },
  { label: "Option 3", value: "OPTION3" },
  { label: "Option 4", value: "OPTION4" },
  { label: "Option 5", value: "OPTION5" },
];

const Simple = (): ReactElement => {
  const [selectedValue, setSelectedValue] = useState<string | undefined>(
    undefined
  );
  return (
    <IcSelect
      data-testid={`select`}
      onIcChange={(e) => {
        console.log("the event fired.");
        setSelectedValue(e.detail.value);
      }}
      value={selectedValue}
      label={`Test`}
      options={options}
    />
  );
};

export default Simple;
```

Notice the console log in the event handler. This fires when the event is called when the app is running, but not when the following test is run:

```
describe("Simple Tests", () => {
 
  test("change option should work", async () => {
    const { getByTestId } = render(<Simple />);

    await act(async () => {
      fireEvent.click(getByTestId("select"), { target: { value: "OPTION2" } });
    });

    console.log(getByTestId("select"));
    expect(getByTestId("select")).toHaveValue("OPTION2");
  });
});
```

However the test does pass. So it appears the value is being changed by some other means. This is causing a problem where a component calls a callback via a prop, because the mocked callback is not being invoked when expected. Note I've also tried fireEvent.change, with and without the act await, which I'm fairly sure isn't necessary. This also seems to happen with checkboxes. Callbacks out of props is not a great pattern I accept that, but there will most likely be situations where people want their own event handlers to run. 

## 🧐 Expected behaviour
I expect the value to change and the console log statement to execute, or my callback function to be invoked.
 
## Additional info
Thanks for this library. Happy to contribute in any way I can be of use.

**Comment by enwdefnyddiwr** [comment]
Did some further research this morning, and I don't think this is an issue specific to your library but rather just web components and events in react testing. The following link has some interesting things I'm going to try out. Will update this afterwards with my findings as I expect a few people coming from React/Standard HTML projects may encounter this.

https://stackoverflow.com/questions/69075825/how-to-mock-stencil-web-components-by-using-react-testing-library

**Comment by enwdefnyddiwr** [comment]
Worth noting that it's necessary to wait for web components (the technology used underneath the React components if you aren't using the web components directly) to 'hydrate' before running tests on them. So in your jest tests:

```
await waitFor(() => {
 expect(screen.getByTestId("my-button")).toHaveClass(
 "hydrated"
 );
 });
 fireEvent.click('my-button'); // etc
```
 Just pasting here in case someone hits this gotcha.

**Comment by jd239** [comment]
After some testing, this approach outputted the console.log. From my understanding, to trigger the change event, I'm firing it using `new CustomEvent` and then the name of the event which is `icChange`. `icChange` is what it is called on the web-component but when outputting as React wrapped component, it gets prefixed with `on` - `onIcChange`. The change event has a type of EventEmitter which dispatches the event as a Custom Event. https://github.com/mi6/ic-ui-kit/blob/main/packages/web-components/src/components/ic-select/ic-select.tsx#L188

The detail object is what the EventEmitter emits with a value key value: https://github.com/mi6/ic-ui-kit/blob/main/packages/web-components/src/utils/types.ts#L140

```
describe("Simple Tests", () => {
 
  test("change option should work", async () => {
    const { getByTestId } = render(<Simple />);

    fireEvent(getByTestId('select', new CustomEvent('icChange', { detail: { value: 'OPTION2' } }};

    expect(getByTestId("select")).toHaveValue("OPTION2");
  });
});
```

Give this a try. Hopefully it works for you @enwdefnyddiwr

**Comment by jd239** [comment]
Testing ICDS components with RTL has now been added to the guidance site: https://design.sis.gov.uk/get-started/install-components/testing-with-react-testing-library.
