### ISSUE TITLE
Consider enabling type='date' on IcTextField

### ISSUE THREAD

**Issue by enwdefnyddiwr** [mi6/ic-ui-kit#152]
## Summary
As title. With type='date' on IcTextField in my experiments so far, a perfectly usable date picker is rendered, which is plenty for my app's requirements. It defers to the browser implementation of course, so specific functionality isn't controllable but for simple date picking it is a great low-code solution. I'd like to request that you consider adding support for that type value, since at the moment i'm having to use

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore

to get it to work.
Thanks all!

**Comment by DBD324** [comment]
Thanks very much for your contribution. We have purposefully excluded type='Date' on textFields for now as this functionality will be available in the upcoming Date input component that is currently being developed.
