### ISSUE TITLE
[Cypress] Decide a naming convention for cypress snapshots

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1523]
## Summary 
At the moment the cypress baseline snapshots are a mix of kebab case, camel case and just written out normally with white space in between words. I think it would make more sense for them all to match.

## 💬 Description 

<img width="365" alt="Screenshot 2024-02-16 at 08 04 38" src="https://github.com/mi6/ic-ui-kit/assets/111882034/88b59830-4529-4804-a5f6-300d01abb869">

The image above shows the differences we have when naming the snapshots. We should decide how we want snapshots named and then go through and update snapshots to match that name style. 

We'll have to update them in the `compareSnapshot` line in the Cypress files, and then delete the outdated screenshots with the old name style.

## 💰 Use value 
It makes the code look more professional and less messy. 

## Additional Info

Agreed that this issue should encompass the work to ensure all components use the `setThresholdBasedOnEnv()` method described here: https://github.com/mi6/ic-ui-kit/issues/1755 and pointed to include this

**Comment by MI6-255** [comment]
@MI6-286, could you consider this as part of the testing standards?

**Comment by MI6-255** [comment]
@ad9242 to add to this issue

**Comment by ad9242** [comment]
Agreed that this issue should encompass the work to ensure all components use the `setThresholdBasedOnEnv()` method described here: https://github.com/mi6/ic-ui-kit/issues/1755

**Comment by ad9242** [comment]
May want to also consider the focus indicator work covered here: https://github.com/mi6/ic-ui-kit/issues/1463 as that will also require the baseline images to be updated
