### ISSUE TITLE
Checkbox - Missing properties 

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-ui-kit#1586]
## Summary 
Add appearance prop to checkbox component. 

## 💬 Description 
Add appearance property including options for 'Default', 'Light' and 'Dark'.

Check component to confirm which prop options are required. 

## 💰 User value 
Provides consistent functionality across all ICDS components.

## 📚 User Stories 
If relevant, describe the high-level functionality as user stories. 

*As an* ICDS user:  
*I need* 
*So that*  

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* 
*When*  
*Then* 

## ✏ Designs 
If there's a Figma design file (or other mock-up), include it here. 

## 🧾 Guidance 
If there's written guidance or documentation, include a link to it here.  

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by GCHQ-Developer-741** [comment]
No designs for this variant yet, or acceptance criteria, so is blocked until this is defined
