### ISSUE TITLE
Hero V2

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-ui-kit#159]
## Summary
The hero banner V2 adds full size image support and automatic switching of component contrast variants dependent on personality colour selection. 

## 💰 Use value
Foundational component required to provide ICDS users the tools to build rich applications. Hero banner provides key messaging on a homepage as well as slots for key call to actions. 

*📚  User Story* *📚*

*As an* ICDS user
*I need* a hero banner with the following additional elements:
* Full size right hand side image
*So that* I can have different stylistic options.

*As an* ICDS user
*I need* the slot components to automatically adjust their contrast variant according to the selected background personality colour
*So that*  it achieves correct contrast ratios.

📋  *Acceptance Criteria* 📋

*Given* that a user is implementing a hero component, 
*When* setting its interaction content. 
*Then* they should be able to specify any components in the interaction slot
(e.g can choose any number of buttons, or different types of input field, or a set of links)
*And* the selected components should automatically change to the correct contrast variant for the selected personality colour
(e.g Buttons should use the light variant on a dark background and the dark variant on a light background.)

*Given* that a user is implementing a hero component, 
*When* setting its right hand side content,
*Then* they should be able to set it as a 'full screen image'. 

✏️  *Designs*  ✏️

**Comment by ASM995** [comment]
Need to investigate further @DBD324

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
