### ISSUE TITLE
Stepper - Missing Properties 

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-ui-kit#1609]
## Summary 
Add size and appearance prop to stepper component.
## 💬 Description 
Add size property including options for 'Default' 'Small' and 'Large', where 'default' is the default.

Add appearance property including options for 'Default', 'Light' and 'Dark'.

Check component to confirm which prop options are required.

## 💰 User value 
Provides consistent functionality across all ICDS components. 

## 📚 User Stories 
If relevant, describe the high-level functionality as user stories. 

*As an* ICDS user:  
*I need* 
*So that*  

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* 
*When*  
*Then* 

## ✏ Designs 
If there's a Figma design file (or other mock-up), include it here. 

## 🧾 Guidance 
If there's written guidance or documentation, include a link to it here.  

## Additional info 
Tell us anything else useful to help us understand your suggestion.

**Comment by gd2910** [comment]
Design will have to take into consideration for `size` prop the two variants, i.e. three sizes for each variant?
There are no designs as yet for light/dark appearance.

**Comment by gd2910** [comment]
![image](https://github.com/mi6/ic-ui-kit/assets/122624946/00dbe028-dc5d-4eda-874c-0987376f59d0)
The appearance is changed through checking if the parent (ic-stepper) has the prop in the DOM, we may want to change this to a @Watch() to ensure the appearance can change post render.
