### ISSUE TITLE
[ic-hero] define max width for all breakpoints

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-ui-kit#168]
## Summary of the bug
Definition of max width for all breakpoints needs to be declared. Whilst developing hero v2 the following AC was identified as not working.

Review Hero V2 so that it respects the following parameters for max width of the content container:

- Extra large: Left hand content = 2/3 width, Right hand content =1/3 width.
- Large: Left hand content = 50%, Right hand content = 50%
- Medium: Left hand content = 50%, Right hand content = 50%
- Small: Left hand content = 100%. Right hand content = 100% stacked underneath
- Extra small: Left hand content = 100%. Right hand content = 100% stacked underneath

**Comment by ASM995** [comment]
Bug resolved.
