### ISSUE TITLE
[ic-toggle-button/ic-toggle-button-group] Icons are appearing smaller than expected when label is more than one line

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1680]
## Summary of the bug 
When toggle buttons are slotted into toggle button group with either iconPlacement left or right, the icons are shrinking when the label overflows onto more than one line. 

## 📸 Screenshots or code 
How we'd expect:
<img width="259" alt="Screenshot 2024-03-20 at 13 48 31" src="https://github.com/mi6/ic-ui-kit/assets/111882034/2b3bb489-7474-4ddd-9d0a-37c133833ccf">

Current icon behaviour: 
<img width="284" alt="Screenshot 2024-03-20 at 13 48 07" src="https://github.com/mi6/ic-ui-kit/assets/111882034/068f4a3b-e950-4c8a-9fc7-d776bcb85b9d">

## 🧐 Expected behaviour 
The icon should be the same size when the label overflows, or the size change shouldn't be drastically different

**Comment by MI6-255** [comment]
https://github.com/mi6/ic-ui-kit/issues/1812

**Comment by GCHQ-Developer-530** [comment]
Fixed in this PR: https://github.com/mi6/ic-ui-kit/pull/1933
