### ISSUE TITLE
Migrate multi-select tests over to Cypress

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#1700]
## Summary 
Migrate multi-select tests over to Cypress

## 💬 Description 
As per #1166, tests for the multi-select component need to be migrated over to Cypress. This involves migrating over every e2e test we currently have, as well as accessibility and visual testing. This also involves removing the old framework's code, so two versions of the same tests do not run. 

## 💰 Use value 
Improve our testing toolset to allow us to test in more states and deliver a higher quality product.

**Comment by ad9242** [comment]
Following work done in #1277, tests were added for the functionality added under that ticket. There were issues with the popup menu closing when items were clicked. This appeared to be a Cypress only issue as did not happen anywhere else the component was used (eg storybook\stackblitz).

May want to consider re-looking into trying to resolve this issue when implementing these tests

**Comment by ad9242** [comment]
complete before #2108
