### ISSUE TITLE
Selected state of ic-radio-option off-centre at different zoom levels in browser

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-ui-kit#1721]
## Summary of the bug 
When changing zoom level the blue dot signifying a radios selected state can move off-centre at certain levels (90%, 110% etc for myself)

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to page: ['Radio page' ](https://design.sis.gov.uk/components/radio)
2. Change zoom level of window and keep an eye on the selected radio option
3. See the error 

## 📸 Screenshots or code 
Snippet at 110%
![image](https://github.com/mi6/ic-ui-kit/assets/122624946/8a426691-6336-433c-8a76-96feafa886c6)

## 🖥 📱 Device 
- Type: Desktop
- Device: Windows
- Browser version: Chrome

## 🧐 Expected behaviour 
The selected state should not skew

**Comment by GCHQ-Developer-741** [comment]
Unable to recreate. May have been fixed in another issue.
