### ISSUE TITLE
improve contribution guidance to make forking\branching clearer

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1724]
## What component is this related to? 
Contribution guidance

## Why do we need it? 
A couple of issues recently where better guidance would have helped:

1) It is not explicity stated that you need to create a branch off `develop` (only implied from the wording of setting `develop` to be the target

2) by default GH seems to only copy the main branch when creating a fork, so contributers need to ensure the "copy main branch only" setting is unchecked when forking

## Related open issues  
[Link to other GitHub issues]

**Comment by MI6-255** [comment]
Will merge this into the contribution issue

**Comment by MI6-255** [comment]
Keep it short and just add to existing guidance
