### ISSUE TITLE
SSL error on the main site

### ISSUE THREAD

**Issue by JoeAtkins95** [mi6/ic-ui-kit#1733]
## Summary of the bug 
Hello, I'm sure you're aware of this but the main site to used to display the UI library is down with an SSL certificate error.

## 🪜 How to reproduce 
1. Go to the main page: https://design.sis.gov.uk/

## 📸 Screenshots
![image](https://github.com/mi6/ic-ui-kit/assets/132467456/dd800f03-5dcf-49b0-91f8-c1565506504d)

## 🖥 📱 Device 
Any device I've tried to access the site on has failed

**Comment by MI6-94** [comment]
Thanks for raising this issue - it's now been rectified.
