### ISSUE TITLE
Popover menu accessibility improvements: Open and close announcements

### ISSUE THREAD

**Issue by GCHQ-Developer-539** [mi6/ic-ui-kit#1736]
## Summary 
The [popover menu](https://mi6.github.io/ic-ui-kit/branches/develop/web-components/iframe.html?args=&id=web-components-popover-menu--default-story&viewMode=story) does not annouce when it closes, nor does it announce 'close' as the action when hovering the button when the menu is open. 

## 💬 Description 

- [ ] Change the VO command of the popover menu button to "show/hide popover menu"
- [ ] 

## 💰 Use value 
When a screenreader use triggers the actions within a popover menu to close the popover, or when the user hovers the popover menu button, they will be informed of the action to help understand the current state of the screen.

**Comment by ad9242** [comment]
not sure this is an issue with the popover menu. more a case of adding appropriate information to the element that opens the menu (in the examples)

**Comment by MI6-255** [comment]
If make a change to the Storybook, change the website examples
