### ISSUE TITLE
[ic-radio-option\ic-radio-group] - Cypress Migration

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1794]
## Summary 
Generate E2E Cypress tests and snapshot images, replacing and removing the older tests, adding additional tests where needed.

Tests have been added for fixes added in #1749, but no other tests currently exist

**Comment by MI6-255** [comment]
May be in progress, review if to close later

**Comment by MI6-286** [comment]
Visual regression tests added as part of #1891. Full migration of E2E tests still needed.

**Comment by MI6-255** [comment]
Awaiting @ad9242 to make a wider ticket and close this
