### ISSUE TITLE
Pagination component

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#183]
## Summary
Component used to show page navigation through large lists of data items or pages. 

## 💰 User value
Foundation component that allows easy navigation through multiple pages and large lists of data. 

## 📚 User Stories
As an ICDS user
I need a pagination component
So that I can sort large amounts of data into different pages and allow navigation between them.

As an ICDS user
I need to see how many pages there are
So that I know how much content is available.

As an ICDS user
I need to see how many results/records/items there are
So that I know how much content is available.

As an ICDS user
I need to know what the current page is
So that I know where I am. 

As an ICDS user
I need to be able to navigate to any page displayed in the page order
So that I can easily navigate without just going forward or back

As an ICDS user
I need to be able to easily move to the next and previous page
So that I can move through content linearly. 

As an ICDS user
I need to be able to easily move to the first and last page
So that I can move through content quickly. 

As an ICDS user
I need to be able to change how many results/records/items per page are displayed
So that I can view more per page. 

A an ICDS user
I need the pagination to be disabled
So that I can stop users interacting with it at specific times. (e.g whilst load is occuring)

As an ICDS user 
I need any clickable elements to have all interaction states (default, hover, pressed, disabled, active)
So that I get feedback when interacting with the component. 

As an ICDS user
I need the component to be responsive
So that it is displayed and operable on all screen sizes. 

As an ICDS user
I need the pagination component to be a navigation element 
so that I know it's there and can access it quickly. 

As an ICDS user
I need to be able to navigate by keyboard
So that I don't have to use a mouse. 

As an ICDS user
I need each navigation button to read out the action in full (e.g "Go to page 4")
So that I understand what each item will do. 

## 📝 Acceptance Criteria 
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

*Given*
*When* 
*Then*

### Simple pagination
**Icon buttons**
Given that a simple pagination is being implemented
When the first page is the current page, 
Then the previous and first icon buttons should be disabled as user is already on first page. 

Given that a simple pagination is being implemented
When the last page is the current page, 
Then the next and last icon buttons should be disabled as user is already on lastpage.

Given that a simple pagination is being implemented
When the first page button is clicked
Then the first page should be selected and the pagination updated to show that page selected. 

Given that a simple pagination is being implemented
When the last page button is clicked
Then the last page should be selected and the pagination updated to show that page selected. 

Given that a simple pagination is being implemented
When the next page button is clicked
Then the next page should be selected and the pagination updated to show that page selected. 

Given that a simple pagination is being implemented
When the previous page button is clicked
Then the previous page should be selected and the pagination updated to show that page selected. 

**Appearance**
Given that a simple pagination is being implemented
When the appearance property is set 
Then the following appearance types should be used:
- appearance: Default - default styling
- appearance: Light- Light styling
- appearance: Dark - Dark styling

**Label**
Given that a simple pagination is being implemented
When the current page label override is not set
Then it should default to read 'Page X' where X is the currently selected page number. 

Given that a simple pagination is being implemented,
When the current page label override is set
Then this should appear in the text label. 
(e.g user could set it to be just 'X' where X is current page)

Given that a simple pagination is being implemented
When setting the current page label aria label
Then the option to override the default (the visible label) should be possible so that more detail can be added for screen readers. 
(e.g user can set aria label to read 'Page 1 of 10' where the visible label just shows 'Page 1')

Given that a simple pagination is being implemented
When setting the 'displayCurrentPage' to false (default true)
Then the current page should not be displayed, and only the icon buttons are displayed. 

### Complex pagination
**Icon buttons**
Given that a complex pagination is being implemented,
When setting the 'showFirstAndLastButtons' prop is set to false (the default)
Then the first and last icon buttons should not be displayed next to the next and previous buttons. 

Given that a complex pagination is being implemented,
When setting the 'showFirstAndLastButtons' prop is set to true
Then the first and last icon buttons should be displayed in addition to the next and previous buttons. 

Given that a complex pagination is being implemented
When the first page is the current page, 
Then the previous and first icon buttons should be disabled as user is already on first page. 

Given that a complex pagination is being implemented
When the last page is the current page, 
Then the next and last icon buttons should be disabled as user is already on lastpage.

Given that a complex pagination is being implemented
When the first page button is clicked
Then the first page should be selected and the pagination updated to show that page selected. 

Given that a complex pagination is being implemented
When the last page button is clicked
Then the last page should be selected and the pagination updated to show that page selected. 

Given that a complex pagination is being implemented
When the next page button is clicked
Then the next page should be selected and the pagination updated to show that page selected. 

Given that a complex pagination is being implemented
When the previous page button is clicked
Then the previous page should be selected and the pagination updated to show that page selected. 

**Pagination items**
Given that a complex pagination is being implemented, 
When setting the 'adjacentItems' prop, 
Then the following should occur for each setting:
- adjacentItems: 1 (default) - One page is displayed either side of the current page. 
- adjacentItems: 2 - Two pages are displayed either side of the current page.  
- adjacentItems: 0 - No pages are displayed either side of the current page. 

Given that a complex pagination is being implemented, 
When setting the 'boundaryItems' prop, 
Then the following should occur for each setting:
- boundaryItems: 1 (default) - The first and last pagination items are always displayed
- boundaryItems: 2 - The first, second, penultimate and last items are always displayed
- boundaryItems: 0 - The first and last pagination items are not displayed when current page is mid-range. 

(see Figma component for detail on this)

Given that a user is interacting with a pagination items
When hovering, pressing or focussing
Then the following should be true:
- :hover -  hover state displayed
- :active - pressed state displayed
- :focus - focus state displayed (outer outline focus style)

Given that a complex pagination exists
When the current page is in the middle of the range
Then pagination items next to the adjacent items should be replaced with a non-interactive '...' state
And this should be equal width to the other pagination items. 
(see Figma component for detailed view). 

**Appearance**
Given that a complex pagination is being implemented
When the appearance property is set 
Then the following appearance types should be used:
- appearance: Default - default styling
- appearance: Light- Light styling
- appearance: Dark - Dark styling
And the pagination items should use the according appearance variant. 

**Label**
Given that a complex pagination is being implemented
When the pagination items are created 
Then their aria-label can be set to give more information that their visible label. 
And by default the aria label should read 'Page X' where X is the page number. 
(e.g visible label just shows '1', '2', '3'. Aria-label by default should read 'Page 1' but can be overridden as well.)

**Responsiveness**
Given that a pagination exists with a large number of pages
When the component can't fit horizontally within its container
Then the items that cannot fit should wrap on a new line. 

### Accessibility
Given that a pagination is used on a page
When a page is selected
Then that pagination item should use aria-current to indicate it is the current page and its aria-label should update to include reference to 'current page'. 

Given that any type of pagination is being used
When interacting with the next, prev, first and last buttons with a SR
Then the following should be announced:
- first button: "Go to first page".
- prev button: "Go to previous page".
- next button: "Go to next page".
- last button: "Go to last page". 

Given that a complex pagination is being used
When interacting with the pagination items using a SR
Then they should be announced 'Go to page X' where X is the number of the page. 

## ✏ Designs

Please see branch: "[New] 183-Pagination".

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by ASM995** [comment]
This ticket has been split into two sub-tasks:

- [ ] #481 
- [ ] #459 
- [ ] #460

**Comment by DBD324** [comment]
#481

**Comment by DBD324** [comment]
This ticket is no longer required as has been split into component parts:
#481 
#459 
#460 

Closing ticket as now duplicated.
