### ISSUE TITLE
Back To Top: Virtual Cursor does not move

### ISSUE THREAD

**Issue by GCHQ-Developer-299** [mi6/ic-ui-kit#1846]
## Summary of the bug 
Similar to an issue we had with [Skip to Content in the design system](https://github.com/mi6/ic-design-system/pull/821) - the IcBackToTop component does not move the virtual cursor for screen reader users. 

Requirements for this ticket:
- [ ] Fix BackToTop so that when it is clicked, the screen reader virtual cursor is moved to the `target` 
- [ ] Improve Storybook "Page Example" for Back To Top, adding focusable buttons above and below the target element on the page, making it more clear that focus has moved and we aren't just looping around the page.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to [Back to top 'Page Example' storybook](https://rhcz0lsp-6006.uks1.devtunnels.ms/iframe.html?id=web-components-back-to-top--page-example&viewMode=story)
2. Activate Voiceover and navigate down the page using the cursor ( Ctrl Alt RightArrow )
3. Navigate onto the Back to top button and activate it. The page will scroll up to top.
4. Use the voiceover cursor to move to the next element, and you'll find that it goes to the Footer, which is not good. 

## 🖥 📱 Device 
- Type: Desktop
- Device: MacBook with Voiceover

## 🧐 Expected behaviour 
Expect the back to top button to move the virtual cursor, so moving the cursor back or forward after clicking it should read elements adjacent to the 'target' element

## Additional info 
This will enable the BackToTop component to pass #1817

**Comment by MI6-255** [comment]
Use the fix from Skip to content
