### ISSUE TITLE
[ic-accordion] accordion sizes don't match Figma designs

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1856]
## Summary of the bug 
In the Figma designs, the different size variations have an impact on the width of the accordion as well. But in the implementation, all accordions are full width and only the height changes. 

## 📸 Screenshots or code 
Figma:
<img width="321" alt="Screenshot 2024-05-09 at 12 44 24" src="https://github.com/mi6/ic-ui-kit/assets/111882034/8ecf9aad-05aa-4094-9f87-923a2d516c06">
Implementation:
<img width="1210" alt="Screenshot 2024-05-09 at 12 44 56" src="https://github.com/mi6/ic-ui-kit/assets/111882034/11d76a4b-d952-4e77-90ef-2cd9c53c05c9">

## 🧐 Expected behaviour 
The accordion sizes should match figma. 

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* a accordion exists
*When*  it is small
*Then* it should have a 300px width

*Given* a accordion exists
*When*  it is default
*Then* it should have a 600px width

*Given* a accordion exists
*When*  it is large
*Then* it should have a 800px width

## Additional info 
Current accordions could be a full width size variant.

**Comment by MI6-255** [comment]
Design brought this up to ask why it was moved to design, which I was unsure why. Therefore, I have moved it back to refinement so we can discuss at refinement on if it needs design

**Comment by MI6-255** [comment]
Design to update all the Figma widths to the same size, as we will be following the dev implementation

**Comment by GCHQ-Developer-094** [comment]
Changes made in Figma and now merged.
