### ISSUE TITLE
Capitalisation of classification banners

### ISSUE THREAD

**Issue by tomyems** [mi6/ic-ui-kit#186]
## Summary

The classification banner currently displays text in all caps. What's the evidence behind that design choice?

## 💬 Description

For example: 'UK OFFICIAL', 'UK OFFICIAL SENSITIVE'. I wondered why you chose that design choice over 'UK Official'? Do you have evidence that you can share to support that the message is more clearly communicated in all caps?

## 💰 Use value

All caps is generally regarded as being harder for people to read, in particular for people with dyslexia. The GOV.UK style guide (https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#security-classifications) does not use all caps for security classifications.

## Additional info

I realise that this has been developed to be read out correctly by screen readers.

**Comment by DBD324** [comment]
Hi, thank you for your contribution. We have made the decision to use all caps for the classification banner text for a couple of reasons.

Firstly, our internal style guidance on the subject is to use all-caps for these four specific terms to provide emphasis on the terms and make them recognizable at a glance. The importance of this information is high and so the capitalization helps to make the terms stand out on the page. Our guidance reads "When working with documents, classifications must be in CAPITALS at the top or bottom of each page."

Secondly, while it is true that capitalization has been observed to make an impact on readability, slowing it down 13-20% (Breland & Breland, 1944, Legibility of newspaper headlines printed in capitals and lower case), this effect can in fact be beneficial when requiring a user to slow down and take in the importance of the messaging. 

The impact of readability is also greatest when trying to take in large bodies of text, whereas on standalone terms it is less impactful and actually provides a good contrast with other text on a page. 

Also, as these terms are repeated frequently, and backed up with additional visual cue of the background colour-coding, the terms can be quickly remembered without the need to re-read again. 

There are some useful guidelines about how to effectively use capitalization in this article ([https://uxplanet.org/why-letter-casing-is-important-to-consider-during-design-decisions-50402acd0a4e](https://uxplanet.org/why-letter-casing-is-important-to-consider-during-design-decisions-50402acd0a4e)), whilst minimizing the impact on readability. 

We do specify in our content style that we do not use capitalization as it impacts readability, but this needs further elaboration to include the edge cases where it can be a useful tool, where the requirement on emphasis is greater than that of readability. The two areas we currently use it are in the classification banner and on destructive action buttons. We will raise a research ticket to address this in full and update our content style guidance accordingly. 

Thank you again for your contribution, we appreciate the input and will take this into consideration when addressing similar issues in the future.
