### ISSUE TITLE
ic-text-field icon disappears when validationStatus is applied

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-ui-kit#1867]
## Summary of the bug 
When a `validationStatus` is applied to an `ic-text-field` that has a `SlottedSVG` in the icon slot, the icon will disappear and the span surrounding it will be removed from the DOM.

This section of the component is controlled by a private value called `showLeftIcon`, which is only ever set to `false` when the text-field is `disabled` and not `readonly`. Since neither of these things happen, and the icon displays as normal initially, this will require some investigation to determine why this section of the code is being removed.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Copy the code below into a test app.
2. Run the app.
3. Enter any value into the ic-text-field
4. See the error 

## 📸 Screenshots or code 
```jsx
import { useState } from "react";
import { IcTextField, SlottedSVG } from "@ukic/react";
import { mdiMagnify } from "@mdi/js";

export const IconTest = () => {
  const [value, setValue] = useState("");
  const handleChange = (event) => {
    setValue(event.detail.value);
  }
  return (
    <IcTextField
      hideLabel
      label="Search"
      validationStatus={value.length > 0 ? "error" : ""}
      onIcChange={handleChange}
      value={value}
    >
      <SlottedSVG
        slot="icon"
        path={mdiMagnify}
        height="24px"
        viewBox="0 0 24 24"
        width="24px"
      />
    </IcTextField>
  );
};

export default IconTest;
```
![Screenshot from 2024-05-14 17-07-26](https://github.com/mi6/ic-ui-kit/assets/117368893/2b8f44de-43bf-4c9a-8ff7-19bfce4eeea0)
![Screenshot from 2024-05-14 17-06-57](https://github.com/mi6/ic-ui-kit/assets/117368893/ef27785e-6a0f-4bb0-9561-cfbdf9afffcc)
![Screenshot from 2024-05-14 17-17-27](https://github.com/mi6/ic-ui-kit/assets/117368893/8a56774b-04fc-4119-9dbb-c837c3e99feb)

## 🧐 Expected behaviour 
The icon should remain visible and in the correct place in the DOM, regardless of whether any validationStatus has been applied

## 📝 Acceptance Criteria  

*Given* that an ic-text-field exists with an icon
*When* a validationStatus is applied to the text-field
*Then* the icon slotted into the icon slot should remain visible.

## Additional info 
As shown in the 3rd screenshot, the DOM actually changes when the icon disappears, moving the span which wraps the slot out of its intended place in the DOM, and applying a hidden attribute. This may be the cause of the disappearing icon, however it is unclear where in our code this error takes place, making it difficult to debug. Something to consider when looking into this.

**Comment by ad9242** [comment]
Have been able to recreate this without the validation status. it seems to be an issue using a SlottedSVG for the icon. This could be related to the way the slot is checked for content. For example, in ic-textfield, the slot is only checked when the component is instantiated (before load\render) :
```
export class TextField {
  private inheritedAttributes: { [k: string]: string } = {};
  private inputEl: HTMLInputElement | HTMLTextAreaElement;
  private showLeftIcon: boolean = this.hasLeftIconSlot();
...
```

One thing to consider is how this would behave if you initially did not have an icon in the slot but you subsequently add one. At present, i don't think this would work
