### ISSUE TITLE
[ic-footer-link] in Safari footer links don't get focus

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1869]
## Summary of the bug 
Footer links don't get focus by tabbing or by hovering.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to any footer example with links on Safari
2. Tab or hover
3. See the error 

## 🧐 Expected behaviour 
Footer links should get the same offset underline that regular links do.

**Comment by gd2910** [comment]
Linked to [1910](https://github.com/mi6/ic-ui-kit/issues/1910)
