### ISSUE TITLE
[IcTextField] - icon not rendered if slot initially empty

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#1876]
## Summary of the bug 
If a textfield initially has no icon, but one is subsequently added, the icon is not visible

## 🪜 How to reproduce 
With the following [stackblitz example](https://stackblitz.com/edit/stackblitz-starters-myfezh?file=src%2FApp.tsx)

When clicking the button, the visibility of the icon should change
It does work if the icon is initially visible

## 🧐 Expected behaviour 
The icon should be visible when the slot has content

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* an icon slot in a textfield is empty
*When*  adding an icon to the slot
*Then* the icon should be visible

*Given* an icon is visible in a textfield 
*When*  removing the slot content 
*Then* the icon should not be visible

## Additional info 
This is closely linked to #1867

**Comment by MI6-255** [comment]
May have been fixed by @GCHQ-Developer-741

**Comment by ad9242** [comment]
fixed by #1992
