### ISSUE TITLE
[ic-hero] secondary slot and background image clash

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1883]
## Summary of the bug 
When a background image is used, anything can still be put in the secondary slot. 

Need to check with design to decide what should take precedence 
- should slot content show and no background image?
- or background image and no slot content? 
- is it okay as is and we just need to add guidance?

## 📸 Screenshots or code 

<img width="1235" alt="Screenshot 2024-05-16 at 11 32 49" src="https://github.com/mi6/ic-ui-kit/assets/111882034/82fcf432-8505-431d-bc4d-a80b9ad09716">
<img width="1238" alt="Screenshot 2024-05-16 at 11 29 41" src="https://github.com/mi6/ic-ui-kit/assets/111882034/0912542f-e6f4-404c-a5fa-655d7678a298">

## 🧐 Expected behaviour 
There should be no clash in content.

**Comment by MI6-255** [comment]
Working as intended
