### ISSUE TITLE
[ic-search-bar] props not working as expected

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1911]
## Summary of the bug 
When checking search bar against the PR checklist, I noticed that spell check and auto focus didn't work as expected. 

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. On the search bar playground turn on spellcheck
2. Try typing something wrong - see that there are no red lines
3. Turn on autofocus
4. See that focus isn't given to the component

## 📸 Screenshots or code 
Example of the html input with spell check
<img width="225" alt="Screenshot 2024-05-23 at 14 52 30" src="https://github.com/mi6/ic-ui-kit/assets/111882034/87342f24-54fb-462d-9ca6-56423939cfc2">

Search bar with spell check
<img width="362" alt="Screenshot 2024-05-23 at 14 52 35" src="https://github.com/mi6/ic-ui-kit/assets/111882034/9a1d1e8f-3a29-4910-b1db-ef6994dd2ca7">

## 🧐 Expected behaviour 
The props should work where red lines appear for spell check and the component is focused on page load for autofocus.

## Additional info 
We have a focusOnLoad prop that works correctly and focuses the component on load, but autofocus doesn't work (do we just need to do the same thing for both of these props?)

**Comment by MI6-255** [comment]
Is spell check on Text field working too?

**Comment by MI6-255** [comment]
Is this a quirk of Storybook or the specific browser, explore if this is the case in this ticket

**Comment by MI6-255** [comment]
Works in stackblitz, not in Storybook

**Comment by MI6-255** [comment]
We've got a Cypress test for spellcheck, but not autofocus

**Comment by ad9242** [comment]
spell check works. would not expect autofocus to work in storybook as it is only applied on page load. closing
