### ISSUE TITLE
[ic-tooltip] inconsistent behaviour when clicking on a tooltip target

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1915]
## Summary of the bug 
When hovering over a tooltip target, or when disable hover is set, tooltips work as expected. But when I click on a tooltip target, the tooltip seems to re-evaluate it's positioning and it goes wrong. This is also happening all the time in high contrast mode.

Not sure if it's a coincidence (I imagine it's not), but it's only ever the *-end placements that are breaking.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Hover over a button with a tooltip placement *-end in our storybook examples
2. See it appears correctly
3. Click on the button
4. See the tooltip move and now when you hover again it's stuck in this state

## 📸 Screenshots or code 

https://github.com/mi6/ic-ui-kit/assets/111882034/6623c1c4-95c9-4efe-af7b-ec1f00bc74a7

<img width="346" alt="Screenshot 2024-05-23 at 14 15 46" src="https://github.com/mi6/ic-ui-kit/assets/111882034/6b704162-6c58-42bb-96f2-85ba31c45232">

<img width="409" alt="Screenshot 2024-05-23 at 14 15 10" src="https://github.com/mi6/ic-ui-kit/assets/111882034/1cdb15cb-f03e-4d19-ab1a-2fcc1a41aa59">

<img width="522" alt="Screenshot 2024-05-23 at 14 15 26" src="https://github.com/mi6/ic-ui-kit/assets/111882034/772a6584-8e52-4f64-9567-c9c7f99cec67">

<img width="385" alt="Screenshot 2024-05-23 at 14 15 38" src="https://github.com/mi6/ic-ui-kit/assets/111882034/b5617aaf-33d4-4ea3-9daa-8e42c1b91826">

## 🧐 Expected behaviour 
Tooltips should display in the correct place

**Comment by MI6-255** [comment]
If it's just Storybook, may de-priortise
