### ISSUE TITLE
[ic-side-navigation] Issues when text resized to 200%

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#1923]
## Summary of the bug 
When text is resized to 200%, side nav presents a few issues:

- navigation items icons don’t resize so look uncentred
- focus doesn’t stretch to the width of the side nav
- on mobile view, the app name is cut off and the navigation items with long labels are cut off

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Resize text to 200% or extra large etc.
2. View any side nav example
3. See the error 

## 📸 Screenshots or code 
Icons not resized or vertically centred -
<img width="188" alt="Screenshot 2024-05-24 at 09 53 52" src="https://github.com/mi6/ic-ui-kit/assets/111882034/de2d18c9-6815-4cc0-8ddd-0e418c3bd4c0">

<img width="91" alt="Screenshot 2024-05-24 at 09 54 39" src="https://github.com/mi6/ic-ui-kit/assets/111882034/3cd32e53-2339-427f-8bcd-506930020d18">

<img width="481" alt="Screenshot 2024-05-24 at 09 54 52" src="https://github.com/mi6/ic-ui-kit/assets/111882034/37a76df9-ea66-44a3-af30-0dc315e41409">

Focus doesn't grow to the width of the side nav - 
<img width="480" alt="Screenshot 2024-05-24 at 09 55 28" src="https://github.com/mi6/ic-ui-kit/assets/111882034/2ee9151f-551c-4d8b-87c6-c73d853d744f">

Mobile, app title cut off and long labels -

<img width="324" alt="Screenshot 2024-05-24 at 09 56 12" src="https://github.com/mi6/ic-ui-kit/assets/111882034/893cd406-b15a-411a-b5ab-5fe73ce13579">

## 🧐 Expected behaviour 
Should work the same as when text is default size

**Comment by MI6-255** [comment]
Main focus is the app title being cut off, if the other fixes are bigger, we can break them out and re-priortise

**Comment by MI6-255** [comment]
May have had a similar fix in Tab Groups

**Comment by MI6-255** [comment]
Intended behaviour for the title is ellipsis
