### ISSUE TITLE
Fix naming of Accordion functions

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-ui-kit#1924]
## Summary of the bug 

There are functions which have a spelling mistake in the component accordion.
For instance:

- SlottedContentDialogAccordian,  
- SlottedContentDialogAccordianGroup, 
- SlottedContentDialogAccordianGroupSingleExpansion,

These need to be fixed, however this may not be as simple as it seems due to breakage of tests and other files. This may impact other components too.

**Comment by MI6-255** [comment]
Done
