### ISSUE TITLE
[CONTRIBUTING.md]: Add CI visual regression steps to markdown file.

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#1941]
## What component is this related to? 
This relates to the visual regression images and how to add them using the CI.

## Why do we need it? 
This will expose the our best practice when dealing with visual regression tests to external contributors.

## Related open issues  
N/A

**Comment by MI6-255** [comment]
Test this as an external contributor on how you enable actions on a fork

**Comment by MI6-255** [comment]
Does the update workflow use tokens and if so it will not work
