### ISSUE TITLE
Create a Test app in React

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#1971]
## Summary
A test app should be created so that integration/end-to-end testing can be carried out to allow components to move out of BETA.

## 💬 Description 
Test app to be created in React and tested with React Testing Library and end-to-end Cypress tests. Steps would be to decide on the user stories and hence the components to be included, design the app, develop the app and create end-to-end Cypress tests.

## 💰 User value 
Testing of integrated components within a full app would potentially expose issues that ICDS would not see with individual component testing, meaning these issues can be fixed.

**Comment by MI6-255** [comment]
Developer design in Figma then develop it, with design help in design review

**Comment by MI6-255** [comment]
To cover: design, develop and testing

**Comment by MI6-255** [comment]
Consider if we add this to the site

**Comment by MI6-255** [comment]
Cap: 10 points
