### ISSUE TITLE
Light and dark ic-links don't show the correct colours in their visited states

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#2009]
## Summary of the bug 
The light and dark ic-links remain white and black when they are visited, which does not match the Figma designs.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Go to the [light and dark links example](https://design.sis.gov.uk/components/link/code#light-and-dark) on the website.
2. See that they are white and black.

It looks like there is some overriding of CSS going on, looking at the DevTools. (in dev tools, select the <a> inside IcLink and toggle :visited in the CSS panel. They don't change colour)

## 🧐 Expected behaviour 
The links should display as being visited, i.e. with different colours; on Figma, the light visited link is grey and the dark visited link is purple. 

## Additional info 
To prevent things from getting confusing, I think it's best CSS variables are created for the light and dark links. E.g. `--ic-hyperlink-light` and `--ic-hyperlink-dark` for the normal states, and then `--ic-hyperlink-light-visited` and `--ic-hyperlink-dark-visited`.

**Note:** You will see that there are some hyperlink-related colour variables that are not being used. I have created [a separate ticket](https://github.com/mi6/ic-ui-kit/issues/2010) to remove these; removing them will be a breaking change.

**Comment by GCHQ-Developer-094** [comment]
Ticket will be fixed as part of larger dark mode work.

**Comment by GCHQ-Developer-530** [comment]
Closing as fixed by dark mode work #1214
