### ISSUE TITLE
Remove unused link CSS variables

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#2010]
## Summary
**Note:** This ticket should be completed after the [light and dark link updates](https://github.com/mi6/ic-ui-kit/issues/2009).

There are some CSS variables relating to the ic-link which are no longer being used.

## 💬 Description 
The following hyperlink CSS variables are no longer used in any component:
`--ic-hyperlink-hover`
`--ic-hyperlink-contrast`
`--ic-hyperlink-contrast-hover`

At time of writing, the `--ic-hyperlink-contrast-visited` variable [is being used in the ic-link component](https://github.com/mi6/ic-ui-kit/blob/d514f0b7ea02cad6e1f5f13aba34b7e8a3c162dd/packages/web-components/src/components/ic-link/ic-link.css#L86) but the [light and dark link updates ticket](https://github.com/mi6/ic-ui-kit/issues/2009) removes that use, meaning that this variable can also be removed as part of this ticket.

## 💰 Use value 
These variables are not being used so there is no need to keep them, and keeping them may cause confusion for customers.

## Additional info 
This is a breaking change because some teams / projects may be using the CSS colour variables.

**Comment by GCHQ-Developer-847** [comment]
While triaging this ticket, we were wondering whether it would actually be a breaking change... 

I think it would be because there is always the possibility someone might be using any of the variables in `variables.css` as they may come across it and think it an appropriate colour to use for a certain use case. And with these link colours ^ , they may not realise that we don't actually use them in the ICDS components any more / at all.

I do actually remember seeing one team use the hover link colour which is why I must have marked this ticket as a breaking change! So yep, this change needs to be added to the v3 branch.

**Comment by MI6-255** [comment]
Do as part of: https://github.com/mi6/ic-ui-kit/issues/1214

Points removed from this ticket, was marked as 0.5

**Comment by GCHQ-Developer-741** [comment]
Done in #1214
