### ISSUE TITLE
`icon` variant does not sit above footer

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#2026]
## Summary of the bug 
When displaying a back to top with `variant`=`icon`, the element does not remain fixed in position when the footer scrolls into view:

![image](https://github.com/mi6/ic-ui-kit/assets/116102637/6dcf5aca-750e-4fba-a460-e62268e4c9cc)

the default variant does remain fixed:
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/3ea8f616-9e53-4b49-bd3d-b94c16e49b2d)

## 🧐 Expected behaviour 
The button should not overlap the footer

## 📝 Acceptance Criteria  

*Given* an icon variant back to top exists on a page
*When*  the page footer scrolls into view
*Then* the back to top button should not overlap the footer

## Additional info 
This may be due to the tooltip on the button

**Comment by evenstensberg** [comment]
Can I fix this?

If allowed:

Do I need a reproduction repo to mimic this bug? I'm running storybook locally and have a navigated to "back-to-top" component, but I don't have reproduction steps to follow
