### ISSUE TITLE
High contrast cypress tests

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#2057]
## Summary 
At the moment, the following components have high contrast cypress tests:

- Page header
- Radio
- Search bar
- Stepper
- Status tag
- Switch
- Tabs
- Text field
- Toggle button group
- Tooltip
- Typography

## 💬 Description 
The rest of the components need high contrast mode adding into the cypress tests. 

Should be as simple as adding a new describe block with 

```
before(() => {
    cy.enableForcedColors();
  });

  after(() => {
    cy.disableForcedColors();
  });
```
## 💰 Use value 
Keeps all tests consistent and makes us more confident in our components in high contrast mode.

**Comment by MI6-255** [comment]
Make sure to test the focus state
