### ISSUE TITLE
Implement to the v3 branching strategy

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#2058]
## Summary 
Implement to the v3 branching strategy for both ui-kit and design-system

## 💬 Description 
The general gist will be to follow our existing branching strategy, with it working as following on both ic-ui-kit and ic-design-system:

1. `main` represents the stable version 2.
2. Usual bug fixes/small improvements are to be committed on a `feature` branch, into `develop`, which eventually goes into `main` as normal.
3. A new `release/v3.0.0` branch to be created to host all version 3 additions.
4. Any specific changes specific to version 3 to be branched off `release/v3.0.0` and merged into that branch, with all the usual PR checks we do, as if it was going into `develop`.
5. GitHub Action to be developed which is automatically triggered when changes to `develop` are made, the workflow runs to open a PR from `develop` into `release/v3.0.0`. (Consider here if we can just have it automatically merge if there are no merge conflicts, to reduce the burden on us).
6. When implementing this, considerations will need to be factored in for when the v2 package is updated in package.json, but that update should not downgrade the v3 package on the v3 branch.
7. As part of the release process, we should update the instructions to merge `main` back into `release/v3.0.0` as well as `develop`.
8. In terms of what work will belong where, any work on the v3 roadmap will go into v3 only. Any bug fixes or anything else will go to v2 and v3 (through the develop automation).

-

## 💰 Use value 
Allow us to begin work on v3.

**Comment by MI6-255** [comment]
Opened by @MI6-255
