### ISSUE TITLE
Align size variants for components

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#2060]
## Summary of the bug 
Align all components with size prop to have small, medium and large options. 

At the moment it's small, default and large but we've agreed to a rename for V3. Also some components don't have either small or large variants.

This needs to go through design to ensure every component has all size variants and ensure that all mentions of "default" are updated to "medium".

A list of components currently using IcSizes or IcSizesNoLarge -

Accordion
Accordion-Group
Badge
Button
Checkbox
Checkbox-Group
Chip
Data Entity
Data Row
Empty State
Hero
Input Component Container
Menu
Page Header
Radio Group
Search Bar
Select
Status Tag
Switch
Text Field
Toggle Button
Toggle Button Group

**Comment by MI6-255** [comment]
https://github.com/mi6/ic-ui-kit/issues/2072

**Comment by GCHQ-Developer-094** [comment]
Deprecated by above 2072 work.
