### ISSUE TITLE
[ic-theme] Add mechanism for setting global dark mode theme 

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#2061]
## Summary 
Implement a mode or color prop to theme so that users can set dark mode, which subsequently updates every component to use the correct option for the appearance prop.

## 💬 Description 
Would need a function to get all components, update appearance to dark or light depending on the mode.

Would also need functions within some components for slotted content and ensuring the appearance prop on those are updated as well.

If the appearance prop is specifically set on a component then that should take precedence over the theme appearance.

Build into theme the option to either match system preferences for dark mode, force light, or force dark.

## 💰 Use value 
Enables a simple dark mode for users.

**Comment by MI6-255** [comment]
Consider for Page Header how the inverse colour will be needed

**Comment by MI6-255** [comment]
Marked as duplicate: [#1214](https://github.com/mi6/ic-ui-kit/issues/1214)
