### ISSUE TITLE
Explore a data table theme for a 3rd party library

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#2062]
## Summary 
Explore a data table theme for a 3rd party library

## 💬 Description 
Explore which 3rd party library we could use that is free, accessible, teams would be happy to use and offers all features 

Decide how we'll then then deal with data table features requests going forward and if we'd support them 

## 💰 User value 
Be able to support all features needed from teams of a data table.

**Comment by MI6-255** [comment]
Timebox 3 days

**Comment by MI6-255** [comment]
Consider funding

**Comment by MI6-255** [comment]
Compare against all the data table functionality from Figma

**Comment by GCHQ-Developer-847** [comment]
Research and findings have been written up on a page in the internal knowledge base.
