### ISSUE TITLE
Sizing consistency across component library

### ISSUE THREAD

**Issue by GCHQ-Developer-094** [mi6/ic-ui-kit#2072]
## Summary

Most components have three size options: default, small and large. We want to update and change all instances of 'Default' to 'Medium'.

Additionally, a review of current component sizes implemented would also benefit

## Outputs

- Update Figma component library
- Create list of components that would benefit from additional sizing options (to be implemented separately at later date)

Following components have had size 'default' updated to 'medium':  
Accordion 
Badge
Button
Checkbox
Chip
Date picker
Empty state
Loading indicator
Page header
Radio button
Search bar
Status tag
Switch
Text field
Top navigation
 

## Additional info

See related tickets:

- https://github.com/orgs/mi6/projects/2/views/10?filterQuery=size&pane=issue&itemId=68694543
- https://github.com/mi6/ic-ui-kit/issues/881

**Comment by gd2910** [comment]
Guidance will need to be updated, see [ticket](https://github.com/mi6/ic-design-system/issues/1090)
