### ISSUE TITLE
Install Storybook performance add-on

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#2087]
## Summary
As part of the exploration into how we can performance test ICDS components, the Storybook performance add-on should be installed.

## 💬 Description 
This task is to install the Storybook performance add-on and test the implementation against existing React stories - https://storybook.js.org/addons/storybook-addon-performance

## Why do we need it? 
To try using the performance add-on to check and debug performance of React components and hence help determine how we carry out performance testing of ICDS components.

**Comment by MI6-255** [comment]
If this doesn't give us what we need, we can go down the route of exploring what @MI6-286 and @jd239 have been working on with rendering a page with the components on and using Lighthouse.

**Comment by evenstensberg** [comment]
Some more docs about the addon

- https://dev.to/vborodulin/welcome-storybook-addon-performance-55l4

**Comment by MI6-255** [comment]
If time, just do one example

**Comment by MI6-255** [comment]
React only Storybook
