### ISSUE TITLE
[ic-tooltip] Cypress migration

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#2089]
## Summary
Generate E2E Cypress tests for ic-tooltip, replacing and removing the older tests and adding additional tests where needed.

There are currently Cypress visual regression tests and a11y tests that have been added as part of #1891.  However, a full migration is required.

**Comment by evenstensberg** [comment]
Maybe trying out Playwright? Its is widely used now for e2e tests, customisable and actively maintained.

https://playwright.dev/
