### ISSUE TITLE
Introduce a npm pack script

### ISSUE THREAD

**Issue by evenstensberg** [mi6/ic-ui-kit#2105]
## Summary 
In the README (https://github.com/mi6/ic-ui-kit?tab=readme-ov-file#local-build-and-install) there's a very repetitive process, and we can make a simple util script to batch theese duplicate commands.

## 💬 Description 
Make a bash script that packs and builds automatically.

## 💰 Use value 
Easier to develop

## 📝 Acceptance Criteria  
N/A

## ✏ Designs 
N/A

## 🧾 Guidance 
Write about the script in readme.md

## Additional info 
NA

**Comment by GCHQ-Developer-299** [comment]
Hi @evenstensberg we appreciate the contribution but could you please refrain from adding GIFs to your issues. While there's nothing specifically in our [Code of Conduct](https://github.com/mi6/ic-design-system/blob/main/CODE_OF_CONDUCT.md) about keeping things professional, we are a government organisation. 
If a section of the Issue template doesn't apply you're welcome to remove it instead. Many thanks.

**Comment by evenstensberg** [comment]
@GCHQ-Developer-299 Hi. Sure and sorr for that. Removed the gif

**Comment by MI6-255** [comment]
Keep this ticket to introduce a npm run pack, building on this: https://github.com/mi6/ic-ui-kit/pull/2180/files#diff-acd7f6b1c62b759b805434f15773bd61949ef0bdb78dfc9fa98100bf216cc443
