### ISSUE TITLE
Move multi-select from canary to core package

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#2108]
## Summary 
Move the multi-select component from the canary package to the core packages

## 💬 Description 
When first implemented as a canary component, 
To bring the component into the core package, the 2 code bases need to be merged back into a single select component

This should be done sooner rather than later, as this will become a more complex task as more changes are made to ic-select. there are already changes (for example adding an icon into the ic-select), which are not in the select-with-multi code base

A decision needs to be made at what point we are happy to do this - after reaching out for feedback?

Before releasing we should ensure that there is sufficient test coverage in the unit tests

##Additional info
Doing this work will remove the need to complete #2095 
#1700 should also be completed before release

**Comment by MI6-255** [comment]
As part of v3
