### ISSUE TITLE
[ic-card] clickable cards do not use current link styling

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-ui-kit#213]
## Summary of the bug
Global link styles have recently been updated, but the cards component does not seem to have been updated in accordance. 

## 🧐 Expected behaviour
Cards (clickable) use a link as the card title. This should be updated to match the other link styling throughout the site.

## 📸 Screenshots or code
![Screenshot from 2023-01-05 11-26-05](https://user-images.githubusercontent.com/117368893/210771231-52acc61c-0bc7-4a95-a684-ec8c06d5fefd.png)
![Screenshot from 2023-01-05 11-26-01](https://user-images.githubusercontent.com/117368893/210771234-b16aedb3-1227-446a-909e-6b9412edf048.png)

**Comment by jd239** [comment]
Work being done in #245
