### ISSUE TITLE
Upgrade package version on v3 branch to version 3 and surrounding work

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#2147]
## Summary 
Upgrade the package.json version to version 3, and test the pipelines work as expected

## 💬 Description 
The actions for this issue are as follows:

1. Upgrade the package.json version to version 3, on the `v3.0.0/develop`, and any other places it needs updating 
2. Change the manual pipeline for v3 to an automated one (https://github.com/mi6/ic-ui-kit/issues/2059), when changes are moved to `v3.0.0/main`. This is just a v3 develop to v3 main that needs doing here, which may need adding to the release instructions. 
3. Test the now automated pipeline works and adds the next flag to commits, and that an npm install of our package, does not install v3 (having this v3 package with the flag on npm is fine)
4. Check if there are any issues with the develop to v3 pipeline ([#2058](https://github.com/mi6/ic-ui-kit/issues/2058)) in regards to the package.json in v3 being overwritten by the v2 branch being merged in
5. Install the v3 package on the design system website repo, in the v3 package only (to discuss if we want to do this, and what our process will be for breaking changes)

## 💰 Use value 
Have the infrastructure setup so we can deploy v3 at a later date for early testers.

**Comment by MI6-255** [comment]
Double check before starting, that the v3 release has a prerelease flag that will prevent it being installed when npm install @ukic/react@latest is run for example

**Comment by GCHQ-Developer-299** [comment]
I tried to manually bump all the package versions in a PR but builds failed because v3.0.0 packages didn't exist. I think we might need to do a v.3.0.0 release using the [release-v3 pipeline](https://github.com/mi6/ic-ui-kit/actions/workflows/ic-ui-kit-release-v3.yml) so that v3.0.0 versions of the core packages exist. Then we can update 'dependencies' and 'peerDependencies'
