### ISSUE TITLE
Accordion slotted heading story is not as expected in React

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#2148]
## Summary of the bug 
The slotted heading in the Slotted headings React Component story of Accordion is not displaying as expected in Storybook. 

## 🪜 How to reproduce
1. Open the React Components Storybook and navigate to Accordion > Slotted headings

## 📸 Screenshots or code 
![image](https://github.com/user-attachments/assets/b9e6d99f-dc79-4a3f-8861-9808f118b758)

## 🧐 Expected behaviour 
The slotted heading should display as below:
![image](https://github.com/user-attachments/assets/69cac9f7-a425-4123-be2c-4fe51e1f5b2d)

## 📝 Acceptance Criteria  
*Given* I navigate to Accordion > Slotted headings within React Storybook
*Then* The accordion heading is displayed as expected

**Comment by GCHQ-Developer-299** [comment]
Cypress test uses the same markup as Storybook but renders correctly.

In the storybook, the heading and 'text' are wrapped in a <p> tag, this is causing the issue - might be storybook trying to 'fix' loose elements. Try wrapping 'text' inside an IcTypography.
