### ISSUE TITLE
Explore styling differences for tabs and nav items

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-ui-kit#215]
## Summary
Tabs and Nav Items look similar, which leads to the expectation that they must work in a similar way.

## 💬 Description
Possible issue in nav bar as items looks like tabs and therefore causing expectation of different mode of operation through keyboard. Make styling different between navs and tabs so that it is obvious which components is which and therefore how to interact. Changing tab styling can also enable better visual connection between the tab container that the tabs control. Research whether current nav bar styling is causing people to misunderstand how to interact with page header nav bar items.

## 💰 Use value
To remove confusion about each component's functionality and purpose.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
