### ISSUE TITLE
ic-classification-banner does not handle undefined values being passed as props

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-ui-kit#2177]
## Summary of the bug 
When implementing a classification banner, a lot of the prop types are set to `string | undefined`, which works well when the prop is not defined at all as it can easily default to an empty string. However, I've noticed that if the content of a prop is optionally chained (see code section), when it short circuits and returns undefined, it actually renders undefined rather than using the built-in fallback value.

## 📸 Screenshots or code 
```tsx
<IcClassificationBanner
  country={country?.toUpperCase()}
  additionalSelectors={additionalSelectors?.toUpperCase()}
  classification="official-sensitive"
/>
```
![Screenshot 2024-07-18 at 10 06 52](https://github.com/user-attachments/assets/3cfb0c7d-b0d7-4848-a0ea-c0c6c3e9939c)

## 🧐 Expected behaviour 
I'd expect it to handle when undefined is passed as a prop value and show the intended default value as though the prop was never defined at all.

## Additional info 
One thing I noticed is that when I refresh the page with the banner in this state, it will display the default values as intended. I can only assume since the DOM element is listed as having no prop values, it will apply the default values.
![Screenshot 2024-07-18 at 10 12 01](https://github.com/user-attachments/assets/2e0ac990-8579-4edb-800c-e058bb9c5b4a)
![Screenshot 2024-07-18 at 10 12 59](https://github.com/user-attachments/assets/50980020-be19-44cf-a8db-22c6631c39e9)

**Comment by srt544** [comment]
Already implemented
