### ISSUE TITLE
Text Field with type number allows non numeric values in Safari

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#2187]
## Summary of the bug 
Text Field with type number allows non numeric values in Safari

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 

1. Open Safari
2. Navigate to https://design.sis.gov.uk/components/text-field/code#with-min-and-max-values
3. Type in a non-numeric value (this is not allowed in Chrome)

## 📸 Screenshots or code 
![Screenshot 2024-07-19 at 10 56 21](https://github.com/user-attachments/assets/144d4474-a9bd-4a44-9d02-05d8fc81f3ac)

## 🧐 Expected behaviour 
Not allow non numeric entry

**Comment by ad9242** [comment]
this appears to be standard behaviour for a native input type=number in safari. there are lots of references to safari not supporting it, so question whether we should really implement it

**Comment by ad9242** [comment]
closing as browser behaviour
