### ISSUE TITLE
[ic-card] Rename to ic-card-vertical

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#2216]
## Summary 
With the introduction of horizontal cards, ic-card should be renamed to make it obvious that it is the vertical variant.

## 💬 Description 
Horizontal cards have been named ic-card-horizontal. A suggestion made by the community was that ic-card should be renamed to ic-card-vertical so that the two still show next to each other alphabetically and there's an obvious distinction between the two components.

## 💰 Use value 
It will help users tell the two card components apart.

**Comment by MI6-255** [comment]
Design need to do this in Figma too

**Comment by MI6-255** [comment]
Guidance needs updating
