### ISSUE TITLE
Suggestion: Rename fonts (generated styles) to something more pragmatic

### ISSUE THREAD

**Issue by evenstensberg** [mi6/ic-ui-kit#2227]
## Summary
If you're a 3rd party user of ic-ui-kit and need to import the styles, the namespace is `ic-ui-kit/fonts`. That's not very intuitive, maybe the generated styling should be renamed to something more correct, like `ic-ui-kit/styles`?

## 💬 Description 
See above

## Why do we need it?
It's not **needed**, but it will make it more clear to a user that the font style file is a global stylesheet.

**Comment by evenstensberg** [comment]
I think this is the last infra bug I have. Will work on issues/triaged issues from now on.

**Comment by GCHQ-Developer-299** [comment]
The fonts package does only contain fonts - and since packages and their contents are described on the guidance site and npm.
