### ISSUE TITLE
Ensure IcAlert status versions pass a11y checks in high contrast mode

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-ui-kit#2240]
## Summary of the bug 
Currently IcAlert is not passing a11y checks in high-contrast, colours must be changed to a higher contrast to pass.

Ticket will have to pass through design to choose the new colours before ready for dev.

Once colours are decided please uncomment the a11y checks on the cypress e2e tests.

## 📸 Screenshots or code 
![image](https://github.com/user-attachments/assets/4c64da3c-090c-4bed-a335-d64f0ad5446f)

**Comment by GCHQ-Developer-299** [comment]
Redundant due to developments in v3. We're on the case!
