### ISSUE TITLE
Date Range

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-ui-kit#225]
## Summary
Related to #219 Date picker either as a future improvement or as a separate component but built on the date picker.

## 💰 User value
Describe why this is important and how it will help users (either developers, designers or the end-users). Think about how it makes people's lives easier, more accessible or quicker to build stuff.

## 📚 User Stories
If relevant, describe the high-level functionality as user stories.

*As an* ICDS user: 
*I need* 
*So that*

## 📝 Acceptance Criteria 
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

*Given*
*When* 
*Then*

## ✏ Designs
If there's a Figma design file (or other mock-up), include it here.

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by jd239** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat?s=03

**Comment by GCHQ-Developer-094** [comment]
Duplicate
