### ISSUE TITLE
Remove deprecated events and props

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#230]
A number of props\events have been renamed and marked as deprecated (including Issue #228 which implemented a deprecation warning for some events)

The following changes need to be made:

- remove any references from the component docs of the old names (can search for `@deprecated` in the code)
- remove any code which is emitting the old events
- ensure new props\events are covered in testing
- remove testing of old props\event names (if required)
- ensure any examples do not reference the old names (if they do on the site, a separate ticket may need to be raised on the ic-design-system repo  to remove them)

Also look into removing any props that seem redundant but haven't been deprecated yet - an example of this is "current" prop for ic-step, which could just be replaces by type="current" which we already have.

**Comment by GCHQ-Developer-530** [comment]
Remove any props/events/methods on the dialog related to buttons. Buttons should only be added to dialog using dialog-controls slot

**Comment by MI6-255** [comment]
Bare in mind there may be more tests for code coverage
