### ISSUE TITLE
[ic-date-input] - spacing of input field and helper text does not match designs

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#2301]
## Summary of the bug 
When a date input is displayed with helper text, the input field is too close to the helper text

## 📸 Screenshots or code 

figma (on the left) has more spacing:
![image](https://github.com/user-attachments/assets/84181ea4-d121-44e3-92f5-54bb0952149f)

## Additional info
visual regression baseline images will need updating

**Comment by samarsrivastav** [comment]
hey @ad9242 , i would like to take up the issue.
Could you please give some more details on the bug!!

**Comment by MI6-255** [comment]
Do this in the v3 branch with it being for Text Field
