### ISSUE TITLE
[ic-loading-indicator] loading indicator does not display when slotted into Top Navigation

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#2313]
## Summary of the bug 
When trying to place a `ic-loading-indicator` into the `navigation` slot on `ic-top-navigation`, it is not visible:
![image](https://github.com/user-attachments/assets/ac8c6a0a-56e8-4ff9-9a89-71dddaf8299a)

It is in the dom, but seems the svg element seems to have 0 size:
![image](https://github.com/user-attachments/assets/8bfe2b65-73f6-45e0-949b-00879a38583e)

From some investigation it seems that the code within the `componentDidLoad` is detecting that the `outerElement` has 0 width. Wrapping this code in a `setTimeout` appeared to make the element visible, but further investigation should be carried out as to whether this is the best approach - maybe it would be better to check for when the indicator is placed in a top navigation element

```
      if (this.el.closest("ic-top-navigation")) {
        setTimeout(() => {
          this.setCircleLineWidth();
          this.circularMeter = this.el.shadowRoot.querySelector(
            ".ic-loading-circular-svg circle:nth-child(2)"
          );
          this.updateCircularProgressMeter();
        }, 300);
      }
      else{  
```

or investigate if there is some way to avoid the need for a `setTimeout` completely - possibly watching for some kind of content or attribute change.

Once this was solved there were still some issues with the colours used, which may be accessibility issues. However, it should be possible to define colours using the following tokens:
--inner-color (most likely set to --ic-theme-text)
--outer-color (set to ? )
 
Some additional padding may also be required to fix alignment.

## 🪜 How to reproduce 
See the following : [StackBlitz example](https://stackblitz.com/edit/zeljuv-jcqcjp?file=src%2Fapp.tsx)

## 🧐 Expected behaviour 
The loading indicator should be visible

## Additional info 
May want to check with design that this is valid use case of the loading indicator, but it seems pretty reasonable

**Comment by GCHQ-Developer-299** [comment]
Comment from design: We'd probably not support this, instead recommending the whole page be in a loading state (using Skeleton component) until all navigation items are available.  It would be a very unusual workflow for Top Navigation to contain a loading indicator.
