### ISSUE TITLE
[ic-stepper] Interactive stepper

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#233]
## Summary
Can stepper steps be made clickable?

Consider effect on processes with conditional content. 

What happens if you skip forward to last step?

Who is responsible for deciding what happens with input data from steps if user moves between steps? 

Is there a better pattern than a stepper, that does not suggest an order series of steps, but rather an unordered set of items that need completing.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
