### ISSUE TITLE
Explore if we remove the React Storybook

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#237]
## Summary
Explore if we remove the React Storybook, for a smoother dev experience by:
- not having to update stories in two places
- not having a mis-match in stories we missed
- not having to commit twice

## 💬 Description
Have we had a need for the React library? Are we confident if the web component version works, Stencil takes care of the rest? We could consider keeping the setup for testing (e.g. for quick testing if something works with React Router for example) but deleting the stories, so there's not the bad developer experience there and repeating code.

**Comment by GCHQ-Developer-112** [comment]
This was discussed by the core team in a refinement session on 15/02. The decision was made to re-introduce the React Storybook that we had previously removed

Ticket: [Deploy the React Storybook to branch builds](https://github.com/mi6/ic-ui-kit/issues/377)
PR: [Add react storybook to deploy step](https://github.com/mi6/ic-ui-kit/pull/388)
