### ISSUE TITLE
Search icon becomes invisible at small breakpoints on Safari

### ISSUE THREAD

**Issue by MI6-654** [mi6/ic-ui-kit#2374]
## Summary of the bug 
Tell us, in a few words, what the problem is. 
On Safari, the search icon becomes invisible at small breakpoints then reappears at even smaller breakpoints.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
On Safari, zoom in on the Design System website and notice how the search icon becomes invisible at small breakpoints then reappears as you keep zooming in.

## 📸 Screenshots or code 
If you can, add screenshots to show the problem. If you need to show a code example, you can include a snippet or link to a repository with an example. 

<img width="894" alt="image" src="https://github.com/mi6/ic-ui-kit/assets/161740861/3999e1e3-787a-49d4-a4d1-f8bf69ff6254">
Image 1: Search Icon is invisible at small breakpoint but hover and tooltip reveals it's still there. It's still clickable and functions as expected.

<img width="894" alt="image" src="https://github.com/mi6/ic-ui-kit/assets/161740861/ed364b4b-9007-424f-bf1f-2a9a5b48836f">
Image 2: Search icon becomes visible again at even smaller breakpoint.

## 🖥 📱 Device 
- Type: Desktop
- Device: MacBook
- OS version: macOS14
- Browser version: Safari 17.4 

## 🧐 Expected behaviour 
Tell us, in enough detail, what you expected to happen instead. 
At all small breakpoints, the search icon should always be visible.

**Comment by GCHQ-Developer-530** [comment]
Completing as part of https://github.com/mi6/ic-ui-kit/issues/2178 to avoid breaking user VR tests
