### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#238]
## Summary
Dialogs are modal windows that provide important messaging to users. As they are presented modally, they interrupt the user's flow to display vital information. The user must interact with the dialog in order to continue. This is usually by performing the primary action provided in a modal, or dismissing the modal. 
_Please ensure modal shadow is applied_ 

https://web.dev/building-a-dialog-component/

The modal container provides the background and behaviour for content that needs to be displayed modally. Any other content can be added to the container and the mechanism of the modal will be consistent with all others. 

## 💰 User value
Foundational component required to provide ICDS users the tools to build rich applications. Modal containers provide a method to house content in a modal layer above the context of the base layer. 

## 📚 User Stories
If relevant, describe the high-level functionality as user stories.

**As an** ICDS user
**I need**  a default dialog that contains:
Title
Description
Dismiss button (X button)
Primary action button
Dismiss action button
So that I can display important messages to users. 

**As an** ICDS user
**I need** an information dialog
**So that** I can simply provide information that can then be closed.  

**As an** ICDS user
**I need** to be able to select a status (success, warning, error, information) to display on the dialog
**So that** i can indicate the severity of the message. 

**As an** ICDS user
**I need** to be able to choose the dialog size (small, medium, large) 
**So that** I can add longer messages. 

**As an** ICDS user
**I need** to be able to enter markdown into the dialog body
**So that** I can add different types of content. 

**As an** ICDS user
**I need** to be able to add a child element to the dialog body
**So that** I can add interactive content. 

**As an** ICDS user
**I need** to have the content area scroll when the maximum vertical modal size is reached
**So that** longer content can be viewed in the dialog. 

**As an** ICDS user
**I need** a modal container to appear above the background layer
**So that** I can house other content.

**As an** ICDS user
**I need** a dark overlay to appear over the background content, but behind the modal container
**So that** the modal is differentiated from the background layer. 

**As an** ICDS user
**I need** the following different sizes of modal container:
Small (4 columns?)
Medium (6 columns?)
Large (8 columns?)
**So that** i can add different amounts of content. 

**As an** ICDS user
**I need** to be able to dismiss the modal using a control in the container content, as well as by pressing the modal background overlay
**So that** I can quickly close the modal content and return to the base layer. 

**As an** ICDS user
**I need** to ensure that only one modal is displayed at a time
**So that** modal layers do not stack.  

**As an** ICDS user
**I need** the container's vertical height to scale to fit the content, until a max/min height,
**So that** the content is wrapped effectively. 

**As an** ICDS user
**I need** to the container to scroll in cases where the content is too large for the container
**So that** all the content is viewable in the container. 

**As an** ICDS user
**I need** the container to appear centred in the viewport
**So that** all modals are presented in the same position. 

**As an** ICDS user
**I need** the container to have defined title, content, and action areas
**So that** modal content is laid out consistently.

## Acceptance criteria

**Given**
**When**
**Then**

### Scrim
**Given** that a dialog exists on a page
**When** it is opened
**Then** a background scrim layer should appear underneath. 

**Given** that a dialog is open on a page, and the property 'preventCloseOnBackgroundClick' is not 'true'
**When** a user clicks the background scrim
**Then** then the dialog should close, and user focus should be returned to the dialog opening element. 

**Given** that a dialog is open on a page, and the property 'preventCloseOnBackgroundClick' is 'true'
**When** a user clicks the background scrim
**Then** then the dialog should remain open.

### Dialog type
**Given** that a dialog is being implemented
**When** setting the 'dialogType' property to 'destructive'
**Then** the primary button should be replaced with a destructive button. 
**and** when opened, focus should be automatically applied to the tertiary or dismiss button. 

**Given** that a dialog is being implemented
**When** setting the 'dialogType' property to 'information'
**Then** the action area should be hidden
**and** when opened, focus should be automatically applied to the dismiss button. 

**Given** that a dialog is being implemented with 'dialogType' property set to 'confirmation'
**When** the dialog is opened
**Then** focus should be automatically applied to the primary button. 

### Actions
**Given** that a dialog is being implemented
**When** setting the 'numberActions' property
**Then** there should be a choice of number of actions to display as default:
- 1 action: primary button on right hand side. 
- 2 action: Primary button on right hand side. Tertiary button to its left. 
- 3 action: Primary button on right hand side. 2 secondary buttons to its left. 

**Given** that a dialog is being implemented, and is either dialogType confirmation or destructive,
**When** setting the properties,
**Then** the 'customActions' can be used to specify slot contents for the action bar so that different combinations of actions can be included instead of the defaults. 

### Header
**Given** that a dialog is being implemented 
**When** setting the header details
**Then** a 'dialogHeading' must be provided. 

**Given** that a dialog is being implemented 
**When** setting the header details
**Then** a 'dialogLabel' can optionally be provided. 

**Given** that a dialog is being implemented
**When** no 'dialogLabel' is specified
**Then** the label element shouldn't be displayed. 

**Given** that a dialog is being implemented 
**When** setting the header details
**Then** a dismiss button must always be rendered. 

### Dismiss button
**Given** that a dialog exists
**When** clicking the dismiss button, or hitting the 'Esc' key
**Then** the dialog is dismissed and the user is returned to their previous location on the base page.

**Given** that a dialog exists
**When** setting the 'dismissLabel' prop to any other string,
**Then** the ariaLabel should contain the value of 'dismissLabel'.

 **Given** that a dialog exists
**When** hovering or focussing on the dismiss button
**Then** then a tooltip is displayed reading 'Close'. 

 
### Content
**Given** that a dialog is being implemented
**When** setting the properties,
**Then** the 'customContent' can be used to specify slot contents for the content area so that different content can be specified instead of the defaults. 

**Given** that a dialog is being implemented
**When** the 'customContent' property is not used, 
**Then** the default layout content should be used which includes:
- Status area
- Description
- Interaction area

### Status
**Given** that a dialog is being implemented
**When** setting the 'status' property
**Then** the following values can be used:
- 'None' - No alert is rendered. 
- 'Success' - Success alert rendered. 
- 'Warning' - Warning alert rendered. 
- 'Error' - Error alert rendered. 
- 'Information' - Info alert rendered. 
- 'Neutral' - Neutral alert rendered. 

**Given** that a dialog with a 'status=Neutral' has been set
**When** using the 'neutralStatusIcon' prop, 
**Then** a custom icon can be selected to display in the alert icon slot. 

**Given** that a dialog with a status has been set, 
**When** setting the alert settings
**Then** the alert heading and description should be able to be set. 
**and** the alert should always use 'titleAbove=true'
**and** the alert should always use 'dismissible=false'
**and** the alert should not contain any slotted actions.

### Description
**Given** that a dialog with default content layout is being implemetned
**When** adding the textual content using the 'dialogDescription' property
**Then** the textual content should be displayed under the alert area. 

### Interaction area
**Given** that a dialog with default content layout is being implement
**When** setting the properties
**Then** the 'interactionArea' slot can be used to add interactive elements
**And** when opened focus should be automatically applied to the first interactive element. 

### Scrolling and vertical sizing
**Given** that a dialog with default content layout is being implemented
**When** the specified content is larger than the default vertical size
**Then** the dialog should grow to display the content, until it reaches the max-height and then the content area should become scrollable. 

### Sizing
**Given** that a dialog is being implemented
**When** setting the size property
**Then** the following should be used:
- Size: Small
-- Width: 50%
-- Max-width: 400px.
-- Min-height: 176px.
-- Max-height: 50%.   
- Size: Medium
-- Width: 70%
-- Max-width: 720px.  
-- Min-height: 200px.
-- Max-height: 70%.   
- Size: Large
-- Width: 90%
-- Max-width: 1080px.  
-- Min-height: 200px.
-- Max-height: 90%.

**Given** that a dialog with 'size=Large'   is being implemented
**When** using default content layout
**Then** the width of the content area should be 75% of the dialog width and left-aligned. 

### Positioning
**Given** that a dialog of any size exists, and the breakpoint is not XS
**When** opened
**Then** it should be displayed vertically and horizontally centered in the viewport. 

### Fullscreen
**Given** that a dialog is being implemented
**When** setting the fullScreen property as 'true'
**Then** dialog should fill the viewport. 

### Responsiveness
**Given** that a dialog of any size exists
**When** the viewport is resized (or zoomed) to equate to the XS breakpoint, 
**Then** the full screen property should be automatically applied. 

### Motion
**Given** that a dialog exists and breakpoint is not XS
**When** the dialog is opened
**Then** it should transition into view using the follwoing properties:
- Scrim - Fade in - opacity 0%-100% -  use --ic-easing-transition-slow
- Dialog - Fade in - opacity 0%-100% - use --ic-easing-transition-slow
- Dialog - Position - Y-axis -48px -> y-axis 0px (relative to centred positioning) - use --ic-easing-transition-slow

**Given** that a dialog exists and breakpoint is not XS
**When** the dialog is closed
**Then** it should transition out of view using the follwoing properties:
- Scrim - Fade out- opacity 100%-0% -  use --ic-easing-transition-slow
- Dialog - Fade out - opacity 100%-0% - use --ic-easing-transition-slow

**Given** that a dialog exists and breakpoint is XS
**When** dialog is opened
**Then** is should transition into view using following properties:
- Fade in - opacity 0-100% - use --ic-easing-transition-slow
- Position - y-axis -80px -> 0px - use --ic-easing-transition-slow

**Given** that a dialog exists and breakpoint is XS
**When** dialog is closed
**Then** is should transition out of view using following properties:
- Fade out - opacity 100%-0% - use --ic-easing-transition-slow

### Accessibility
**Given** that a dialog is being implemented
**When** setting properties
**Then** the dialogAriaLabel can be used to specify a custom aria label instead of it defaulting to the 'dialogHeading'. 

**Given** that a dialog exists
**When** opened
**Then** focus should move to the relevant option, and focus should be contained within the elements of the modal.
- Destructive dialog - initial focus on dismiss button
- Information dialog - initial focus on dismiss button
- Confirmation dialog - initial focus on primary button

**Given** that a dialog exists with interactive content
**when** opened
**Then** focus should be applied to the first interactive element. 

**Given** that a dialog exists
**When** rendered
**Then** it should use the <dialog> role. 

**Given** that a dialog is open
**When** interacting with content inside it
**Then** this should not be able to launch a dialog on top. (only 1 dialog at a time)

## Proposed prop naming
These are proposals only and can be changed if necessary. 

Props:
preventCloseOnBackgroundClick - boolean (default: false)
numberActions - 1 action, 2 action, 3 action. (default: 2)
dialogType - confirmation, destructive, information (default: confirmation)
customActions - SLOT (optional)
dialogHeading - string (required)
dialogLabel - string (optional)
dialogAriaLabel - string (optional) (default =[dialogLabel])
dismissAriaLabel- string (default 'close')
customContent - SLOT (optional)
status - none, success, warning, error, info, neutral (default: none)
neutralStatusIcon - icon select?
dialogDescription - string (required?Optional?)
size - small, medium, large
fullScreen - boolean (default: false)

**Comment by DBD324** [comment]
Associated documentation ticket: https://github.com/mi6/ic-design-system/issues/170
