### ISSUE TITLE
[ic-status-tag] New sizes

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#239]
## Summary
Status tags have been built. New requirements mean to address consistency issues, we need to include a small variant.

Change in variants:
Current: Default
New name: Large
Current: Dense
New name: Default
New size: Small

**Comment by MI6-255** [comment]
This ticket is now just to add the large variant

**Comment by GCHQ-Developer-094** [comment]
Deprecated
