### ISSUE TITLE
[ic-dialog] Allow disabled button prop

### ISSUE THREAD

**Issue by gd2910** [mi6/ic-ui-kit#2410]
## Summary 
Allow passing the `disabled` button prop in the `buttonProps` attribute.

## 💬 Description 
Current guidance suggests using a dialog to confirm choices but does not allow the disabling of the button until the choice is confirmed.
![image](https://github.com/user-attachments/assets/891e3ade-db87-4dce-8e32-5dbf2ec457ba)

## 💰 Use value 
This will allow developers to ensure choices are selected/confirmed before allowing confirmation of dialog.

## 📝 Acceptance Criteria  
*Given* 
A dialog asks a user to confirm a choice
*When*  
A choice/confirmation is not selected
*Then* 
The developer can disable the confirmation button

**Comment by ad9242** [comment]
closed as workaround is to use the "dialog-controls" slot and buttonProps is deprecated in v3
