### ISSUE TITLE
Investigate styling across shadow DOM boundaries

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#249]
## Summary
we have some components now where we are having to include css inside the component in order to style form the oustide.

## 💬 Description
A couple of examples:

In ic-text-field so we can style the search & clear icons that appears in search bar

In ic-button so the navigation-menu close menu button can be styled

Need to investigate if there is a better way to do this.

Could maybe use css parts, but currently the styles we are applying are internal to our components. It's possible that exposing as css parts will mean anyone can override these parts

## Additional info
@jd239 investigated this and found that: 
" I feel :parts offers the most flexibility. I appreciate that developers will be able to override styling by applying it to the part but think the onus is on them. If they stray away from the style we provide, it's their responsibility to make is accessible.

Another reason why i prefer this approach is because I do not want us to end up in a situation where we have 10+ CSS properties on a component: https://ionicframework.com/docs/api/button#css-custom-properties

On the flip side, we have more control over what can be changed when using CSS custom properties.

If we feel using CSS properties to pass styling from one component to another doesn't feel right (e.g. ic-button), then I think we should move forward with parts. 

Found this article from Ionic interesting: https://ionicframework.com/blog/customize-your-ionic-framework-app-with-css-shadow-parts/ "

**Comment by MI6-255** [comment]
Will cover whats left in customisation
