### ISSUE TITLE
Search higlighting

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-ui-kit#251]
## Summary
When a user searches for a term, highlight in the results what my search result matched on.

## 💬 Description
The search would work even better if it was like the attached (MUI), providing a snippet.

## 💰 Use value
Would give the user more information behind their search results

## Additional info
![Screenshot from 2023-01-09 14-42-47](https://user-images.githubusercontent.com/117368893/211334602-eb7ad2da-bd2f-4375-9d4c-dc2457f8425f.png)

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
