### ISSUE TITLE
Scroll bar behaviour with components

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-ui-kit#255]
## Summary
Investigate scroll bar behaviour with certain components.

## 💬 Description
Scrollable components like side-nav, left-hand-nav and select lists will render default browser scrollbars. 
This can affect perceived alignment of content when overlaid. 
Explore what changes need to be made to accommodate the scrollbars on different browsers and define changes required. 

## 💰 Use value
Improved usability, developer experience and end user experience (e.g. the design system website)

## Additional info
Affected components:

Side nav
Top bar (hamburger)
Left-hand-nav
Tabs and nav bar horizontal scrolling
Select/dropdown lists
dialogs

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
