### ISSUE TITLE
Update modal and dialog examples (width and height)

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#260]
## Summary
Update the modal and dialog examples in the Figma library based on the new min and max heights specified.

## 💬 Description
When completing this, add comments to the modal ticket for the reasoning behind the widths and heights for each modal size.

## 💰 Use value
Developers know the reasoning behind the sizes of modals.

**Comment by GCHQ-Developer-094** [comment]
Fullscreen variant in Figma and components can be manually resized. Marked as complete.
