### ISSUE TITLE
Investigate Sonarqube integration with Github Actions

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#261]
## Summary
Some investigation is required to see if we can integrate sonarqube into our pipelines. Sonarqube is a static type checking platform which will identify potential bugs and code smells.

**Comment by jd239** [comment]
I stumbled on an open source alternative to Sonarqube called CodeQL (https://codeql.github.com/) as I think Sonarqube needs to be hosted somewhere to be used.

**Comment by MI6-255** [comment]
CodeQL also integrates nicely to GitHub

**Comment by GCHQ-Developer-530** [comment]
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning-for-a-repository#configuring-code-scanning-automatically

**Comment by GCHQ-Developer-530** [comment]
We've added CodeQL which runs on every pull request, but it seems to only scan for vulnerabilities and not code smells like we expected. Our static analysis tests seem to pick up code smells, but leaving this ticket open in case we find a better way of picking them up.
