### ISSUE TITLE
[IcSelect] Select selected option overlaps close icon

### ISSUE THREAD

**Issue by OrangeCaterpillar** [mi6/ic-ui-kit#2611]
## Summary of the bug 
When an option is wider than the select, then the value inside the select input overlaps the close icon. See attached screenshot below

Whilst we typically avoid using long options, some are needed and the styling should take this into account

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Create a page with an IcSelect component on it
2. Provide an option that is larger in width than the IcSelect
3. Choose the large option
4. See the overlapping caused by the option/value and the close icon within the IcSelect input

## 📸 Screenshots or code 
```typescript
  <IcSectionContainer aligned="full-width">
    <IcSelect
      label="test"
      options={[{
        label: "very long option, very long option, very long option, very long option, very long option",
        value: "test",
      }]
      }
      showClearButton
      onIcChange={(e) => console.log(e)}
      value=""
    />
  </IcSectionContainer>
```

<img width="311" alt="image" src="https://github.com/user-attachments/assets/73eecd29-7e1f-492d-acf4-70940240d201">

## 🖥 📱 Device 
Type: Desktop/Mobile
Device: Macbook
OS version: macOS12
Browser version: Chrome Version 126.0.6478.127 (Official Build)

## 🧐 Expected behaviour 
The close icon should not be overlapping the values inside the select

## 📝 Acceptance Criteria  
*Given* I have a option that is wider than the select input
*When* I select the option
*Then* the close icon and the value shouldn't overlap

**Comment by MI6-255** [comment]
This might be fixed with a recent change

**Comment by GCHQ-Developer-847** [comment]
This will be fixed once the [multi-select move to the core package has been completed](https://github.com/mi6/ic-ui-kit/issues/2108) - as the select component will have been updated to show an ellipsis when the text overflows. (This change will be available in v3)

I have double-checked that my changes for that ticket fix this issue with long options in the single select (and other variants).
