### ISSUE TITLE
Suggestion: Move from barrel files to absolute imports

### ISSUE THREAD

**Issue by evenstensberg** [mi6/ic-ui-kit#2619]
## Summary 
Barrel files often makes optimisations and performance worse. This project should move from barrel files to absolute imports to improve performance and readability for components.

## 💬 Description 
See above

## 💰 Use value 
- Good performance
- Makes code more readable
- Bundlers perform better with tree shaking etc

## 📝 Acceptance Criteria  

*Given* removal of barrel files
*When*  building the components
*Then* it should improve load times and performance

## ✏ Designs 
N/A

## 🧾 Guidance 
- https://stenciljs.com/docs/module-bundling 

## Additional info 
N/A

**Comment by MI6-255** [comment]
Thanks for the suggestion. Would you be able to share examples of where this would change in our codebase please?

**Comment by evenstensberg** [comment]
I've got some tips that the ic repo in react performs well when we see the `__PURE__` pragma definition in the output after compiling the react components. 

I still think we can improve the importing in web-components to not use index.js when importing, but to import from the correct folders. If that isn't possible, I'll close this issue.

**Comment by evenstensberg** [comment]
Found a solution for compiling the web-components individually (https://stenciljs.com/docs/custom-elements#customelementsexportbehavior), but the react output will still be the same. Closing this issue.

**Comment by evenstensberg** [comment]
Actually I’ll try to fix this, this weekend. Closing it if it gets too hard.
