### ISSUE TITLE
Update label colour for disabled inputs

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-ui-kit#262]
## Summary
Update the text colour for inputs that use a label so that it remains the same colour when the input is disabled.

## 💬 Description
Currently when an input that uses a label is disabled as well as the input component itself, the text colour of the label switches to grey. While this can meet accessibility requirements for colour contrast it can still make it harder to understand what an input is for when it is disabled. We have decided to change this behaviour so the label colour remains the same when the input is disabled allowing the input information to remain clear and easily readable when an input is disabled but, as the input itself will be greyed out, still keeping it clear that the input is disabled.

## 💰 Use value
Improves user experience when using components while maintaining accessibility requirements.

## Additional info
This change should affect all components that have a disabled state and a label.

**Comment by jd239** [comment]
Ignore text colour change when disabled
