### ISSUE TITLE
Investigate ICDS environmental impact

### ISSUE THREAD

**Issue by GCHQ-Developer-741** [mi6/ic-ui-kit#267]
## What is the purpose of the work?
Evaluate the ICDS environmental impact and steps we can take to reduce our carbon footprint.
Inefficiencies such as:
- serving 8MBs of search data

There will be greater value on focusing on components (rather than microsite), as that's where the efforts can be scaled.

**Comment by jd239** [comment]
Links to https://github.com/mi6/ic-ui-kit/issues/524

**Comment by GCHQ-Developer-094** [comment]
Duplicate - done
