### ISSUE TITLE
Adding types to React package

### ISSUE THREAD

**Issue by cd3859** [mi6/ic-ui-kit#2679]
## Summary 
Adding types to React Packages

## 💬 Description 
Adding the types from the web-component packages to the React packages 

## 💰 Use value 
Currently types are only accessible in the web-component package, meaning if types are imported into a project the whole web-component package will be bundled regardless of if an actual component from the package is used. By copying over types to the React counterparts this will allow users to utilize types without the need to import web-components if not needed.

**Comment by evenstensberg** [comment]
- https://stackoverflow.com/questions/75185668/how-to-add-stencils-intrinsicelements-to-reacts-intrinsicelements

**Comment by MI6-255** [comment]
Explore using a @types package and add guidance to the site

**Comment by MI6-255** [comment]
#1395

**Comment by MI6-255** [comment]
Marked as a duplicate
