### ISSUE TITLE
[ic-select/ic-search-bar] Add loading state to dropdown components: Select, multi-select, search, searchable select.

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#268]
## Summary
Consider default state are.
- If using a prop, consider what happens if the developer forgets to use it. Probs don't use prop.  

Consider how animations may mask the delay times
if using animations, consider what happens when user sets prefs to turn off animations. (already have animation dropdown)
Ensure that loading state is displayed for long enough if displayed at all. 

### Automatic loading state (may decide not to include this functionality)
**Given** that a select component exists, 
**When** the select component is clicked,
**Then** the empty droplist starts to animate into view over a duration of 300ms,
**And** the droplist is initially sized to house only the loading state. 

**Given** that a select component exists and has been clicked, 
**When** the droplist animation starts, 
**And** If the list options are loaded before the animation finishes, 
**Then** the droplist grows to display its full height with the options loaded. 

**Given** that a select component exists and has been clicked, 
**When** the droplist animation starts, 
**And** If the list options are not loaded before the animation finishes, 
**Then** the droplist displays the loading state,
**And** the loading state is displayed for a minimum duration of 1000ms. 

**Given** that a select component exists and has been clicked, 
**And** the loading state is displayed, 
**When** the list options are loaded,
**Then** the droplist animates to display its full height with the options loaded. 

**Given** that a select component exists and has been clicked, 
**And** the loading state is displayed, 
**When** the 'timeout' prop is set to true, 
**Then** the loading error state should be displayed. 

**Given** that a select component drop list is showing the loading error state
**When** the 'retry' button is pressed
**Then** the droplist should return to loading state whilst the next load takes place. 

### Search input loading
**Given** that a search component exists, 
**When** a user types a search term into the field, 
**Then** the droplist animates into view over a 300ms duration.

**Given** that a search component exists and a term has been entered,
**When** the droplist animation starts, 
**If** the search results are loaded before the animation finishes, 
**Then** the droplist grows to display its full height with the search results loaded. 

**Given** that a search component exists and a term has been entered,
**When** the droplist animation starts, 
**If** the search results are not loaded before the animation finishes, 
**Then** the droplist displays the loading state,
**And** the loading state is displayed for a minimum duration of 1000ms. 

**Given** that a search component exists and a term has been entered,
**And** the loading state is displayed, 
**When** the search results are loaded,
**Then** the droplist animates to display its full height with the results displayed. 

**Given** that a search component exists and a term has been entered,
**And** the loading state is displayed, 
**When** the search results take more than 10s to load, 
**Then** the droplist shows the no results state. 

**Given** that a search component exists and a term has been entered,
**And** the loading state is displayed, 
**When** no search results are found, 
**Then** the droplist shows the no results state, if the search component has the 'Show no results message' prop set. 

**Given** that a search bar term has been entered, 
**and** the search operation is underway,
**When** the 'timeout' prop is set to true, 
**Then** the loading error state should be displayed. 

**Given** that a search component drop list is showing the loading error state
**When** the 'retry' button is pressed
**Then** the droplist should return to loading state whilst the next search takes place. 

## 💰 Use value
Users will be able to see that options are loading, as opposed to nothing happening.

**Comment by DBD324** [comment]
The 'loading error state' designs can be found in a Figma branch off V2.1 titled '[update] 268-Include loading error state in droplists'

**Comment by jd239** [comment]
This is blocked by https://github.com/mi6/ic-ui-kit/issues/326
