### ISSUE TITLE
[ic-top-navigation] - Focus state overlaps with label text of navigation item

### ISSUE THREAD

**Issue by MI6-286** [mi6/ic-ui-kit#2692]
## Summary of the bug 
The focus state of an ic-navigation-item with a long label that wraps onto multiple lines overlaps with / touches the label text when within an ic-top-navigation menu open in mobile mode. 

In addition, when the navigation item has prop selected="true", the selected indicator does not increase in size to fit the multi-line navigation item.

## 🪜 How to reproduce 
1. View an ic-top-navigation with a navigation item that has a long label
2. Open the menu in mobile mode
3. Tab to focus the navigation item

## 📸 Screenshots or code 
![image](https://github.com/user-attachments/assets/463eae73-0674-47b0-a227-b1f12db8ee6a)

## Additional info 
The issue is not seen within ic-side-navigation:
![image](https://github.com/user-attachments/assets/cc8f009a-32d3-42f6-8d7e-ff2301283aa2)

**Comment by MI6-255** [comment]
There is guidance to not have a label as long as this, therefore we are closing the issue
