### ISSUE TITLE
Document versioning approach

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-ui-kit#271]
Release end of sprint, nut can easily change.

Follow SEMVER, but with that breaking changes extra

Need to be bringing it into sprint planning/PI planning our major breaking changes

Need to communicate the regular releases (e.g. say 12 months) and how frequent and give people notice (give people the next tag)

**Comment by jd239** [comment]
https://github.com/mi6/ic-design-system/issues/202#issuecomment-1377645453
