### ISSUE TITLE
[ic-menu-item] toggle variant - can't control toggle via state `toggleChecked` isn't a property

### ISSUE THREAD

**Issue by timja** [mi6/ic-ui-kit#2745]
## Summary of the bug 

It doesn't appear to be possible to set a toggle ic-menu-item to be toggled via state passed in.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. See https://github.com/mi6/ic-ui-kit/blob/895517389cf1b33e002f4b72661792fd74ee4cbb/packages/web-components/src/components/ic-menu-item/ic-menu-item.tsx#L36 its a state and not a prop, and there are no appropriate values when I browse the types

## 📸 Screenshots or code 
If you can, add screenshots to show the problem. If you need to show a code example, you can include a snippet or link to a repository with an example. 

```tsx
      <IcButton variant="secondary" id="button-1" onClick={handlePopoverToggled}>
        {heading}
      </IcButton>
      <IcPopoverMenu anchor="button-1" aria-label="popover" open={popoverOpen} onIcPopoverClosed={handlePopoverClosed}>
          {list.map((item) => {
            return (
              <IcMenuItem
                variant={"toggle"}
                // how can I mark this as checked / toggled?
                label={item.label}
                key={`key-selector-${item.key}`}
              />
            );
          })}
      </IcPopoverMenu>
```

## 🖥 📱 Device 
- Type: [e.g. Desktop, mobile] 
- Device: [e.g. iPhone, MacBook, ThinkPad] 
- OS version: [e.g. macOS13, iOS16, Android 13] 
- Browser version: [e.g. Chrome 115, Safari 16] 

## 🧐 Expected behaviour 
I should be able to mark this as toggled myself

## 📝 Acceptance Criteria  
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil. 

*Given* 
*When*  
*Then* 

## Additional info 
Tell us anything else useful to help us fix or understand the problem.

**Comment by GCHQ-Developer-112** [comment]
The [fix for this issue](https://github.com/mi6/ic-ui-kit/pull/2723) is available in our latest release

**Comment by timja** [comment]
Thanks I upgraded and was able to use, working good!

**Comment by tikto29** [comment]
<IcButton variant="secondary" id="button-1" onClick={handlePopoverToggled}>
        {heading}
      </IcButton>
      <IcPopoverMenu anchor="button-1" aria-label="popover" open={popoverOpen} onIcPopoverClosed={handlePopoverClosed}>
          {list.map((item) => {
            return (
              <IcMenuItem
                variant={"toggle"}
                // how can I mark this as checked / toggled?
                label={item.label}
                key={`key-selector-${item.key}`}
              />
            );
          })}
      </IcPopoverMenu>
