### ISSUE TITLE
Welcome new contributors to the repo: All jobs have failed

### ISSUE THREAD

**Issue by irl** [mi6/ic-ui-kit#2752]
## Summary of the bug 
Every time I open an issue on this repo, I get an email to let me know that GitHub Actions has failed to welcome me.

## 🪜 How to reproduce 
Tell us the steps to reproduce the problem: 
1. Be a new contributor
2. Submit an issue on this repo

## 📸 Screenshots or code 
<img width="571" alt="Screenshot 2024-11-10 at 08 42 00" src="https://github.com/user-attachments/assets/2e4b3d05-db93-43b2-b235-b2ae5a72689e">

## 🧐 Expected behaviour 
A robotic, yet warm, welcome.

## 📝 Acceptance Criteria  

*Given* a user is a new contributor
*When*  they open an issue
*Then* they get welcomed

**Comment by evenstensberg** [comment]
Do you have a link to the CI job?

**Comment by irl** [comment]
https://github.com/mi6/ic-ui-kit/actions/runs/11763632659

**Comment by evenstensberg** [comment]
You could try submitting a PR and see if the issue persists.

**Comment by irl** [comment]
> You could try submitting a PR and see if the issue persists.

I got the welcome email, CLA email, and warning that I'm targetting the wrong branch. All seems to be working there.

Did you fix something, or do you think it was a transient issue? I had exactly the same issue when submitting an issue on the ic-design-system repo.

**Comment by MI6-255** [comment]
This looks to be fixed now after tokens were updated.
