### ISSUE TITLE
Hover/pressed states for input components

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-ui-kit#279]
## Summary
Research into different options for hover/pressed states to apply to all input components (search bar, text fields, autocomplete) to maintain consistency.

## 💬 Description
Detailing design changes made:

Text fields have a hover state which applies a change to the outline colour.
Search fields have a hover and pressed state which applies a change to the outline and icon colour.
Dropdowns have a hover and pressed state which applies a change to the outline and icon colour. In addition, on hover the background colour changes and on pressed the background colour is again removed, with visible focus applied to the field.
Autocomplete follows the same states as dropdown. Visible focus is applied to the field on pressed and active states.

## 💰 Use value
Ensuring usability and accessibility of components while maintaining consistency across different components.

## Additional info

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
