### ISSUE TITLE
[ic-data-table] Slotted column elements do not appear unless the column key is present in the data objects

### ISSUE THREAD

**Issue by jw18968** [mi6/ic-ui-kit#2866]
## Summary of the bug 
When placing elements with a table row through the use of the slot prop, if the column's key is not present in the data objects, the element is not displayed. 

## 🪜 How to reproduce 
1. From the ["Links and Elements in data" example on the ICDS site](https://design.sis.gov.uk/components/data-table/code#links-and-elements-in-data), open the React example in StackBlitz. You will see that the actions column is empty. 
2. Add the 'actions' key to any of the objects within the data array (example shown below) and the action buttons will appear.
```js
const data = [
    {
      firstName: 'Sarah',
      lastName: 'Smith',
      age: 28,
      actions: undefined
    }
]
```

## 📸 Screenshots or code 
![image](https://github.com/user-attachments/assets/36f7f606-45d3-4303-a847-3b2b6467fb6e)

## 🖥 📱 Device 
- Type: Desktop
- Device: MacBook
- OS version: macOS15 
- Browser version: Chrome 131

## 🧐 Expected behaviour 
I expect the slotted elements to be displayed in the column when the column type is 'element', regardless of whether the column key is present in the provided data.

**Comment by timja** [comment]
@jw18968 I think this fixes your issue: https://github.com/mi6/ic-ui-kit/pull/2760

Mind testing it? Otherwise it will be released soon I expect

**Comment by jw18968** [comment]
@timja #2760 does appear to have fixed this issue! Thanks for pointing me to that.
