### ISSUE TITLE
Tree view: Option for text wrap instead of truncation

### ISSUE THREAD

**Issue by GCHQ-Developer-299** [mi6/ic-ui-kit#2895]
## Summary 
Provide prop for tree items that are too long to wrap instead of truncating, which is the current behaviour. 

Current tree view:
<img width="283" alt="Screenshot 2024-12-11 at 15 48 14" src="https://github.com/user-attachments/assets/e30aaff5-59da-42f2-9c56-fe9c1fb5cf23" />

Old tree view, with overflow:
<img width="288" alt="Screenshot 2024-12-11 at 15 51 33" src="https://github.com/user-attachments/assets/07a1e8be-97c1-484d-b770-137027980a6b" />

## 💬 Description 
Prop could be called "overflowBehaviour" or something

**Comment by MI6-255** [comment]
Default to text wrap onto the next line, and a prop added to truncate

**Comment by MI6-255** [comment]
Add a guidance code example
