### ISSUE TITLE
Investigate our components alongside TypeScript

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#299]
## Summary
A spike to investigate our components alongside TypeScript and playback the information to the wider team. Time boxed to 3 days

## 💬 Description
This should explore building a small TypeScript app (with both React and web components), to discover if TypeScript users need to do anything extra when using our components, including any typical linter requirements. The output of this spike will involve setting up a session with the wider team to demo how it's done and any specifics/issues that the team should be aware of, including making new issues where needed

## 💰 Use value
Have a deeper understanding within the team and discover potential issues before they're reported.

**Comment by GCHQ-Developer-530** [comment]
Update: work so far has been pushed to a new branch in a react testing repo. As work had already started before finding this repo the branch is practically completely different from the existing work on the repo. I've been noting any small typos, questions or typescript issues within comments so they're easily found.

**Comment by GCHQ-Developer-530** [comment]
Tickets created for problems found:

https://github.com/mi6/ic-design-system/issues/253
https://github.com/mi6/ic-design-system/issues/252
https://github.com/mi6/ic-design-system/issues/241
