### ISSUE TITLE
[ic-theme] theme colour/foreground calculation fails with certain colour combinations

### ISSUE THREAD

**Issue by MI6-27** [mi6/ic-ui-kit#3]
## Summary of the bug
A combination of theme colour has been found to result in an incorrect foreground colour calculation.

## 🪜 How to reproduce
Add a IcTheme configuration as follows:

```jsx
<IcTheme color="rgb(154, 126, 74)"></IcTheme>
```

## 🧐 Expected behaviour
I would expect the foreground (text) colour to be white.

Incrementing the RGB values slightly (darker) results in the correct calculation. Assume the formula needs tweaking (screenshot 2)

## 📸 Screenshots or code
<img width="732" alt="image" src="https://user-images.githubusercontent.com/90763452/202189542-1e8096c1-5bc7-4eed-b997-316d7393eefe.png">

Screenshot 2, with `rgb(144, 126, 74)`.
<img width="646" alt="image" src="https://user-images.githubusercontent.com/90763452/202189676-db3148cc-6287-4c5d-bb8d-252a9cd680d7.png">

## 🖥 Desktop
 - OS:  macOS
 - Browser: Chrome
 - Version: 107

**Comment by MI6-255** [comment]
First try revert the changes made to the formula, if not we can try a library
