### ISSUE TITLE
[ic-search]: Tooltip on clear and search buttons do not appear correctly

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#318]
## Summary of the bug
When hovering over the clear and search buttons on ic-search, the tooltip doesn't appear just below the button. 
This issue doesn't not appear for icon buttons or select so is specific for Search Bar

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Type a character into the search bar
2. Hover over clear and search

## 🧐 Expected behaviour
Tooltip should appear directly below button (screenshot from Chrome)

![Capture](https://user-images.githubusercontent.com/116016939/214599564-5a9cd2a4-376a-4071-aca7-2e87f30efd1a.PNG)

## 📸 Screenshots or code
Screenshot from Edge

![Capture](https://user-images.githubusercontent.com/116016939/214599843-c5d76194-301c-4c6d-b1db-e4b989a0afa9.PNG)

## 🖥 Desktop
 - OS: N/A
 - Browser: Edge
 - Version: 109.0.1518.61

## 📱 Mobile
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Comment by ASM995** [comment]
This seems to affect some instances in Edge but not all.

**Comment by jd239** [comment]
This is now happening in:
- Chrome: 109.0.5414.120
- FF Developer Edition: 110.0b6
