### ISSUE TITLE
icSideNavigation zIndex

### ISSUE THREAD

**Issue by MI6-613** [mi6/ic-ui-kit#322]
## Summary of the bug
Tell us, in a few words, what the problem is.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Have a page with IcSideNavigation and some MUI components (chips or data tables work) in the main content
2. Zoom in so that the icSideNavigation drawer overlays over the content
3. You will now see the MUI items appear above the drawer

## 🧐 Expected behaviour
All content is behind the expanded drawer

## 📸 Screenshots or code
If you can, add screenshots to show the problem. If you need to show a code example, you can include a snippet or link to a repository with an example.
<img width="496" alt="Screenshot 2023-01-27 at 13 25 48" src="https://user-images.githubusercontent.com/122873275/215099652-51b0a113-55e2-4135-a404-1fad8ef54fa1.png">
<img width="558" alt="Screenshot 2023-01-27 at 13 25 42" src="https://user-images.githubusercontent.com/122873275/215099763-14ec8e95-05ba-458f-a705-ec875660066b.png">

## 🖥 Desktop
 - OS: Windows & Mac
 - Browser: Chrome
 - Version: 2.1.0-beta.0

**Comment by MI6-682** [comment]
Having looked at the code, I think the solution may be potentially giving the side-nav the same css variable as the ic-classification-banner (--ic-z-index-overlay)?. 

It would also be useful if in the documentation somewhere the z-index of different components was defined and explained. An example of what this could look like and explain from MUI: https://mui.com/material-ui/customization/z-index/

**Comment by jd239** [comment]
> Having looked at the code, I think the solution may be potentially giving the side-nav the same css variable as the ic-classification-banner (--ic-z-index-overlay)?.
> 
> It would also be useful if in the documentation somewhere the z-index of different components were defined and explained. An example of what this could look like and explain from MUI: https://mui.com/material-ui/customization/z-index/

Ticket created: https://github.com/mi6/ic-design-system/issues/313
