### ISSUE TITLE
[ic-chips]: Truncate label if label is too long

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#328]
## Summary
At the moment, a `max-width` is not set on chips, so a very long label will increase the width which goes against the guidance: https://design.sis.gov.uk/components/chips#labels

## 💬 Description
A `max-width` is required on the chips with the label truncating once it overflows past the max width.

## 💰 Use value
Consumers are expecting certain behaviour when using chips based on the guidance provided so the built component should adhere to it. 

## Additional info
Development considerations:
- This might work: https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

Design considerations: 
- Once the text overflows, should there be a tooltip to display the full label?
- What is the `max-width`? Should we set one based on our guidance or give the control to the developers so it's consistent across applications? We can provide the developer with a CSS custom property to set the `max-width`.

**Comment by MI6-255** [comment]
Suggestion is that we won't do  the truncation would cause an accessibility error, design to confirm

**Comment by jd239** [comment]
Relates to https://github.com/mi6/ic-ui-kit/issues/332
