### ISSUE TITLE
Add validation for 'select' components

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#344]
## Summary
Select components don't currently support validation. Need to investigate whether they should. 

## 💬 Description
Select boxes might not need validation as a preferable pattern would to be avoid allowing the user to select an incorrect option from a select box by excluding that option from the available list. 

However, there are times where validation may be useful if for example a combination of inputs causes the validation error and therefore may need to show that it is an invalid selection on the select box. Similarly, there might be a need to show a warning message given a particular selected option. 

## 💰 Use value
This provides more flexibility into the component functionality to allow more use cases to be catered for. 

## Additional info
If we decide to include validation, the same validation pattern as used for text fields should be used. 
Consider this for all types of select - single select, multi-select, searchable-select.

**Comment by GCHQ-Developer-094** [comment]
Won't do for now
