### ISSUE TITLE
Add 'see more' truncation pattern for Typography

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-ui-kit#345]
## Summary
Add optional truncation to the Typography component in a 'see more/see less' pattern with an interactive component to toggle truncation of the text.
 
## 💬 Description
Using a prop to determine the number of lines before truncation, the typography element should be able to display a 'See more' interactive label which when clicked expands allowing full text to be seen and becomes a 'See less' interactive label which when clicked returns the text to the truncated version with 'See more' label.
 
## 💰 User value
A truncation pattern would be useful for situations where a container cannot or should not exceed a certain height by default but where text content which would cause it to exceed this height is required (e.g. cards) 
 
## Acceptance criteria
 
**Given** a user has set a max number of lines on a typography component
**When** the text content of the typography component exceeds this max number of lines
**Then** it should truncate and display a 'See more' interactive element on the last line
 
**Given** text has been truncated 
**When** a user clicks the 'See more' label
**Then** the full text should be displayed with a 'See less' label below the text content
 
 
#Interaction
(see Video example.gif)
 
**Given** the full text with a 'See less' label is visible
**When** a user clicks the 'See less' label
**Then** the text content should return to being truncated with the 'See more' label on the last line
 
**Given** the See more/See less mini-component is based on the standalone link component
**When** a user interacts with the component
**Then** all the interactions are the same (Hover, Pressed, Focus)
**Except** the See more/See less component does not feature the VISITED state
 
 
#Behaviour
 
 **Given** the max amount of lines have been defined
**When** the content does not fit in the provided space
**Then** the truncation point is defined by taking the width of the ‘See more’ component, added to a single space and an ellipses
**And** the last character should be the next full character on that line (see attached photo: Example 1 Redlining)
 
 **Given** that the See more/See less component includes flexibility in its logic
**When** there is additional content - but on a separate paragraph
**And** the last visible line is short enough the house all the content
**Then** no ellipses is shown, and the ‘See more’ component appears after one space-bar key width from the final full stop (see attached photo: Example 2)
 EDIT: agreed with design that the ellipses will still be shown (on a new line)

#Details
 
States:
- Default
- Hover (same as Focused)
- Pressed

Colour:
- Dark variant only

**Comment by fbd399** [comment]
Referenced files:
<img width="594" alt="Example 2" src="https://user-images.githubusercontent.com/117087335/221610885-1fc62e23-5395-4eb1-9fd0-cb63692d82b0.png">
![Video example](https://user-images.githubusercontent.com/117087335/221610888-f373364d-ba2b-4950-927d-fd04191954f1.gif)
<img width="667" alt="Example 1 Redlining" src="https://user-images.githubusercontent.com/117087335/221610892-31a87043-ad18-4dae-aa7e-b526b2546c49.png">

**Comment by fbd399** [comment]
Design done. Moving to 'In refinement'.

**Comment by DBD324** [comment]
Functionality of placing 'see more' in line with truncated text can be added as another story if deemed required.
