### ISSUE TITLE
[@ukic/react]: Use Rollup to generate component library to be used via CDN

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#374]
## Summary
At the moment, it is possible to use the web-components package via unpkg/jsDelivr because of how Stencil packages up the core component library. It would be good to also import the React library into applications in the same manner. 

## 💬 Description
At the moment, we use the default export configuration provided by [react-output-target](https://www.npmjs.com/package/@stencil/react-output-target). It is possible to add a rollup config file into the React library to output the library in different code modules (e.g. CommonJs). 

## 💰 Use value
It will allow consumers to quickly use the React components without setting up a new application. Consumers will be able to quickly fire up a sandbox, reference the library and start using the components straight away. This would allow consumers to also explore the components more freely without committing to setting up a framework on their local machine which is a slower process. 

In addition to the above, it will allow consumers to provide interactive examples of bugs. The sandbox link can been added to the ticket and which allows the Core team to triage the bug more efficiently rather than copying and pasting code or viewing screenshots.  

## Additional info
Rollup: https://rollupjs.org/

**Comment by GCHQ-Developer-299** [comment]
Superceded by Stackblitz and other work.
