### ISSUE TITLE
[@stenciljs]: Investigate Stencil v3.

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#386]
## What is the purpose of the work?

To investigate the benefits to Stencil v3.
- Will improvements will it make to your components?
- Will it improve component optimisation?
- Will this break the react-target-output addon?

## Why do we need it?
An major update provides breaking changes but should also (hopefully) provide a better API. It's worth finding out if our component library can benefit from this.

**Comment by ASM995** [comment]
https://stenciljs.com/docs/introduction/upgrading-to-stencil-three
