### ISSUE TITLE
Issues with MUI Icons in IcSideNavigation

### ISSUE THREAD

**Issue by MI6-682** [mi6/ic-ui-kit#392]
## Summary of the bug
Using MUI Icons in the `IcSideNavigation` causes some unusual bugs with the placement of icons. Also slotted `img` tags with SVGs don't seem to render. I may be misunderstanding the use of `SlottedSVG` but using a `div` has the same issue as in the now closed #263. 

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Create an `IcSideNavigation`
2. Add some `IcNavigationItem`s with MUI Icons in `SlottedSVG`s
3. The icons move unexpectedly when the `IcSideNavigation` is closed

## 🧐 Expected behaviour
The icons remain in the correct place

## 📸 Screenshots or code
```jsx
<IcSideNavigation appTitle="Test App" status="" version="v0.0.7">
    <SlottedSVG slot="app-icon">
        <img src='./Bananas.svg'/>
    </SlottedSVG>
    <IcNavigationItem slot="primary-navigation" href="/" label="Home">
        <SlottedSVG slot='icon'>
            <HomeIcon />
        </SlottedSVG>
    </IcNavigationItem>
    <IcNavigationItem slot="primary-navigation" href="/" label="Trends">
        <SlottedSVG slot='icon'>
            <HomeIcon />
        </SlottedSVG>
    </IcNavigationItem >
    <IcDivider slot ='primary-navigation' />
    <IcNavigationItem
        slot="secondary-navigation"
        href="/"
        label="Test 1"
    >
        <SlottedSVG slot='icon'>
            <HomeIcon />
        </SlottedSVG>
    </IcNavigationItem >
    <IcNavigationItem
        slot="secondary-navigation"
        href="/"
        label="Test 2"
    >
        <SlottedSVG slot='icon'>
            <HomeIcon />
        </SlottedSVG>
    </IcNavigationItem >
</IcSideNavigation >
```
Video:
https://user-images.githubusercontent.com/122810565/219710678-9806c6c2-9601-4735-99b9-6b12d701820c.mov

## 🖥 Desktop
 - OS: macOS
 - Browser: chrome
 - Version: 109

## Additional info
Tell us anything else useful to help us fix or understand the problem.

**Comment by jd239** [comment]
@MI6-682. Thanks for your ticket. We have created a ticket within the guidance site repo to add more detail regarding the `SlottedSVG` component: https://github.com/mi6/ic-design-system/issues/301. We'll make a note to add an example on the Side Navigation code example using MUI Icons as well.

**Comment by MI6-682** [comment]
@jd239 Thanks! Just to clarify, are you saying that the bug shown in the video I attached to the issue is to do with the use of the `SlottedSVG` component or is it an issue with the `IcSideNavigation` component?

**Comment by jd239** [comment]
Hey @MI6-682. It looks like there is an issue with the usage of the `SlottedSVG`.

The `SlottedSVG` provides the `<svg>` tag as the wrapper so in your code example, the SVG is getting rendered as  `<svg><img /></svg>` for the app icon and `<svg><svg></svg></svg>` where `<HomeIcon />` is being used.
 
In the [example](https://design.sis.gov.uk/get-started/install-components/react/#working-with-slotted-svgs) on the guidance site, elements passed as children should be the internal elements of an SVG such as `path`, `circle`, `rect`, [etc...](https://developer.mozilla.org/en-US/docs/Web/SVG/Element).

Our [ticket](https://github.com/mi6/ic-design-system/issues/301) will be explain this further and demonstrate that adding the path from `@mdi/js` is the preferred approach. [@mdi/js](https://pictogrammers.com/library/mdi/)
```jsx
// Example

import { mdiHome } from '@mdi/js';

<IcSideNavigation appTitle="Test App" status="" version="v0.0.7">
    <IcNavigationItem slot="primary-navigation" href="/" label="Home">
      <SlottedSVG
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        slot='icon'
        path={mdiHome}
      />
    </IcNavigationItem>
     ....
```

In addition to this, the `viewBox` is not provided by default so this would also need to be added. For `IcSideNavigation`, the width and height for icons is `24px` so a `viewBox='0 0 24 24'` should display the icons correctly. We'll update the examples on the guidance site to reflect this. We'll look into adding a `rem` width/height via the component for the icons. 

Here is a full example:

```jsx
import { mdiHome } from '@mdi/js';
...
<IcSideNavigation appTitle="Test App" status="" version="v0.0.7">
  <SlottedSVG
    slot="app-icon"
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    path={mdiCompass}
  >
  </SlottedSVG>
  <IcNavigationItem slot="primary-navigation" href="/" label="Home">
    <SlottedSVG
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      slot='icon'
      path={mdiHome}
    />
  </IcNavigationItem>
  <IcNavigationItem slot="primary-navigation" href="/" label="Trends">
    <SlottedSVG
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      slot='icon'
      path={mdiHome}
    />
  </IcNavigationItem>
  <IcDivider slot ='primary-navigation' />
  <IcNavigationItem
      slot="secondary-navigation"
      href="/"
      label="Test 1"
  >
    <SlottedSVG
      path={mdiHome}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      slot='icon'
    />
  </IcNavigationItem >
  <IcNavigationItem
      slot="secondary-navigation"
      href="/"
      label="Test 2"
  >
    <SlottedSVG
      slot='icon'
      path={mdiHome}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
    />
  </IcNavigationItem>
</IcSideNavigation>
```

**Comment by MI6-682** [comment]
Great! Thank you so much :) I had tried the `SlottedSVG`, but didn't know it needed a `viewBox` atribute but that has fixed it!
