### ISSUE TITLE
[github-actions]: Add code coverage checks in pipeline

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#432]
## What is the purpose of the work?
Add code coverage checks to the pipeline so if the coverage is less than 80%, the build should fail. The code coverage command is currently set in our `npm scripts`: https://github.com/mi6/ic-ui-kit/blob/main/packages/web-components/package.json#L23

More info: https://jestjs.io/docs/configuration#coveragethreshold-object

## Why do we need it?
This is an acceptance criteria in our definition of done. Adding these checks in our CI, will prevent anything less than agreed getting through to develop.

**Comment by ad9242** [comment]
We may just be able to set the following in stencil.config.ts
coverageThreshold: {
      './src/components/*/*.tsx': {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      }
    },

this is a slight change to the existing config which will cause each component to require 80% coverage (which was the original intended behaviour)

This change should be made after #441 is resolved
