### ISSUE TITLE
[ic-stepper] Change the colour of the current step

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-ui-kit#435]
## Summary of the bug
The colour for the current step uses the following token: `--ic-theme-primary`. When the theme is changed using `<ic-theme>`, the current step takes on the colour of the new theme

## 🪜 How to reproduce
Run storybook using your local machine or navigate to the [`<ic-ui-kit>` build](https://mi6.github.io/ic-ui-kit/branches/develop)
Open the "Theme" story and select the "Sunrise theme" button
Open the stepper stories and view the current step

## 🧐 Expected behaviour
The colour of the current step should be changed to use the 'info blue' colour. This is more meaningful semantically as a status and avoids being recoloured by the changing theme colour. 

Ensure that changes are made both on default and compact stepper. 

## 📸 Screenshots or code
![Screenshot 2023-02-22 at 17 25 44](https://user-images.githubusercontent.com/113986285/220982095-94ea2783-6b8d-4716-92eb-6a6b0e0c8600.png)

![Screenshot 2023-02-22 at 17 23 45](https://user-images.githubusercontent.com/113986285/220982120-2f7c56f2-2692-4024-b4cf-0c7773cd83ee.png)

Change to info blue:

![Image](https://github.com/mi6/ic-ui-kit/assets/116820773/c9e988b3-760e-41ba-ac0b-6997bed2ce7c)

## 🖥 Desktop
 - OS: macOS

**Comment by MI6-255** [comment]
Awaiting design to confirm which token we should use instead

**Comment by jd239** [comment]
In addition to the task above, add a code example of `currentPage` prop is use.
