### ISSUE TITLE
Add unit tests for missing components and ensure minimum coverage met

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#441]
## What is the purpose of the work?
Need to add tests for the following components:
ic-divider
ic-tab-context
ic-tab-group

as a last resort a statement in code can be preceded by
/* istanbul ignore next */

to cause it to be omitted from the code coverage checks

## Why do we need it?
The components are not currently tested so the code coverage stats are inaccurate. Also to ensure the QA of these components and make sure we do not introduce bugs

**Comment by MI6-255** [comment]
#432
