### ISSUE TITLE
Create a spacing variable for 0.063rem

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#451]
## What is the purpose of the work?

Create a CSS variable with the value '0.063rem' (i.e. 1px). Replace the value in all of the components' styling with this new variable.

## Why do we need it?

'0.063rem' is used in a lot of places throughout the components' styling. It would be good to have a CSS variable for this like there is for other spacing so that it does not have to be repeated every time and the value can be changed easily in one place if necessary.

**Comment by GCHQ-Developer-530** [comment]
Completed: https://github.com/mi6/ic-ui-kit/pull/549
