### ISSUE TITLE
[back-to-top] duplicates target element 

### ISSUE THREAD

**Issue by GCHQ-Developer-465** [mi6/ic-ui-kit#475]
## Summary of the bug
The back-to-top component duplicates target element (as seen on the site) 

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
On https://design.sis.gov.uk
1. Click on any tab / navigation item 
2. Go back to the landing page
3. Click on any tab / navigation item 
4. See duplicates in inspect dev tools

## 🧐 Expected behaviour
Should not duplicate but remove and replace it. 

## 📸 Screenshots or code
![Screenshot 2023-03-14 at 15 39 14](https://user-images.githubusercontent.com/111882114/225055162-503b08b0-bab7-4438-9ea0-e766efc61e41.png)

**Comment by ad9242** [comment]
no longer appears to be an issue. tested by various people
