### ISSUE TITLE
Review components for potential missing attributes supported on native controls

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#515]
## What is the purpose of the work?
Issues have already been raised for IcTextField (#503) and IcButton (#323) regarding missing props that are supported by their native counterparts.

Investigation should be carried out to identify which other components are also missing similar props. For example, possibly other input related components (eg radio, checkbox etc), links

Additionally, explore if we keep props like aria as hidden props.

## Why do we need it?
To produce a list of components requiring changes and then carry out work on each of those components as separate issues

**Comment by j212122** [comment]
Below is a list of the props not currently available in each component but that are supported by native counterparts

**Checkbox:**
-form

**Radio**
- checked
- form

**Search Bar**
- dirname (may not be required?)
- form
- minlength
- pattern

**Select**
- autocomplete
- form
- list

I checked this against https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
