### ISSUE TITLE
Sustainability of the design system  

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#524]
## What is the purpose of the work?
Explore sustainability in terms of the guidance that could be added to the site (how to build sustainable apps, how a design system is sustainable in itself) for teams building apps and baseline our current component offering (how do we measure improvements in sustainability and where we are at now).

Investigate whether there are certain factors regarding sustainability a consumer may be looking for when they are deciding whether to use a design system to gain an insight into how the current state of the sustainability of the ICDS may be affecting adoption.

## Outcome of the spike
- Feedback to team the investigations and explore their ideas
- Documented top 5 suggestions to be more sustainable
- Tickets created that can later be prioritised on how to be more sustainable 

It might be worth looking into any sustainability research or work that has already been done for existing internal apps. 

Time box: 3 days.

**Comment by ad9242** [comment]
One thing to investigate as an outcome of this could be the time taken for the guidance site build. Can anything be done to improve it?
