### ISSUE TITLE
[ic-card]: Message slot structure needs updating so it is not inserted inside `ic-typography`.

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#527]
## Summary of the bug
When using the slot 'message', it is placed inside an `ic-typography` component so there could instances where the code is rendered as...

```jsx
<ic-typography>
     <ic-typography>{message}</ic-typography>
</ic-typography>
```
...when an `ic-typography` is given the slot. There is no guidance on this on the site however, slot adds flexibility to add any component so it shouldn't be surrounded by another component. That should be set by the consumer. 

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Create simple app with `IcCard`
2. Add `<ic-typography slot='message'>Hello World</ic-typography>
3. Inspect the message element

## 🧐 Expected behaviour
The `ic-typography` wrapped in a div instead of an `ic-typography`

## 📸 Screenshots or code
Line: https://github.com/mi6/ic-ui-kit/blob/main/packages/web-components/src/components/ic-card/ic-card.tsx#L265-L275

## 🖥 Desktop
 - OS: Windows
 - Browser: Chrome
 - Version: 110

## 📱 Mobile
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

## Additional info
Tell us anything else useful to help us fix or understand the problem.

**Comment by brf153** [comment]
Hello jd239, I want to work on this issue

**Comment by brf153** [comment]
I wanted to ask you that why don't we wrap ic-typography inside a div directly rather than wrapping it inside slot

**Comment by DxVxDOD** [comment]
Hi I would like to work on this issue.

**Comment by ASM995** [comment]
Need to ensure that this is not a breaking change before beginning work.
