### ISSUE TITLE
Whole width of card increases when the expandable content area is expanded

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#538]
## Summary of the bug
When the expandable content area on a card is expanded, the whole width of the card increases (if there is enough content to make it do so).

## 🪜 How to reproduce
1. Go to a card with expandable content e.g. the first example on the [card component page](https://design.sis.gov.uk/components/cards)
2. Click on the 'expand' button
3. The whole width of the card changes when the expandable content is opened and closed

## 🧐 Expected behaviour
The card should stay the same width

## 📸 Screenshots or code
The card shown below changes from a 335px width -> 360px

<img src="https://user-images.githubusercontent.com/111882109/229145604-4a8adda5-3446-4d04-91b9-537f87e06da2.png" width="300">

## 🖥 Desktop
 - Browser: Chrome

**Comment by ad9242** [comment]
might just be a case of adding `width: inherit` on the `<div class="card">`
