### ISSUE TITLE
XS Left-hand nav does not include any keyboard navigation

### ISSUE THREAD

**Issue by fbd399** [mi6/ic-ui-kit#542]
## Summary of the bug
When the left-hand nav component is open on small width devices, keyboard navigation is not set, so users are not able to navigate to any page

## 🪜 How to reproduce
Reduce screen size so left-hand nav appears as XS variant. Tab to component. Press 'space' to open. Notice how arrows or tabs do not move focus between pages.

## 🧐 Expected behaviour
Up/Down keys should move focus between pages, like select.

**Comment by ASM995** [comment]
Closing as duplicate ticket.

**Comment by ad9242** [comment]
duplicate of: https://github.com/mi6/ic-design-system/issues/421
fixed by https://github.com/mi6/ic-design-system/pull/435
