### ISSUE TITLE
[ic-typography]: Add code typography tokens

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-ui-kit#544]
## Summary of the bug
The code variants for `ic-typography` (seen below, taken from Figma) are not available in the `ic-ui-kit` repo.

<img width="475" alt="Screenshot 2023-03-31 at 20 02 23" src="https://user-images.githubusercontent.com/113986285/229207351-0126e3ee-9918-45e0-b6d5-767a4f15c600.png">

## Acceptance Criteria
1.  Tokens for the code variants should be listed in the `variables.css`
2. The code variants should be listed in the `IcTypographyVariants` type found in the `utils/types.ts` file (so it can be passed through the `variant` prop of `ic-typography`)
3. CSS rulesets should be added to `ic-typography.css` for the code variants
4. The code variants should be added to the "variants" & "vertical margins" stories in `ic-typography.stories.mdx`
5. Unit tests for the code variants should be added to `ic-typography.spec.ts`
6. Visual tests should be updated following the addition to the stories in `ic-typography.stories.mdx`

**Comment by joshmu** [comment]
Hi, I would like to clam this issue as well as #390 

The ticket is completed on my end however visual tests are failing across all components.
This seems to be the case for me on my local machine even on the main branch.

Am I missing any context here?

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1970265/229264337-66db8fbb-f7a5-4660-a158-1c8be15c13b9.png">

**Comment by joshmu** [comment]
I should note after updating the visual tests I still see a variety of unrelated components failing.
It seems to be sporadic each time I try to run the visual tests via the pre-commit hook.
Running the visual test in isolation passes.
<img width="827" alt="image" src="https://user-images.githubusercontent.com/1970265/229265299-069d3e86-a065-45e4-b48b-a9ae6a878a3e.png">
