### ISSUE TITLE
[ic-popover-menu] Escape doesn't always focus the correct anchor button

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#564]
## Summary of the bug
On the design system, there are multiple popover examples on the code tab, and when you click off the popover they correctly focus the anchor button (same when you click a menu item), but pressing escape when the popover is open incorrectly focuses the last anchor button, which technically the other popovers shouldn't even have a connection to.

## 🪜 How to reproduce
Tell us the steps to reproduce the problem:
1. Go to page: components/popover-menu
2. Click on: code tab
3. Open popover
4. Press escape key
5. See the anchor button focus under menu groups.

## 🧐 Expected behaviour
The correct anchor button should focus.

## Additional info
Each of the methods of closing the menu call closeMenu() so I'd have expected them to all do the same thing. The only difference is that escape also calls host.blur() but I'm not sure if that's related or not.

**Comment by GCHQ-Developer-741** [comment]
Possibly related to this issue, the Popover Menu page cannot be tabbed through. When pressing the tab key, it focuses the elements immediately before and after (in the tab order) the last anchor button on the page. This produces the same error message in the console: `TypeError: this.anchorEl is null`
