### ISSUE TITLE
Update side navigation menu items to avoid truncation to improve accessibility

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#570]
## Summary
Currently, side nav menu items with long labels truncate if they can't be displayed in a single line. Whilst this pattern is accessible, as the item can be focussed and therefore the full label is displayed in a tooltip, it doesn't match the other truncation behaviours implemented across the other components. 

## 💬 Description
Update side nav menu items to allow text wrapping. This will mean that the height of the menu item will increase when the side navigation is in expanded mode. 

Update tooltip functionality to stop showing tooltips in expanded side navigation as the full label is now displayed in the menu item itself. 

## 💰 Use value
Improves the experience for wider user group by making the labels visible by default, without the need to focus on the menu item to see the full label. 

## Additional info
Tell us anything else useful to help us understand your suggestion.

**Comment by ASM995** [comment]
Team are investigating whether this ticket is required.

**Comment by ad9242** [comment]
is this now implemented?

**Comment by MI6-255** [comment]
Fixed on another issue already
