### ISSUE TITLE
Add alternating row backgrounds and line divisions to data tables. 

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#583]
## Summary
Add ability to specify alternate row backgrounds on data within data tables. 

## 💰 User value
Row backgrounds makes it easier to scan data from left to right inside a single row. Allows for easier comprehension of data within a single row. 

## 📚 User Stories

**Alternate row backgrounds**
*As an* ICDS user
*I need* to see alternate rows show different backgrounds in a table
*So that* I can easily differentiate between rows without confusing its data with rows above and below

**Line divisions**
As an ICDS user
I need to be able to visually understand the separation between rows of data
So that it is clear which row I am looking at.

## 📝 Acceptance Criteria 
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

**Row backgrounds**
*Given* that a table exists with a number of rows larger than 1
*When* setting its properties
*Then* an option exists to highlight alternate row backgrounds using differing background colours.
*And* this should be turned on by default.

*Given* that a table exists with alternate row highlighting,
*When* rows are added, removed, reordered,
*Then* their highlighting should change so that alternate rows are always highlighted differently.

**Row divisions**
*Given* that a table exists with a number of rows larger than 1
*When* setting its properties
*Then* an option exists to turn off row divisions (lines between rows)
*And* this should be turned on by default. (show row divisions by default)

## ✏ Designs
If there's a Figma design file (or other mock-up), include it here.

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by jd239** [comment]
Linked #519
