### ISSUE TITLE
IcSelect breaks with duplicate options

### ISSUE THREAD

**Issue by MI6-651** [mi6/ic-ui-kit#595]
## Summary of the bug
The IcSelect component breaks when there are two identical options. It highlights both options at the same time, and prevents the user from using arrow keys to navigate the menu.

**Comment by MI6-255** [comment]
The specific issue here is not that two values with the same key and value are selected, it's more the issue the arrow keys fail to work to select the item in that case

**Comment by MI6-255** [comment]
Potentially explore if we should show two values with duplicate keys, to prevent the end user from struggling to use it

**Comment by MI6-255** [comment]
https://github.com/mi6/ic-ui-kit/issues/442
