### ISSUE TITLE
Updated textField to allow use of 'maxlength' and 'minlength' attributes

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#604]
## Summary
Usual html input components allow you to set a maxlength and minlength, which sets the number of characters that can be entered into a field. The ic-text-field component should also provide this functioanlity. 

This differs from the existing prop max-length which is used to display a character count. The terminology used here is a bit confusing, as max-length may cause misunderstanding of its function, as it doesn't actually limit the number of characters that can be entered into the field. 

## 💬 Description
New properties should be created for maxlength and minlength that would work similarly to the html defintion. 

**Maxlength**
An integer value that specifies the maximum allowable characters that can be entered into the field. This actually limits additional characters being entered into the field. This value must be greater than or equal to minlength. If maxlength is exceeded then an error message should be shown stating 'Maximum input is X characters'. 

**minlength**
An integer value that specifies the minimum allowable characters that can be entered into the field.  This value must be less than or equal to maxlength. If minlength is not achieved then an error message should be shown stating 'Minimum input is X characters'. 

**Existing max-length prop**
This property currently is used to show the character count. The terminology here is incorrect, as it it doesn't actually affect the maximum allowable input characters, but instead sets the value of the character count. The user can still enter more characters than the character count into the field. 

Change docs to more accurately describe what this prop does. 

This ticket avoids a breaking change as it won't actually change name of prop, it will just update docs. Breaking change ticket will be raised (#1064) to change the prop name in next major release. 

## 💰 Use value
This attribute can be useful when creating forms as it makes sure the correct input length is adhered to. 

## Additional info
Tell us anything else useful to help us understand your suggestion.

**Comment by gd2910** [comment]
Validation needs clarification, should it display warning/error when limit reached (as maxlength should never be able to be exceeded)? Old max-length should perhaps be changed to 'show-character-count' and be a boolean value, only applicable when new maxlength value set.
