### ISSUE TITLE
Text field error validation without icon or text

### ISSUE THREAD

**Issue by MI6-451** [mi6/ic-ui-kit#612]
## Summary
The text field should allow for 'inline' error validation.

## 💬 Description
The text field currently allows for inline validation but only for 'success' validation. There is a requirement to allow similar functionality for 'error' validation but instead of having the 'error' icon appear in the text field input, as is the case with the 'success' validation, there should be no icon or validation text. Instead, the validation would only be displayed through the red outline of the text field. Guidance should be suggest that where this is used additional means are used to convey the error so it does not solely rely on different colours, e.g. a tooltip displaying the error.

## 💰 Use value
This would allow for a greater range of 'error' validation and is necessary for a pattern on the Pagination bar.

## Additional info
This is linked to/blocks #460

**Comment by MI6-255** [comment]
We discussed in this ticket:
- An event to expose the validation message that pagination can use
- Removing logic from pagination to check min/max values and use min/max from text field 
- Internal prop for turning off the validation text for own use only)
