### ISSUE TITLE
ic-select shows autofill

### ISSUE THREAD

**Issue by GCHQ-Developer-575** [mi6/ic-ui-kit#622]
## Summary of the bug
The ic-select component doesn't have autofill turned off. This means that when the component is in "searchable" mode, the user can receive the default chrome autofill (based on previous searches) over the top of the dropdown selections

## 🪜 How to reproduce
1. Go to a searchable ic-select
2. Search for some options
3. Refresh the page
4. Click the ic-select by the text input area

## 🧐 Expected behaviour
The chrome autofill does not appear

**Comment by ASM995** [comment]
Only regards Autocomplete attritube

**Comment by ASM995** [comment]
Work complete
