### ISSUE TITLE
Aria label issue with menu group without label in popover menu 

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#656]
## Summary of the bug
When adding an `ic-menu-group` without a label to an `ic-popover`, the aria label for the button contains the text "undefined menu group"

## 🪜 How to reproduce
with following code: 
```
 <ic-popover-menu anchor="button-1" aria-label="popover">
   <ic-menu-group>
      <ic-menu-item
        label="Zoom in"
        keyboard-shortcut="Cmd+"
      ></ic-menu-item>
      <ic-menu-item
        label="Zoom out"
        keyboard-shortcut="Cmd-"
      ></ic-menu-item>
    </ic-menu-group>
  </ic-popover-menu>
```

when inspecting the menu-item in the browser developer tools, the aria-label containing "undefined menu group" can be seen

## 🧐 Expected behaviour
Assuming it is ok to have a menu group without a label (the prop is marked as optional), then I would not expect the "undefined menu group" to appear in the aria label for the button

## 📸 Screenshots or code
![image](https://user-images.githubusercontent.com/116102637/236505018-5f0e598e-0a76-4f2b-a970-c22a1a421927.png)

## Additional info
Tell us anything else useful to help us fix or understand the problem.

**Comment by MI6-255** [comment]
Exclude screenreader announcement for unlabelled sections
