### ISSUE TITLE
Make min and max props on text field take string or number

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#677]
## Summary
Change the `min` and `max` props on the text field to accept either a string or number.

## 💬 Description
Currently, the text field only accepts a value for `min` and `max` with type `number`. 

For anyone wishing to use the `min` and `max` props with `type="date"` to get the native calendar pop-up to display (while they wait for the date picker to be developed), this will allow them to customise the range of dates which the user would be allowed to select.

At the moment, if a date string is passed to these props on the text field, because of the `number` type, the whole string is not passed to the native input (e.g. "2022-12-05" is passed as "2022" instead). 

Changing the type to `string | number` fixes this. This would also make the type for these props match that of the same props on a native `<input>`.

## 💰 Use value
The date picker (once developed) will provide this functionality, but in the meantime, this change would allow the text field to have the native calendar pop-up with the minimum / maximum date functionality found on a standard `<input type="date">`.

**Comment by MI6-255** [comment]
We don't want to support TextField supporting dates long term (until DatePicker). Our idea for this ticket is to not add support for "date" (or datetime etc), but to allow strings in min/max, then potentially make a new ticket to remove this support in V3 (do in this ticket to create a new one)
