### ISSUE TITLE
Update status icons to aid recognition

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#713]
## Summary
The ICDS status icons could be improved to aid in recognition. The current icons use similar shapes which can detract from swift recognition when many are used in a single screen. 

The use of only colour can cause issues with accessibility, although the current icon colours all pass required contrast ratios. 

## 💬 Description
Update status icons to use different colours across each, different glyphs, and different background shapes. 

Status icons now have the following unique features:
- Glyph - the iconographic representation inside the status icon is unique to the message. 
- Shape - each status icon has a unique shape, with increasing number of vertices depending on the severity. The shape also matches the mental metaphor created by many road signs with triangles as warning and octagons as stop signs. 
- Colour - the status colour palette has been updated slightly to include new tokens for light, contrast, default and dark variants of each status colour allowing it to be used in many different scenarios. 
- Label - Icons should normally be associated with a label where possible. This would describe the severity of the message and add more detail. 

The new colours have been tested for accessibility with the system text colours and all have a pairing with a text colour that achieves at least 4.5:1. Most have a pairing with a text colour that achieves 7:1. 

New tokens to add:

- Status
  - Success
    - Light
    - Contrast
    - Default
    - Dark
  - Warning
    - Light
    - Contrast
    - Default
    - Dark
  - Error
    - Light
    - Contrast
    - Default
    - Dark
  - Info
    - Light
    - Contrast
    - Default
    - Dark
  - Anomalous
    - Light
    - Contrast
    - Default
    - Dark
  - Status unknown
    - Light
    - Contrast
    - Default
    - Dark

![image](https://github.com/mi6/ic-ui-kit/assets/116820773/db88aa75-56c5-4a45-916f-081529952b2c)

The new status icons to use from the existing icon library are as follows:

- Success: check-circle
- Info: information
- Warning: alert
- Error: close-octagon
- Unknown: help-box

![image](https://github.com/mi6/ic-ui-kit/assets/116820773/0bd50da7-ba1e-413f-8cd2-e534bd74ad49)

## 💰 Use value
This will make the status icons easier to recognize and understand. It will aid accessibility by not relying too much on colour to denote differences. 

## Acceptance Criteria

*Given* that the status palette and icons have been updated
*When* used in other components
*Then* the new icons and colours should be used. 

## Additional info
See Figma branch 'Status icon updates' for details on the new colour styles and icons.

**Comment by GCHQ-Developer-094** [comment]
Still work to be done for Figma components. Re-opening.

**Comment by GCHQ-Developer-094** [comment]
All relevant icons now updated.
