### ISSUE TITLE
Data tables - Epic

### ISSUE THREAD

**Issue by ASM995** [mi6/ic-ui-kit#76]
## Summary
Data tables provide a way to display sets of data to a user and provide navigation functionality, filtering and actions to interact with the data. 

## 💰 User value
Foundational component required to provide ICDS users the tools to build rich applications. Nearly every community team will need to use data tables as a major component within their applications. 

## 📚 User Stories
If relevant, describe the high-level functionality as user stories.

**Keyboard Navigation**
*As a* ICDS user
*I need* to be able to navigate through data in a table using a keyboard
*So that* I have equal access to its content. 

**Table column sorting** 
*As an* ICDS user
*I need* to be able to sort data in a table by values in specific columns
*So that* I can more easily view data from different perspectives. 

**Tooltips**
*As an* ICDS user
*I need* to be able to view the full data in a cell when it is truncated
*So that* I can understand all table data. 

**Truncation on large values**
*As an* ICDS user
*I need* to be able to specify when cell data should truncate vs. wrap
*So that* long data won't cause cells to grow too big. 

**Table Value** 
*As an* ICDS user
*I need* to be able to filter the table data to show rows that match a search term,
*So that* I can view only the data that I'm interested in. 

*As an* ICDS user,
*I need* to be able to filter the data to show rows that contain a search term
*So that* I can view only the data that I'm interested in. 

**Progression/loading behaviour** 
*As an* ICDS user
*I need* to see an indication of data loading when the data in the table changes
*So that* I know how long to wait to see the new data. 

**Breadcrumb**
Existing ICDS component should provide this functionality. 

**Responsive**
*As an* ICDS user
*I need* a way to view all table data regardless of the screen size or viewport that i'm using,
*So that* I am equally able to access all data. 

**Rows checkboxes** 
*As an* ICDS user, 
*I need* a way to select a row in the data table
*So that* table actions can be performed on it. 

**Column checkboxes**
*As an* ICDS user, 
*I need* a way to select a column in the data table
*So that* table actions can be performed on it. 

**Accessibility support**
*As any* ICDS user, 
*I need* to be able to understand all data and perform all actions regardless of my input method and my interaction method,
*So that* I can equally access data. 

**Keyboard focus** 
*As an* ICDS user, 
*I need* to view a focus indicator for any element that can be interacted with, 
*So that* I know where my keyboard actions will target. 

**Toggle density**
*As an* ICDS user
*I need* to be able to specify data density
*So that* I can see more or less data within the same size viewport. 

**Row hover** 
*As an* ICDS user
*I need* to see a row highlighted when hovering (or focusing on a cell)
*So that* I can easily see the other column values associated with that row,
*And* it needs to be clearly distinctive from other row highlighting such as row selection. 

**Zebra stripes**
*As an* ICDS user
*I need* to see every other row coloured differently, 
*So that* it is easy to scan data across the columns in a row without confusing it with rows above and below

**Line divisions**
*As an* ICDS user
*I need* to be able to visually understand the separation between rows of data
*So that* it is clear which row I am looking at.  

**Pagination** 
*As an* ICDS user
*I need* to be able to see data split across multiple pages
*So that* large data tables don't force excessive scrolling.  

*As an* ICDS user
*I need* to be able to specify how many items of data can be viewed per page
*So that* I can control the way I look at the data. 

*As an* ICDS user
*I need* to be able to switch between any page of the data table
*So that* I can navigate easily through the data. 

*As an* ICDS user
*I need* to be able see how many pages of data exist in the table
*So that* I have an awareness of the size of the data set. 

**Contextual hover**
*As an* ICDS user
*I need* to be able to perform actions on individual rows of data
*So that* I can interact with the data. 
(doesn't need to be hover actions, could be achieved with popovers or expansion)

**Basic filtering** 
*As an* ICDS user 
*I need* to be able to filter the data table by column values 

*Date/time range filter*
*Bulk actions* 
*Pre defined formatting* 
*Fluid heigh (text wrap) 
*Skeleton loading*

Slotted cell - allows other comps to be added to a cell or custom layouts for complex stuff. 

## 📝 Acceptance Criteria 
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

*Given*
*When* 
*Then*

## ✏ Designs
If there's a Figma design file (or other mock-up), include it here.

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by DBD324** [comment]
Data tables V1 is captured here:
#519

**Comment by DBD324** [comment]
#586 
#583
