### ISSUE TITLE
Change the name for the data entity component to data list

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-ui-kit#79]
## Summary
Change the name for the data entity component to data list

## 💬 Description
This work involves renaming the component and any references to it should also be changed

## 💰 Use value
To make the functionality of this component clearer to our end users

## Additional info
Tell us anything else useful to help us understand your suggestion.

**Comment by GCHQ-Developer-112** [comment]
This ticket is on hold as changing the name of the data entity component would constitute a breaking change

**Comment by GCHQ-Developer-112** [comment]
The changes for this ticket can be found on this [branch](https://github.com/mi6/ic-ui-kit/tree/79-change-the-name-for-the-data-entity-component-to-data-list)

**Comment by MI6-255** [comment]
To do both guidance and component
