### ISSUE TITLE
Add sort functionality to data tables

### ISSUE THREAD

**Issue by DBD324** [mi6/ic-ui-kit#790]
## Summary
Sort functionality allows the rows in a table to re-ordered based on the user's settings. Sorts can occur on different columns with different data types. Multiple sorts can be applied at same time.

## 💰 User value
Allows contents of data tables to be sorted so the content is easier to locate and consume. 

## 📚 User Stories
If relevant, describe the high-level functionality as user stories.

*As an* ICDS user: 
*I need* to be able to sort my data table by any column
*So that* I can order the data in a way that makes sense to me. 

*As an* ICDS user: 
*I need* to be able to sort by ascending or by descending
*So that* I can order the data either way. 

*As an* ICDS user: 
*I need* to be able to add alphanumeric sort, ascending or descending
*So that* I can order the data.

*As an* ICDS user: 
*I need* to be able to add numeric sort, ascending or descending
*So that* I can order the data.

*As an* ICDS user: 
*I need* to be able to add date sort, ascending or descending
*So that* I can order the data.

~~*An an* ICDS User
*I need* to be able to add multiple concurrent sorts, and see which sort is ordered where, 
*So that* I have better control over my data.~~

## 📝 Acceptance Criteria 
If relevant, describe in full detail the different interactions and edge cases that the component or patterns needs to fulfil.

**Sorting order**
*Given* that a column is sortable
*When* a user clicks on the sort icon button in the column header
*Then* the rows should be sorted initially in ascending order based on the data type:
- Text: Alphanumeric sort (alphabetic)
- Number or Currency: Numeric sort (lowest first)
- Date: Date sort (oldest first)

*Given* that a column is sortable, and is already sorted ascending
*When* a user clicks on the sort icon button in the column header again
*Then* the rows should be sorted descending order based on the data type:
- Text: Alphanumeric sort (alphabetic)
- Number or Currency: Numeric sort (highest first)
- Date: Date sort (newest first)

*Given* that a column is sortable, and is already sorted descending
*When* a user clicks on the sort icon button in the column header again
*Then* the sort should be removed and the rows return to their original unsorted order. 

**Custom sorting order**
*Given* that a table is being set up, and a column is set to be sortable, 
*When* setting its properties, 
*Then* it should be possible to set a custom sorting order. 
For example, instead of the default sorting order being 'ascending, descending, unsorted' it can be changed to 'ascending, unsorted' therefore not allowing a descending sort. Any combination of these can be used. 

**Default sort**
*Given* that a table is being set up, and a column is set to be sortable
*When* setting its initial properties, 
*Then* an initial sort can be added. 
For example, a table showing band names could have a default sort applied to them so that they are initially sorted by age.

Moved to other tickets, see comments:
~~**Sort exclusions**
*Given* that a table is being set up and can be sorted
*When* setting its properties
*Then* certain rows can be excluded from sort to allow them to always appear at the top.~~

~~**Multi-sort**
*Given* that one column is already sorted
*When* clicking on another column and holding down the sort key (windows=ctrl, mac=cmd, or shift on either)
*Then* the new sort is added and each columns sort is identified by a numbered badge.~~

## ✏ Designs
If there's a Figma design file (or other mock-up), include it here.

## 🧾 Guidance
If there's written guidance or documentation, include it here.

**Comment by jd239** [comment]
AC to be moved to another ticket: 

Sort exclusions
Given that a table is being set up and can be sorted
When setting its properties
Then certain rows can be excluded from sort to allow them to always appear at the top.

Multi-sort
Given that one column is already sorted
When clicking on another column and holding down the sort key (windows=ctrl, mac=cmd, or shift on either)
Then the new sort is added and each columns sort is identified by a numbered badge.
