### ISSUE TITLE
Remove name from slot in ic-navigation-item and make it a default slot

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#845]
## Summary
Remove the `"navigation-item"` name from the slot used in the ic-navigation-item component to just make it a default / unnamed slot.

## 💬 Description
At the moment, if passing in a custom link (e.g. a NavLink) to an ic-navigation-item component, you have to add `slot="navigation-item"` to the link. 

It has been reported that this is preventing the ability to re-use code that has been written for the links on the ic-side-navigation to add the same links to the ic-footer.

For example:
A NavLink for an ic-footer (inside an `IcFooterLink` component)
```
<NavLink to="/">Home</NavLink>
```

How the same link would need to be written in an ic-side-navigation (inside an `IcNavigationItem` component)
```
<NavLink to="/" slot="navigation-item">Home</NavLink>
```

^ Removing the name from the slot in ic-navigation-item would mean they could both be written like the first example and so would make it easier for them to be re-used across both components.

The slot name is not needed anyway - the slot named "navigation-item" in the ic-navigation-item component is the only slot, so if you remove the name it would just become the default slot, like it is with ic-footer.

Once the name has been removed from the slot, this ticket will also require some small updates to the ic-navigation-item code (there is a query selector for `[slot="navigation-item"]`) and any use of `slot="navigation-item"` throughout the codebase will need to be removed (e.g. in some of the stories demonstrating React Router usage).

## 💰 Use value
This will allow code for links to be re-used between the ic-footer and ic-side-navigation (and ic-top-navigation).

## Additional info
My initial thoughts were that you could just keep `slot="navigation-item"` when passing the same link to ic-footer - thinking it wouldn't affect anything, but I have tested this and it causes to the footer link to not be displayed.

**Comment by jd239** [comment]
As part of fix, add the default slot for navigation items and use an if statement to determine which slot should be rendered. 
Can be deprecated and then removed for v3

**Comment by jd239** [comment]
Other bugs have been found while working on this ticket so will branch off this to fix https://github.com/mi6/ic-ui-kit/issues/1071 and then PR all together
