### ISSUE TITLE
Add virtual scrolling to components

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#847]
## Summary
Implement virtual scrolling with the ic-menu component.

## 💬 Description
Virtual scrolling is when only the items in a list that are actually visible are rendered in the DOM - ones that have been scrolled past are removed and ones that are about to be displayed are added. See [Build your Own Virtual Scroll](https://dev.to/adamklein/build-your-own-virtual-scroll-part-i-11ib) for a lot more information on the subject.

[React example](https://react-window.vercel.app/#/examples/list/fixed-size) to demonstrate what it's like (inspect the DOM to see how it's working).

There is a [virtual scroll library](https://github.com/ayamflow/virtual-scroll) which might help.

This has benefits from a sustainability perspective as it means only the DOM nodes that are needed are rendered, resulting in lower memory requirements.

_

The best solution for this might be to do something similar to what we've done for the horizontal scroll - create a new virtual scroll component which can be added into the ic-menu, and can later be added to any other components which might need it in the future.

It will be important to check that accessibility is not affected e.g. keyboard navigation, or that ic-menu still works with a screen reader - like reading out the total number of options.

## 💰 Use value
This will minimise the energy consumption of rendering the items in the ic-menu component, especially if it has many options.

**Comment by jd239** [comment]
Build as a separate component to improve sustainability. Create as a wrapper component.

**Comment by GCHQ-Developer-530** [comment]
Ticket created for creation of virtual scroll component: https://github.com/mi6/ic-ui-kit/issues/1082
