### ISSUE TITLE
Introduce canary releases for testing

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#862]
## Summary
Add canary versions to the components with a manual trigger in GitHub Actions.

## 💰 Use value
The introduction of canary releases provides significant benefits for both our team and users:
1. Testing in apps before release: Canary releases enable our team to thoroughly test the components in real applications, ensuring a higher-quality and more stable final product. This testing phase allows us to identify and address any potential issues or bugs before the official release.
2. Early releases for users: Canary releases allow users to access early versions of our components, empowering them to incorporate these enhancements into their own applications. By providing early access, we enable users to stay ahead with the latest features and improvements, enhancing their app development process.

## Additional info
Consider the versioning in npm to prevent cluttering the registry and ensure users who perform npm install do not unintentionally install beta versions.

Use something such as: lerna publish --canary

**Comment by jd239** [comment]
Will close this for now and create a ticket if any further work is required once a released has been completed.
