### ISSUE TITLE
Updates to Date input component for use with Date Picker

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#867]
## Summary
Some enhancements to date input to allow for it's use with Date Picker

- Add a clear button inside the input
- Add a launch picker button inside the input
- Add size variants - default, small & large
- Add max\min support for when typing a date

## Acceptance Criteria
Given that there is a Date input component
When using the component,
Then the user can choose between the default, small and large variants.

Given that a Date input component is being used 
When the input field is focused,
Then a button is visible in the input field to allow clearing the value

Given that a Date input component is being used as a date picker
When the input field is focused,
Then a button is visible in the input field to allow opening of a date picker

Given that a Date input has the `max` prop set
When a user types in the field
Then it should not be possible to enter a date which is greater than the max

Given that a Date input has the `min` prop set
When a user types in the field
Then it should not be possible to enter a date which is less than the min

**Comment by jd239** [comment]
Update to disabledDates prop. Split into:
- disableFromNow / disableFuture
- disableUntilNow / disablePast
