### ISSUE TITLE
[ic-button]: Allow the height of `ic-button` to either stretch or be customisable

### ISSUE THREAD

**Issue by GCHQ-Developer-112** [mi6/ic-ui-kit#914]
## Summary
Use the `min-height` CSS property instead of the `height` property on `ic-button` to allow the button height to stretch to the height of its content

## 💰 Use value
At the moment, the button's height doesn't grow and so the slotted content overflows the button creating a bad user experience. This is still an issue if I use the `size="large"` prop.
![Screenshot 2023-07-18 at 15 00 23](https://github.com/mi6/ic-ui-kit/assets/113986285/e7ce4d45-1470-4f70-9be2-21ec87851aef)

When I change the `height` property to `min-height` in dev tools, the button looks and behaves as expected
![Screenshot 2023-07-18 at 15 00 09](https://github.com/mi6/ic-ui-kit/assets/113986285/1ceeee53-0f76-4461-9870-c9245be0d318)

**Comment by DBD324** [comment]
So ic-button shouldn't currently support the ability to position an icon above the label. We may want to consider if we want to allow this behaviour, or if we want to control it somehow. 

The size property defines the button's vertical height. Perhaps we could add a 'custom' value here which would then enable the height to be customised, but I'd warn against it to avoid button heights being specified randomly. The current size options can be considered as defaults, which allow the quick alignment of components with one another when used at the same size. 

With the property set as it is now, if button text wrapped onto multiple lines, would the height of the button still change? Or would the text overflow the edge of the button?
