### ISSUE TITLE
[ic-search-bar]: Inconsistent search bar test regarding focus state.

### ISSUE THREAD

**Issue by jd239** [mi6/ic-ui-kit#928]
## Summary of the bug
The following test fails intermittently when running within the CI/CD pipeline. The following error appears:
```bash
@ukic/web-components:  FAIL  src/components/ic-search-bar/test/basic/ic-search-bar.e2e.ts (88.588 s)
@ukic/web-components:   ● ic-search-bar › focuses back onto search bar from menu
@ukic/web-components:     expect(received).toBe(expected) // Object.is equality
@ukic/web-components:     Expected: "ic-search-bar-input-0-menu-bar"
@ukic/web-components:     Received: "ic-search-bar-input-0-menu"
@ukic/web-components: 
@ukic/web-components:       1004 |     });
@ukic/web-components:       1005 |
@ukic/web-components:     > 1006 |     expect(focusedElement).toBe("ic-search-bar-input-0-menu-bar");
@ukic/web-components:            |                            ^
@ukic/web-components:       1007 |
@ukic/web-components:       1008 |     await page.waitForChanges();
@ukic/web-components:       1009 |
```

## 🧐 Expected behaviour
E2E test should pass.

## 🖥 Desktop
N/A

## 📱 Mobile
N/A

## Additional info
N/A

**Comment by jd239** [comment]
Another test to check over:
ic-select › searchable › should still filter the options when the input is changed after selecting an option

![Capture](https://github.com/mi6/ic-ui-kit/assets/116016939/de331e0c-fbcb-480b-ac38-2e10bb450b97)

**Comment by GCHQ-Developer-299** [comment]
`@ukic/web-components:  FAIL  src/components/ic-search-bar/test/basic/ic-search-bar.e2e.ts (95.003 s)
@ukic/web-components:   ● ic-search-bar › should trigger a retry when the retry button is pressed using space and enter
@ukic/web-components:     expected textContent "Loading..." to equal "ErrorLoading ErrorRetry"
@ukic/web-components: 
@ukic/web-components:       1589 |       "ic-search-bar >>> ic-text-field ic-menu li"
@ukic/web-components:       1590 |     );
@ukic/web-components:     > 1591 |     expect(menuOptions[0]).toEqualText("Loading...");
@ukic/web-components:            |                            ^
@ukic/web-components:       1592 |   });
@ukic/web-components:       15[93](https://github.com/mi6/ic-ui-kit/actions/runs/5762001349/job/15620948450#step:5:94) |
@ukic/web-components:       15[94](https://github.com/mi6/ic-ui-kit/actions/runs/5762001349/job/15620948450#step:5:95) |   it("should cancel loading when clear button is pressed", async () => {
@ukic/web-components: 
@ukic/web-components:       at Object.<anonymous> (src/components/ic-search-bar/test/basic/ic-search-bar.e2e.ts:1591:28)
@ukic/web-components:           at runMicrotasks (<anonymous>)`

Had another Search bar test fail sporadically.

**Comment by jd239** [comment]
Inconsistent loki test: Web Components\\/Page header With stepper\$
