### ISSUE TITLE
Pagination items per page, 1 of n and goto page 

### ISSUE THREAD

**Issue by jonnorton** [mi6/ic-ui-kit#935]
## Summary
I can see at the bottom of the website a pagination example with items per page, 1 of n and goto page, is this part of the pagination toolbar because last time I looked at pagination code could not see this fucntionality in the pagination bar. 

https://design.sis.gov.uk/components/pagination

**Comment by jd239** [comment]
Hi @jonnorton. Pagination items per page, 1 of n and go to page are atoms which form part of a more enhanced pagination  component called `ic-pagination-bar`. This code is not stored within the pagination component you have linked above. We are currently working on updating the guidance before officially releasing the pagination bar as it's own entity.

**Comment by DBD324** [comment]
The guidance relating to the pagination bar was initially included in the pagination guidance that can be found here:
https://design.sis.gov.uk/components/pagination

We have decided to split this guidance page into two, one for pagination, and one for pagination bar. We have raised a ticket (https://github.com/mi6/ic-design-system/issues/555) to make this change.
