### ISSUE TITLE
Add right icon variant to IC-Button

### ISSUE THREAD

**Issue by ad9242** [mi6/ic-ui-kit#974]
## What is the purpose of the work?
To add an option to have an icon to the right of the label for th eic-button component

## Why do we need it?
This is initially required for the buttons on the datepicker, but would be a generally useful enhancement

## 📚 User Stories

As a date picker user
I need to 
So that

**Comment by ad9242** [comment]
could we also fix an issue where the stories have all the buttons heights as 9rem?
![image](https://github.com/mi6/ic-ui-kit/assets/116102637/cde2554e-47a3-4a2d-81f5-03c96fd7d692)

**Comment by MI6-255** [comment]
Introduce leftIcon and rightIcon, deprecate icon and add a new ticket to remove in v3
