### ISSUE TITLE
Upgrade Storybook to v7 

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#977]
## Summary
Upgrade Storybook from version 6 to version 7 and implement necessary structural changes.

## 💬 Description
Currently, our codebase utilises Storybook version 6 for component development and testing. To keep up with the latest features and improvements, we need to upgrade Storybook to version 7. This upgrade requires making structural changes to adapt to the new version's APIs and convention. More information can be found here: https://storybook.js.org/docs/react/migration-guide

## 💰 Use value
Ensures our component development environment remains up-to-date and utilise the latest features.

**Comment by GCHQ-Developer-530** [comment]
This is currently blocked. 

Work has been completed on branch 977-upgrade-to-storybook-7, however there is an issue with loki tests and version 7 of storybook. 

Once [this PR](https://github.com/oblador/loki/pull/472) has been merged, we should be able to pick up this work again.
