### ISSUE TITLE
Performance improvement of components

### ISSUE THREAD

**Issue by MI6-255** [mi6/ic-ui-kit#978]
## Summary
Explore retrospective and future measures for enhancing component performance. This spike aims to assess current component efficiency and establish steps for ongoing optimisation.

## 💬 Description
This spike involves investigating strategies to boost the performance of our components retrospectively and to integrate performance checks into our development process moving forward, including:

1. Conduct an assessment of existing components performance by running Lighthouse scores on our website's pages where components are used.
2. Identify areas for improvement based on Lighthouse scores and component-level analysis.
3. Create separate issues for specific actions needed to enhance component performance, in either ic-ui-kit or ic-design-system if  it is website related.

The outcome of this spike will be a set of actionable recommendations to optimise existing components and ways to incorporate performance checks in our Definition of Done for future pull requests.

## 💰 Use value
To ensure our components have optimal loading times and responsiveness, improving the user experience.

**Comment by MI6-255** [comment]
Next steps: set up the CI to get all components run performance testing using Lighthouse for all components

**Comment by MI6-286** [comment]
Performance testing setup is now complete. Next tasks will be adding tests.
