### ISSUE TITLE
Add color-scheme CSS property to Storybook

### ISSUE THREAD

**Issue by GCHQ-Developer-847** [mi6/ic-ui-kit#991]
## Summary
Add the `color-scheme` property to Storybook to facilitate testing of components for when a user has their system dark mode enabled.

## 💬 Description
Setting the `color-scheme` CSS property in an app allows the system dark mode on a user's device to take effect on pages of the app e.g. it may change the background colour from white to black.

We are adding the testing of components in system dark mode to our testing checklist for PRs, so to make this easier, it is worth adding the `color-scheme` property to the CSS in Storybook. It should be set to `light dark` to allow system light and dark modes to affect the appearance of Storybook, i.e.:
```
:root {
  color-scheme: light dark;
}
```

We need to ensure we are not adding this to the CSS in our NPM packages so it doesn't get imported and added to consumers' apps. It could perhaps be added to a new CSS file in the root directory.

## 💰 Use value
This will make it easier to test that components will work / look correct when they are used in apps with the user's system dark mode enabled. (The alternative solution would be to add a new CSS rule in Styles in Chrome DevTools each time you want to view a component in dark mode).

## Additional info
For more information about this subject, I have created a guide within the internal knowledge base.

**Comment by Vidhanvyrs** [comment]
I think i can help with this just lemme ask a simple query
exactly where do the changes should be added is it in packages/react/.storybook or packages/web-components/.storybook 
in which storybook folder and in which file should it be added is it preview.js or main.js??
