### ISSUE TITLE
Remove deprecated status colour variables

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit#996]
## Summary
In variables.css, under the status colours, there are a few variables that have been deprecated and they need removing.

## 💬 Description
<img width="519" alt="Screenshot 2023-08-14 at 08 33 19" src="https://github.com/mi6/ic-ui-kit/assets/111882034/33391662-a7bf-4b33-a6ca-c51ca924a8b4">

For V3, none of these colours should be available as they're already covered off by variables with other names.

## 💰 Use value
Users won't be able to access variables that won't do anything.

**Comment by MI6-255** [comment]
Add guidance too
